import PNP

#print axioms PNP.Concrete.CookLevin.BuilderFirstClausePaddingRun.PaddingCountdown.machine
#print axioms PNP.Concrete.CookLevin.BuilderFirstClausePaddingRun.PaddingCountdown.loop_workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderFirstClausePaddingRun.PaddingCountdown.loopSteps_le

#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingPolynomial
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingCount
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingCount_eq
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingCount_eq_remaining_first_constraint
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingCount_positive
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.secondConstraintStartPolynomial
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.secondConstraintStart
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.secondConstraintStart_eq
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.predecessorSlot_add_paddingCount

#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countEvaluator
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.targetEvaluator
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countdownTargetMachine
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingSuffixMachine
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.machine
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.rules_length
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.rules_pairwise_query_distinct
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.machine_acceptState_ne_rejectState
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.rule_source_ne_acceptState

#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countWord
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countRootPrefixLength
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countControllerPrefixLength
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countOutside
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countTape
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countdownFinalOutside
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countdownFinalTape
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalOutside
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalTape
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalConfiguration
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countdownWorkSteps
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.suffixWorkSteps
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.workSteps

#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalTape_represents
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countEvaluator_workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countdown_workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.targetEvaluator_workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.prefix_workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.launch_workStep
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.workRunExact

#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.paddingSlot_direct_eq_padding
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.secondConstraintStart_direct_eq_sep
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.specificationRun
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.specification_padding_run
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.specification_target_step
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalTokenBits_eq_encodedFormula_fourthClause
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalTokenSlot
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalTokenSlot_eq_secondConstraintStart
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalOutside_contains_finalTokenSlot
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.finalConfiguration_state

#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countdownBoundPolynomial
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.rawTimeBound
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.countdownBoundPolynomial_eval
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.rawTimeBound_eval
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.rawTimeBound_le
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.run_compile_exact
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.run_compile_rawTimeBound
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.run_compile_rawTimeBound_blankEquivalent
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.boundedDecide_compile_accept
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.boundedDecide_compile_ne_timeout
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.workBoundedDecide_accept

#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.malformedCountdownScratchConfiguration
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.malformedCountdownRootConfiguration
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.malformedCountdownScratch_timeout
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.malformedCountdownRoot_timeout
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.prefixEndpoint_before_launch_timeout
#print axioms PNP.Concrete.CookLevin.BuilderFirstConstraintPaddingRun.work_one_step_short_timeout
