import PNP

#print axioms PNP.Concrete.CookLevin.assignmentAt_exists_of_lt
#print axioms PNP.Concrete.CookLevin.assignmentOf
#print axioms PNP.Concrete.CookLevin.assignmentOf_length
#print axioms PNP.Concrete.CookLevin.assignmentAt_assignmentOf
#print axioms PNP.Concrete.CookLevin.BoundedLiteral
#print axioms PNP.Concrete.CookLevin.BoundedLiteral.emit
#print axioms PNP.Concrete.CookLevin.BoundedLiteral.Holds
#print axioms PNP.Concrete.CookLevin.BoundedLiteral.negate
#print axioms PNP.Concrete.CookLevin.BoundedLiteral.emit_variable_lt
#print axioms PNP.Concrete.CookLevin.BoundedLiteral.emit_satisfied_iff
#print axioms PNP.Concrete.CookLevin.BoundedLiteral.negate_holds_iff_not
#print axioms PNP.Concrete.CookLevin.BoundedLiteral.holds_or_negate_holds
#print axioms PNP.Concrete.CookLevin.BoundedClause
#print axioms PNP.Concrete.CookLevin.BoundedClauses
#print axioms PNP.Concrete.CookLevin.BoundedClause.emit
#print axioms PNP.Concrete.CookLevin.BoundedClause.Holds
#print axioms PNP.Concrete.CookLevin.BoundedClause.AllHold
#print axioms PNP.Concrete.CookLevin.BoundedClause.negated
#print axioms PNP.Concrete.CookLevin.BoundedClause.emit_length
#print axioms PNP.Concrete.CookLevin.BoundedClause.emitted_variable_lt
#print axioms PNP.Concrete.CookLevin.BoundedClause.emit_satisfied_iff
#print axioms PNP.Concrete.CookLevin.BoundedClause.holds_append
#print axioms PNP.Concrete.CookLevin.BoundedClause.singleton_holds_iff
#print axioms PNP.Concrete.CookLevin.BoundedClause.negated_holds_iff_not_allHold
#print axioms PNP.Concrete.CookLevin.BoundedClause.allHold_or_negated_holds
#print axioms PNP.Concrete.CookLevin.BoundedClauses.emit
#print axioms PNP.Concrete.CookLevin.BoundedClauses.Holds
#print axioms PNP.Concrete.CookLevin.BoundedClauses.emit_length
#print axioms PNP.Concrete.CookLevin.BoundedClauses.emitted_variable_lt
#print axioms PNP.Concrete.CookLevin.BoundedClauses.emit_satisfied_iff
#print axioms PNP.Concrete.CookLevin.BoundedClauses.holds_append
#print axioms PNP.Concrete.CookLevin.BoundedClauses.length_append
#print axioms PNP.Concrete.CookLevin.unitClauses
#print axioms PNP.Concrete.CookLevin.implicationClause
#print axioms PNP.Concrete.CookLevin.implicationClauses
#print axioms PNP.Concrete.CookLevin.unitClauses_holds_iff
#print axioms PNP.Concrete.CookLevin.implicationClauses_holds_iff
#print axioms PNP.Concrete.CookLevin.trueLiteral
#print axioms PNP.Concrete.CookLevin.falseLiteral
#print axioms PNP.Concrete.CookLevin.atLeastOneBoundedClause
#print axioms PNP.Concrete.CookLevin.excludeBoundedPairClause
#print axioms PNP.Concrete.CookLevin.excludeBoundedWithClauses
#print axioms PNP.Concrete.CookLevin.atMostOneBoundedClauses
#print axioms PNP.Concrete.CookLevin.exactlyOneBoundedClauses
#print axioms PNP.Concrete.CookLevin.AnyTrue
#print axioms PNP.Concrete.CookLevin.AtMostOneTrue
#print axioms PNP.Concrete.CookLevin.ExactlyOneTrue
#print axioms PNP.Concrete.CookLevin.falseLiteral_eq_negate_trueLiteral
#print axioms PNP.Concrete.CookLevin.atLeastOneBoundedClause_holds_iff
#print axioms PNP.Concrete.CookLevin.excludeBoundedPairClause_holds_iff
#print axioms PNP.Concrete.CookLevin.excludeBoundedWithClauses_holds_iff
#print axioms PNP.Concrete.CookLevin.atMostOneBoundedClauses_holds_iff
#print axioms PNP.Concrete.CookLevin.exactlyOneBoundedClauses_holds_iff
#print axioms PNP.Concrete.CookLevin.LocalConstraint
#print axioms PNP.Concrete.CookLevin.LocalConstraint.emit
#print axioms PNP.Concrete.CookLevin.LocalConstraint.Holds
#print axioms PNP.Concrete.CookLevin.LocalConstraint.pairCount
#print axioms PNP.Concrete.CookLevin.LocalConstraint.clauseCount
#print axioms PNP.Concrete.CookLevin.LocalConstraint.excludeBoundedWithClauses_length
#print axioms PNP.Concrete.CookLevin.LocalConstraint.atMostOneBoundedClauses_length
#print axioms PNP.Concrete.CookLevin.LocalConstraint.exactlyOneBoundedClauses_length
#print axioms PNP.Concrete.CookLevin.LocalConstraint.emit_length
#print axioms PNP.Concrete.CookLevin.LocalConstraint.emit_holds_iff
#print axioms PNP.Concrete.CookLevin.LocalProgram
#print axioms PNP.Concrete.CookLevin.LocalProgram.emit
#print axioms PNP.Concrete.CookLevin.LocalProgram.Holds
#print axioms PNP.Concrete.CookLevin.LocalProgram.clauseCount
#print axioms PNP.Concrete.CookLevin.LocalProgram.toFormula
#print axioms PNP.Concrete.CookLevin.LocalProgram.emit_length
#print axioms PNP.Concrete.CookLevin.LocalProgram.emitted_clause_count
#print axioms PNP.Concrete.CookLevin.LocalProgram.emit_holds_iff
#print axioms PNP.Concrete.CookLevin.LocalProgram.toFormula_satisfied_iff
#print axioms PNP.Concrete.CookLevin.LocalProgram.toFormula_satisfiable_iff
#print axioms PNP.Concrete.CookLevin.FormulaWellScoped
#print axioms PNP.Concrete.CookLevin.localProgram_formula_wellScoped
