import PNP

/- Exact root-import axiom audit for computational recoding in complete programs. -/

#print axioms PNP.DirectWire.StructuralReindexing.GateRenaming.decode_encode
#print axioms PNP.DirectWire.StructuralReindexing.GateRenaming.encode_length_le
#print axioms PNP.DirectWire.StructuralReindexing.GateRenaming.validCode_encode
#print axioms PNP.DirectWire.WireCarrierRecoding.roundTripCheck_iff
#print axioms PNP.DirectWire.WireCarrierRecoding.check_iff
#print axioms PNP.DirectWire.WireCarrierRecoding.compile_success_iff
#print axioms PNP.DirectWire.WireCarrierRecoding.appendMap_gateCount
#print axioms PNP.DirectWire.WireCarrierRecoding.appendMap_output
#print axioms PNP.DirectWire.WireCarrierRecoding.appendMap_field
#print axioms PNP.DirectWire.WireCarrierRecoding.encoded_output
#print axioms PNP.DirectWire.WireCarrierRecoding.encoded_field
#print axioms PNP.DirectWire.WireCarrierRecoding.result_output
#print axioms PNP.DirectWire.WireCarrierRecoding.result_field
#print axioms PNP.DirectWire.WireCarrierRecoding.result_gate_balance
#print axioms PNP.DirectWire.CausalBound.levels_bounded_iff
#print axioms PNP.DirectWire.CausalBound.source_bounded_iff
#print axioms PNP.DirectWire.CausalBound.sourceDependencyGuard_iff
#print axioms PNP.DirectWire.CausalBound.candidateDependencyGuard_iff
#print axioms PNP.DirectWire.WireCarrier.dependencyGuard_iff
#print axioms PNP.DirectWire.WireObligationHistory.State.recode_pending
#print axioms PNP.DirectWire.WireObligationHistory.State.recode_charged
#print axioms PNP.DirectWire.WireObligationHistory.State.recode_removed
#print axioms PNP.DirectWire.WireObligationHistory.State.recode_causalInvariant
#print axioms PNP.DirectWire.WireRecodingState.execute_success_iff
#print axioms PNP.DirectWire.WireRecodingState.execute_failure_iff
#print axioms PNP.DirectWire.WireRecodingState.Receipt.pending
#print axioms PNP.DirectWire.WireRecodingState.Receipt.causalInvariant
#print axioms PNP.DirectWire.WireRecodingState.Receipt.gate_balance
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.encoder_positions
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.encoded_origin
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.decoder_positions
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_origin
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_charged
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_removed_length
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_partition
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.allocation_phases_nodup
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.physical_ownership
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.labelled_live
#print axioms PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.labelled_physical_ownership
#print axioms PNP.DirectWire.WireRecodingState.Receipt.physical_ownership
#print axioms PNP.DirectWire.WireRecodingInput.decode_encode
#print axioms PNP.DirectWire.WireRecodingInput.decode_elaboration_none
#print axioms PNP.DirectWire.WireRecodingInput.decode_success_iff
#print axioms PNP.DirectWire.WireRecodingInput.execute_success_iff
#print axioms PNP.DirectWire.WireRecodingInput.execute_encoder_none
#print axioms PNP.DirectWire.WireRecodingInput.execute_decoder_none
#print axioms PNP.DirectWire.WireRecodingInput.Receipt.pending
#print axioms PNP.DirectWire.WireRecodingInput.Receipt.charged_eq
#print axioms PNP.DirectWire.WireRecodingInput.Receipt.removed_eq
#print axioms PNP.DirectWire.WireRecodingInput.Receipt.causalInvariant
#print axioms PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_origin
#print axioms PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_charged
#print axioms PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_removed
#print axioms PNP.DirectWire.WireOpenProgram.orderEvents_success_iff
#print axioms PNP.DirectWire.WireOpenProgram.orderEvents_failure_iff
#print axioms PNP.DirectWire.WireOpenProgram.execute_failed_tail
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.full_output
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.full_field
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.creation_lifecycle
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.executed_count
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.executed_identities_nodup
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.causalInvariant
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.physical_ownership
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.ownership_origin_injective
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.ownership_charge_origin
#print axioms PNP.DirectWire.WireOpenProgram.compile_exists_iff
#print axioms PNP.DirectWire.WireOpenProgram.compile_none_iff
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.records_source
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.proper_support
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.output
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.field
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.charge_accounting
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictGain
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictResidualDescent
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.physical_ownership
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.closed_ledger
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.creation_lifecycle
#print axioms PNP.DirectWire.WireOpenCertificate.verify_exists_iff
#print axioms PNP.DirectWire.WireOpenCertificate.verify_sound
#print axioms PNP.DirectWire.WireOpenCertificate.verify_decode_none
#print axioms PNP.DirectWire.WireOpenCertificate.verify_program_none
#print axioms PNP.DirectWire.WireOpenCertificate.verify_not_proper
#print axioms PNP.DirectWire.WireOpenCertificate.verify_no_gain
#print axioms PNP.DirectWire.WireOpenProgram.Transition.charged_eq
#print axioms PNP.DirectWire.WireOpenProgram.Transition.removed_eq
#print axioms PNP.DirectWire.WireOpenProgram.Transition.causalInvariant
#print axioms PNP.DirectWire.WireOpenProgram.Transition.local_physical_ownership
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.gate_balance
