import PNP

#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.rectangleCoordinate?
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.rectangleCoordinate?_eq_none_iff
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.rectangleCoordinate?_reconstruct
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.rectangle_eq_coordinate?
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.PostHeaderRoute
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.postHeaderRoute
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.postHeaderRoute_eq_body_iff
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.postHeaderRoute_eq_finish_iff
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.postHeaderRoute_eq_outOfRange_iff
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.postHeaderRoute_body_reconstruct
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.PostHeaderRoute.token?
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.postHeaderSlotDirect_route
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.decodedTokenSlotDirect
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.formulaTokenSlotDirect_decoded
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.RawRemainder.configurationPostHeaderRemainder?
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.RawRemainder.comparisonResultPostHeaderRemainder?
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.RawRemainder.configurationPostHeaderRemainder?_resultConfiguration
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.RawRemainder.compareResult_postHeaderRemainder?
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.RawRemainder.finalConfiguration_postHeaderRemainder?
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.RawRemainder.finalConfiguration_postHeaderRemainder?_eq_outerRoute
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.postHeaderRoute_in_range
#print axioms PNP.Concrete.CookLevin.BuilderArbitrarySlotPostHeaderDecoder.cook_levin_arbitrary_slot_post_header_decoder_checked_complete
