import PNP

#print axioms PNP.Concrete.PipelineSequentialStateNamespace.firstPipelineState
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.secondPipelineState
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.firstPipelineState_injective
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.secondPipelineState_injective
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.firstPipelineState_ne_secondPipelineState
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.renamedFirstPipeline
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.renamedSecondPipeline
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.firstAcceptLaunchRules
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.firstRejectLaunchRules
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.sequentialRules
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.sequentialWorkMachine
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.sequentialWorkMachine_acceptState_ne_rejectState
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.state_ne_accept_of_isHalted_false
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.state_ne_reject_of_isHalted_false
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.nat_beq_false_of_ne
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.sequentialWorkMachine_isHalted_first_false
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.sequentialWorkMachine_isHalted_second_false_of_local
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.findWorkRule_sequential_first_of_some
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.findWorkRule_sequential_second_of_some
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.first_workStep?_of_some
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.second_workStep?_of_some
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.workRunExact?_transport
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.first_workRunExact_of_exact
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.second_workRunExact_of_exact
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.firstAcceptLaunch_workStep
#print axioms PNP.Concrete.PipelineSequentialStateNamespace.firstRejectLaunch_workStep
