import PNP

#print axioms PNP.DirectWire.ComputedWireProfileCost.full_minimum
#print axioms PNP.DirectWire.ComputedWireProfileCost.minimum_gap
#print axioms PNP.DirectWire.ComputedWireProfileCost.quotient_minimum
#print axioms PNP.DirectWire.FreshNandCost.erased_constant
#print axioms PNP.DirectWire.FreshNandCost.erased_count_lower_bound
#print axioms PNP.DirectWire.FreshNandCost.extend_gateCount
#print axioms PNP.DirectWire.FreshNandCost.extended_equivalent
#print axioms PNP.DirectWire.FreshNandCost.extended_fresh
#print axioms PNP.DirectWire.FreshNandCost.extended_old
#print axioms PNP.DirectWire.FreshNandCost.freshCandidate_semantics
#print axioms PNP.DirectWire.FreshNandCost.freshConditions
#print axioms PNP.DirectWire.FreshNandCost.freshGate_injective
#print axioms PNP.DirectWire.FreshNandCost.freshGate_selected
#print axioms PNP.DirectWire.FreshNandCost.freshGate_source
#print axioms PNP.DirectWire.FreshNandCost.freshGate_value
#print axioms PNP.DirectWire.FreshNandCost.freshValue_joinInput
#print axioms PNP.DirectWire.FreshNandCost.freshValue_restricted
#print axioms PNP.DirectWire.FreshNandCost.gateCount_lower_bound
#print axioms PNP.DirectWire.FreshNandCost.inputNands_eval
#print axioms PNP.DirectWire.FreshNandCost.oldCandidate_semantics
#print axioms PNP.DirectWire.FreshNandCost.padInputs_semantics
#print axioms PNP.DirectWire.FreshNandCost.profile_field
#print axioms PNP.DirectWire.FreshNandCost.profile_fullMinimum
#print axioms PNP.DirectWire.FreshNandCost.profile_fullSlack
#print axioms PNP.DirectWire.FreshNandCost.profile_gateCount
#print axioms PNP.DirectWire.FreshNandCost.profile_materializer_charge_lower_bound
#print axioms PNP.DirectWire.FreshNandCost.profile_output
#print axioms PNP.DirectWire.FreshNandCost.profile_projectionDefect
#print axioms PNP.DirectWire.FreshNandCost.profile_quotientMinimum
#print axioms PNP.DirectWire.FreshNandCost.referenceMinimum_extend
#print axioms PNP.DirectWire.FreshNandCost.referenceMinimum_padInputs
#print axioms PNP.DirectWire.FreshNandCost.restricted_oldInput
#print axioms PNP.DirectWire.SemanticGateRetraction.gateCount_eq_sub
#print axioms PNP.DirectWire.SemanticGateRetraction.gateCount_partition
#print axioms PNP.DirectWire.SemanticGateRetraction.kept_gate_value
#print axioms PNP.DirectWire.SemanticGateRetraction.reboundSource_value
#print axioms PNP.DirectWire.SemanticGateRetraction.semantics
#print axioms PNP.DirectWire.WireProfileAmbient.available_iff_exists
#print axioms PNP.DirectWire.WireProfileAmbient.available_pad
#print axioms PNP.DirectWire.WireProfileAmbient.available_pad_iff
#print axioms PNP.DirectWire.WireProfileAmbient.available_reword
#print axioms PNP.DirectWire.WireProfileAmbient.eval_paddedSource
#print axioms PNP.DirectWire.WireProfileAmbient.eval_retractSource
#print axioms PNP.DirectWire.WireProfileAmbient.model_observe_coherent
#print axioms PNP.DirectWire.WireProfileAmbient.pad_fieldValue
#print axioms PNP.DirectWire.WireProfileAmbient.pad_gateCount
#print axioms PNP.DirectWire.WireProfileAvailability.available_of_source
#print axioms PNP.DirectWire.WireProfileAvailability.bind_fieldValue
#print axioms PNP.DirectWire.WireProfileAvailability.bind_full
#print axioms PNP.DirectWire.WireProfileAvailability.bind_gateCount
#print axioms PNP.DirectWire.WireProfileAvailability.bind_implementation
#print axioms PNP.DirectWire.WireProfileAvailability.bind_quotient
#print axioms PNP.DirectWire.WireProfileAvailability.current_available
#print axioms PNP.DirectWire.WireProfileAvailability.findSource_congr
#print axioms PNP.DirectWire.WireProfileAvailability.findSource_sound
#print axioms PNP.DirectWire.WireProfileAvailability.full_match_iff
#print axioms PNP.DirectWire.WireProfileAvailability.full_minimum
#print axioms PNP.DirectWire.WireProfileAvailability.quotient_match_iff
#print axioms PNP.DirectWire.WireProfileAvailability.quotient_minimum
#print axioms PNP.DirectWire.WireProfileAvailability.sourceMatches_congr
#print axioms PNP.DirectWire.WireProfileAvailability.sourceMatches_iff
#print axioms PNP.DirectWire.WireProfileAvailability.system_congr
#print axioms PNP.DirectWire.WireProfileAvailability.system_fullEquivalent
#print axioms PNP.DirectWire.WireProfileFieldClosed.ambient_fieldValue
#print axioms PNP.DirectWire.WireProfileFieldClosed.available
#print axioms PNP.DirectWire.WireProfileFieldClosed.boundary_isInput
#print axioms PNP.DirectWire.WireProfileFieldClosed.gate_value
#print axioms PNP.DirectWire.WireProfileFieldClosed.source_selected
#print axioms PNP.DirectWire.extractTerminalSupport_gate_evaluation
#print axioms PNP.DirectWire.extractTerminalSupport_gate_induced
#print axioms PNP.DirectWire.terminalPhysicalComplementRecords_gateCount_partition
#print axioms PNP.DirectWire.terminalPhysicalComplementRecords_selected
