import PNP

#print axioms PNP.Concrete.CookLevin.exists_add_of_le
#print axioms PNP.Concrete.CookLevin.run_pad_of_halted
#print axioms PNP.Concrete.CookLevin.run_pad_of_stuck
#print axioms PNP.Concrete.CookLevin.boundedDecide_pad_of_halted
#print axioms PNP.Concrete.CookLevin.boundedDecide_pad_of_stuck
#print axioms PNP.Concrete.CookLevin.ruleStateCeiling
#print axioms PNP.Concrete.CookLevin.rulesStateCeiling
#print axioms PNP.Concrete.CookLevin.machineStateBound
#print axioms PNP.Concrete.CookLevin.le_max_left_constructive
#print axioms PNP.Concrete.CookLevin.le_max_right_constructive
#print axioms PNP.Concrete.CookLevin.rule_source_le_ruleStateCeiling
#print axioms PNP.Concrete.CookLevin.rule_target_le_ruleStateCeiling
#print axioms PNP.Concrete.CookLevin.ruleStateCeiling_le_rulesStateCeiling
#print axioms PNP.Concrete.CookLevin.machine_startState_lt_bound
#print axioms PNP.Concrete.CookLevin.machine_acceptState_lt_bound
#print axioms PNP.Concrete.CookLevin.machine_rejectState_lt_bound
#print axioms PNP.Concrete.CookLevin.rule_source_lt_machineStateBound
#print axioms PNP.Concrete.CookLevin.rule_target_lt_machineStateBound
#print axioms PNP.Concrete.CookLevin.InputMode
#print axioms PNP.Concrete.CookLevin.Dimensions
#print axioms PNP.Concrete.CookLevin.Dimensions.encodedInputLength
#print axioms PNP.Concrete.CookLevin.Dimensions.timeCount
#print axioms PNP.Concrete.CookLevin.Dimensions.tapeWidth
#print axioms PNP.Concrete.CookLevin.Dimensions.timeCount_positive
#print axioms PNP.Concrete.CookLevin.Dimensions.tapeWidth_positive
#print axioms PNP.Concrete.CookLevin.encodedInputPolynomial
#print axioms PNP.Concrete.CookLevin.tapeWidthPolynomial
#print axioms PNP.Concrete.CookLevin.eval_encodedInputPolynomial
#print axioms PNP.Concrete.CookLevin.eval_tapeWidthPolynomial
#print axioms PNP.Concrete.CookLevin.dimensionsAt
#print axioms PNP.Concrete.CookLevin.VariableBlock
#print axioms PNP.Concrete.CookLevin.VariableBlock.endOffset
#print axioms PNP.Concrete.CookLevin.VariableBlock.index
#print axioms PNP.Concrete.CookLevin.VariableBlock.offset_le_index
#print axioms PNP.Concrete.CookLevin.VariableBlock.index_lt_endOffset
#print axioms PNP.Concrete.CookLevin.VariableBlock.index_ne_of_end_le_offset
#print axioms PNP.Concrete.CookLevin.VariableLayout
#print axioms PNP.Concrete.CookLevin.VariableLayout.symbolWidth
#print axioms PNP.Concrete.CookLevin.VariableLayout.headWidth
#print axioms PNP.Concrete.CookLevin.VariableLayout.stateWidth
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateBitWidth
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateLengthWidth
#print axioms PNP.Concrete.CookLevin.VariableLayout.symbolBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.headBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.stateBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateBitBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateLengthBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.variableCount
#print axioms PNP.Concrete.CookLevin.VariableLayout.flattenTwo
#print axioms PNP.Concrete.CookLevin.VariableLayout.flattenTwo_lt
#print axioms PNP.Concrete.CookLevin.VariableLayout.tapeSymbolCode
#print axioms PNP.Concrete.CookLevin.VariableLayout.tapeSymbolCode_lt_three
#print axioms PNP.Concrete.CookLevin.VariableLayout.symbolLocalIndex
#print axioms PNP.Concrete.CookLevin.VariableLayout.headLocalIndex
#print axioms PNP.Concrete.CookLevin.VariableLayout.stateLocalIndex
#print axioms PNP.Concrete.CookLevin.VariableLayout.symbolVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.headVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.stateVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateBitVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateLengthVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.symbolBlock_before_headBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.headBlock_before_stateBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.stateBlock_before_certificateBitBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateBitBlock_before_certificateLengthBlock
#print axioms PNP.Concrete.CookLevin.VariableLayout.symbolVariable_ne_headVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.headVariable_ne_stateVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.stateVariable_ne_certificateBitVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateBitVariable_ne_certificateLengthVariable
#print axioms PNP.Concrete.CookLevin.VariableLayout.symbolVariable_lt_variableCount
#print axioms PNP.Concrete.CookLevin.VariableLayout.headVariable_lt_variableCount
#print axioms PNP.Concrete.CookLevin.VariableLayout.stateVariable_lt_variableCount
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateBitVariable_lt_variableCount
#print axioms PNP.Concrete.CookLevin.VariableLayout.certificateLengthVariable_lt_variableCount
#print axioms PNP.Concrete.CookLevin.positiveLiteral
#print axioms PNP.Concrete.CookLevin.negativeLiteral
#print axioms PNP.Concrete.CookLevin.atLeastOneClause
#print axioms PNP.Concrete.CookLevin.excludePairClause
#print axioms PNP.Concrete.CookLevin.excludeWithClauses
#print axioms PNP.Concrete.CookLevin.atMostOneClauses
#print axioms PNP.Concrete.CookLevin.exactlyOneClauses
#print axioms PNP.Concrete.CookLevin.literalSatisfied_positiveLiteral_iff
#print axioms PNP.Concrete.CookLevin.literalSatisfied_negativeLiteral_iff
#print axioms PNP.Concrete.CookLevin.atLeastOneClause_satisfied_iff
#print axioms PNP.Concrete.CookLevin.excludePairClause_satisfied_of_left_false
#print axioms PNP.Concrete.CookLevin.excludePairClause_satisfied_of_right_false
#print axioms PNP.Concrete.CookLevin.excludePairClause_not_satisfied_of_both_true
