import PNP

#print axioms PNP.Concrete.TapeSymbol
#print axioms PNP.Concrete.TapeSymbol.ofBool
#print axioms PNP.Concrete.HeadMove
#print axioms PNP.Concrete.Rule
#print axioms PNP.Concrete.Tape
#print axioms PNP.Concrete.Tape.blank
#print axioms PNP.Concrete.Tape.ofInput
#print axioms PNP.Concrete.Tape.write
#print axioms PNP.Concrete.Tape.moveLeft
#print axioms PNP.Concrete.Tape.moveRight
#print axioms PNP.Concrete.Tape.move
#print axioms PNP.Concrete.Configuration
#print axioms PNP.Concrete.Machine
#print axioms PNP.Concrete.findRule
#print axioms PNP.Concrete.Machine.isHalted
#print axioms PNP.Concrete.applyRule
#print axioms PNP.Concrete.step?
#print axioms PNP.Concrete.run
#print axioms PNP.Concrete.run_zero
#print axioms PNP.Concrete.run_succ
#print axioms PNP.Concrete.startConfig
#print axioms PNP.Concrete.Verdict
#print axioms PNP.Concrete.boundedDecide
#print axioms PNP.Concrete.PolynomialTimeMachine
#print axioms PNP.Concrete.PolynomialTimeMachine.verdict
#print axioms PNP.Concrete.PolynomialTimeMachine.verdict_ne_timeout
#print axioms PNP.Concrete.PolynomialTimeMachine.verdict_accepts_iff
#print axioms PNP.Concrete.immediateAcceptMachine
#print axioms PNP.Concrete.immediateRejectMachine
#print axioms PNP.Concrete.stuckMachine
#print axioms PNP.Concrete.acceptLeadingZeroMachine
#print axioms PNP.Concrete.acceptAllPolynomialTime
#print axioms PNP.Concrete.rejectAllPolynomialTime
#print axioms PNP.Concrete.immediateAcceptMachine_accepts
#print axioms PNP.Concrete.immediateRejectMachine_rejects
#print axioms PNP.Concrete.stuckMachine_times_out
#print axioms PNP.Concrete.acceptLeadingZeroMachine_zero_fuel_times_out
#print axioms PNP.Concrete.acceptLeadingZeroMachine_one_fuel_accepts
