import PNP.Concrete.LockedNANDSourceParserSpec
import PNP.Concrete.LockedNANDSourceParserSemantics
import PNP.Concrete.LockedNANDSourceParserMachine
import PNP.Concrete.LockedNANDSourceParserFailureShapes
import PNP.Concrete.LockedNANDSourceParserValidTrace
import PNP.Concrete.LockedNANDSourceParserTotalTrace
import PNP.Concrete.LockedNANDSourceParserCorrectness
import PNP.Concrete.LockedNANDSourceParserCompiled

/-! Strict-v0 source specification. -/

#print axioms PNP.Concrete.LockedNAND.SourceParser.ValidEncodedCircuit
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes
#print axioms PNP.Concrete.LockedNAND.SourceParser.valid_of_decoded
#print axioms PNP.Concrete.LockedNAND.SourceParser.not_valid_of_decode_none
#print axioms PNP.Concrete.LockedNAND.SourceParser.decode_none_of_not_valid
#print axioms PNP.Concrete.LockedNAND.SourceParser.valid_iff_decodeElaboratedCircuit_ne_none
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_of_decoded
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_of_decode_none
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_of_valid
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_of_not_valid
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_eq_source_or_empty
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_length_le
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_size_le
#print axioms PNP.Concrete.LockedNAND.SourceParser.empty_not_validEncodedCircuit
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_empty
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytes_idempotent

/-! Constructive codec semantics. -/

#print axioms PNP.Concrete.LockedNAND.RawSource.elaborate_exists_iff_wellFormed
#print axioms PNP.Concrete.LockedNAND.RawGate.elaborate_exists_iff_wellFormed
#print axioms PNP.Concrete.LockedNAND.elaborateGatesAux_exists_iff_rawGatesWellFormed
#print axioms PNP.Concrete.LockedNAND.elaborateGatesAux_gateCount_eq
#print axioms PNP.Concrete.LockedNAND.elaborateGates_exists_iff_rawGatesWellFormed
#print axioms PNP.Concrete.LockedNAND.elaborateGates_gateCount_eq_length
#print axioms PNP.Concrete.LockedNAND.rawGatesWellFormed_append
#print axioms PNP.Concrete.LockedNAND.RawCircuit.normalize_wellFormed
#print axioms PNP.Concrete.LockedNAND.RawCircuit.normalize_output_eq_gate
#print axioms PNP.Concrete.LockedNAND.RawCircuit.elaborate_exists_iff_wellFormed
#print axioms PNP.Concrete.LockedNAND.encodeCircuit_eq_of_decodeCircuit_eq_some
#print axioms PNP.Concrete.LockedNAND.decodeElaboratedCircuit_exists_iff
#print axioms PNP.Concrete.LockedNAND.decodeElaboratedCircuit_eq_some_exists_encoded_wellFormed

/-! Literal work machine and complete finite rule table. -/

#print axioms PNP.Concrete.LockedNAND.SourceParser.cellBlank
#print axioms PNP.Concrete.LockedNAND.SourceParser.leftGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.cursorMark
#print axioms PNP.Concrete.LockedNAND.SourceParser.cell00
#print axioms PNP.Concrete.LockedNAND.SourceParser.cell01
#print axioms PNP.Concrete.LockedNAND.SourceParser.countMark
#print axioms PNP.Concrete.LockedNAND.SourceParser.cell10
#print axioms PNP.Concrete.LockedNAND.SourceParser.cell11
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateMark
#print axioms PNP.Concrete.LockedNAND.SourceParser.workAlphabet
#print axioms PNP.Concrete.LockedNAND.SourceParser.SourceContinuation
#print axioms PNP.Concrete.LockedNAND.SourceParser.SourceContinuation.code
#print axioms PNP.Concrete.LockedNAND.SourceParser.SourceContinuation.all
#print axioms PNP.Concrete.LockedNAND.SourceParser.ReferenceBound
#print axioms PNP.Concrete.LockedNAND.SourceParser.ReferenceBound.code
#print axioms PNP.Concrete.LockedNAND.SourceParser.ReferenceBound.all
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.accept
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.reject
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.boot
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.installGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.versionFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.versionSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.inputCountFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.inputCountSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateCountFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateCountSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateStart
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateEndFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateEndSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programEndSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programCountSeekGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programSkipVersionFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programSkipVersionSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programSkipInputFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programSkipInputSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programCountFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programCountSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programSeekCursor
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.programSkipSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.outputsEndFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.outputsEndSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.instanceEndFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.instanceEndSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finalEOF
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.successRestoreLeft
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.cleanupSeekGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.cleanupRight
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementSeekGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementVersionFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementVersionSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementInputFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementInputSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementCountFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementCountSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.gateDecrementSeekCursor
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.sourceStart
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.sourceAfter00
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.sourceAfter01
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.indexFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.indexSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.consumeSeekGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.consumeInputVersionFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.consumeInputVersionSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.consumeInputFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.consumeInputSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.consumeGateAnchor
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.consumeSeekCursor
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishSeekGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputVersionFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputVersionSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputCheckFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputCheckSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputReturnGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputRestoreVersionFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputRestoreVersionSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputRestoreFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputRestoreSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateCheckAnchor
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateReturnGuard
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateVersionFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateVersionSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateInputFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateInputSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateCountFirst
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateCountSecond
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishGateRestore
#print axioms PNP.Concrete.LockedNAND.SourceParser.State.finishInputSeekCursor
#print axioms PNP.Concrete.LockedNAND.SourceParser.Action
#print axioms PNP.Concrete.LockedNAND.SourceParser.StateProgram
#print axioms PNP.Concrete.LockedNAND.SourceParser.keepAction
#print axioms PNP.Concrete.LockedNAND.SourceParser.writeAction
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupAction
#print axioms PNP.Concrete.LockedNAND.SourceParser.expectOne
#print axioms PNP.Concrete.LockedNAND.SourceParser.expectTwo
#print axioms PNP.Concrete.LockedNAND.SourceParser.expectThree
#print axioms PNP.Concrete.LockedNAND.SourceParser.stateRules
#print axioms PNP.Concrete.LockedNAND.SourceParser.statePrograms
#print axioms PNP.Concrete.LockedNAND.SourceParser.rules
#print axioms PNP.Concrete.LockedNAND.SourceParser.machine
#print axioms PNP.Concrete.LockedNAND.SourceParser.compiledMachine
#print axioms PNP.Concrete.LockedNAND.SourceParser.QueryDistinct
#print axioms PNP.Concrete.LockedNAND.SourceParser.rules_pairwise_query_distinct
#print axioms PNP.Concrete.LockedNAND.SourceParser.statePrograms_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.ruleCount
#print axioms PNP.Concrete.LockedNAND.SourceParser.rules_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.machine_startState_ne_acceptState
#print axioms PNP.Concrete.LockedNAND.SourceParser.machine_startState_ne_rejectState
#print axioms PNP.Concrete.LockedNAND.SourceParser.machine_acceptState_ne_rejectState

/-! Constructive decoder-failure normal forms. -/

#print axioms PNP.Concrete.LockedNAND.SourceParser.TokenDecodeFailure
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeTokens_encodeTokens_append
#print axioms PNP.Concrete.LockedNAND.SourceParser.TokenDecodeFailure.decodeTokens_eq_none
#print axioms PNP.Concrete.LockedNAND.SourceParser.TokenDecodeFailure.prepend
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeTokens_eq_none_iff_failure
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedRawBits
#print axioms PNP.Concrete.LockedNAND.SourceParser.boolPairWorkCell
#print axioms PNP.Concrete.LockedNAND.SourceParser.danglingWorkCell
#print axioms PNP.Concrete.LockedNAND.SourceParser.SourcePackedCell
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedRawBits_encodeTokens_append
#print axioms PNP.Concrete.LockedNAND.SourceParser.TokenDecodeFailure.packedShape
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail.workTail_eq_packedRawBits
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedRawBits_first_ne_blank
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedRawBits_allSourcePacked
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail.nonempty
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail.first_ne_blank
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail.nonblank
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail.noBlankZero
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail.allSourcePacked
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedRawBits_length_le
#print axioms PNP.Concrete.LockedNAND.SourceParser.MalformedWorkTail.length_le_rawTail
#print axioms PNP.Concrete.LockedNAND.SourceParser.NatTokenFailure
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeNatTokens_eq_some_iff
#print axioms PNP.Concrete.LockedNAND.SourceParser.NatTokenFailure.decodeNatTokens_eq_none
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeNatTokens_eq_none_iff_failure
#print axioms PNP.Concrete.LockedNAND.SourceParser.SourceTokenFailure
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeSourceTokens_eq_some_iff
#print axioms PNP.Concrete.LockedNAND.SourceParser.SourceTokenFailure.decodeSourceTokens_eq_none
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeSourceTokens_eq_none_iff_failure
#print axioms PNP.Concrete.LockedNAND.SourceParser.NGatesTokenFailure
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeNGatesTokens_eq_some_iff
#print axioms PNP.Concrete.LockedNAND.SourceParser.NGatesTokenFailure.decodeNGatesTokens_eq_none
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeNGatesTokens_eq_none_iff_failure
#print axioms PNP.Concrete.LockedNAND.SourceParser.circuitHeaderTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.circuitGatesPrefixTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.circuitOutputPrefixTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.CircuitTokenFailure
#print axioms PNP.Concrete.LockedNAND.SourceParser.decodeCircuitTokens_eq_none_iff_failure

/-! Canonical valid input layouts and exact transition interfaces. -/

#print axioms PNP.Concrete.LockedNAND.SourceParser.tokenCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedTokenCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.tokenCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedTokenCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.natCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.natCellsTail
#print axioms PNP.Concrete.LockedNAND.SourceParser.natCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.natCells_eq_cons
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateListCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.circuitCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.countCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.borrowedCountCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.borrowedCountCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.countCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.markedGateCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.markedGateListCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.borrowedGateCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.borrowedGateListCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.markedGateCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.borrowedGateCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.markedGateListCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.borrowedGateListCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.gatePrefix
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateParsingPrefix
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedTokenCells_encodeNatTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedTokenCells_encodeSourceTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedTokenCells_encodeGateListTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.packedTokenCells_encodeCircuitTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.pack_encodeTokens
#print axioms PNP.Concrete.LockedNAND.SourceParser.rawInputWorkTape_encodeCircuit
#print axioms PNP.Concrete.LockedNAND.SourceParser.circuitCells_ne_empty
#print axioms PNP.Concrete.LockedNAND.SourceParser.acceptedTape
#print axioms PNP.Concrete.LockedNAND.SourceParser.validFinalConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.validFinalConfiguration_state
#print axioms PNP.Concrete.LockedNAND.SourceParser.validFinalConfiguration_isHalted
#print axioms PNP.Concrete.LockedNAND.SourceParser.acceptedTape_eq_of_nonempty
#print axioms PNP.Concrete.LockedNAND.SourceParser.encodeWorkRight_circuitCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.encodeCircuit_length_eq
#print axioms PNP.Concrete.LockedNAND.SourceParser.acceptedTape_outputBits
#print axioms PNP.Concrete.LockedNAND.SourceParser.tapeAtWord
#print axioms PNP.Concrete.LockedNAND.SourceParser.configAtWord
#print axioms PNP.Concrete.LockedNAND.SourceParser.tapeAtLeftWord
#print axioms PNP.Concrete.LockedNAND.SourceParser.configAtLeftWord
#print axioms PNP.Concrete.LockedNAND.SourceParser.pushCrossed
#print axioms PNP.Concrete.LockedNAND.SourceParser.pushCrossed_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedConfig
#print axioms PNP.Concrete.LockedNAND.SourceParser.ordinaryCell
#print axioms PNP.Concrete.LockedNAND.SourceParser.canonicalHeader_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.canonicalHeader_fixed_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceDoneState
#print axioms PNP.Concrete.LockedNAND.SourceParser.constantSource_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.firstSourceCell
#print axioms PNP.Concrete.LockedNAND.SourceParser.afterFirstSourceState
#print axioms PNP.Concrete.LockedNAND.SourceParser.constantGate_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceSuccessConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceHeader
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceSuccessConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.consumeAfterGuardState
#print axioms PNP.Concrete.LockedNAND.SourceParser.finishAfterGuardState
#print axioms PNP.Concrete.LockedNAND.SourceParser.referenceIndexFirst_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.referenceIndexUnitLaunch_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.referenceIndexFinishLaunch_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.referenceConsumeSeekGuard_scan_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.referenceConsumeGuard_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.referenceFinishSeekGuard_scan_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.referenceFinishGuard_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputConsumeCount_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputConsumeCountExhausted_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceConsumeUnitSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceConsumeUnitTail_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceConsumeUnit_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputFinishCheck_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputFinishCheckExhaustedRun_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputFinishReturnGuard_scan_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputFinishRestoreCount_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceFinishSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceFinishInRange_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceInRangeSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceInRange_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceCleanupConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceExhaustedSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceConsumeExhaustedTail_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceConsumeExhausted_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceFinishExhausted_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceOutOfRangeSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceOutOfRange_cleanupEntry
#print axioms PNP.Concrete.LockedNAND.SourceParser.ordinaryNonGateAnchor
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateConsumeAnchorScan_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceConsumeUnitSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceConsumeUnitTail_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceConsumeUnit_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.ordinaryNonCountMarker
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceFinishSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceFinishInRange_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceExhaustedSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceConsumeExhaustedTail_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceConsumeExhausted_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceFinishExhaustedTail_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceFinishExhausted_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceInRangeSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceInRange_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceOutOfRangeSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceOutOfRange_cleanupEntry
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceContextPrefix
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceFirstWas01
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceRemainderCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceSecondCell
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceAfterSecondCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceRemainderSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceRemainder_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.source_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateSourceLaunchSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateLeftRemainder_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gate_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.gatesSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.gates_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.programEndSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.programEnd_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.markedCircuitCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.markedCircuitCells_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.restorePersistentSymbol
#print axioms PNP.Concrete.LockedNAND.SourceParser.finalRestoreSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.finalRestore_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.circuitAfterHeaderCells
#print axioms PNP.Concrete.LockedNAND.SourceParser.canonicalSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.canonical_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceFootprint
#print axioms PNP.Concrete.LockedNAND.SourceParser.inputReferenceInRangeSteps_bound
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceFootprint
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateReferenceInRangeSteps_bound
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceSpan
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceRemainderSteps_bound
#print axioms PNP.Concrete.LockedNAND.SourceParser.sourceSteps_bound
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateWorkspace
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateWorkspace_step
#print axioms PNP.Concrete.LockedNAND.SourceParser.gateSteps_bound
#print axioms PNP.Concrete.LockedNAND.SourceParser.gatesSteps_bound
#print axioms PNP.Concrete.LockedNAND.SourceParser.validWorkBound
#print axioms PNP.Concrete.LockedNAND.SourceParser.validRawBound
#print axioms PNP.Concrete.LockedNAND.SourceParser.validWorkBound_zero
#print axioms PNP.Concrete.LockedNAND.SourceParser.validRawBound_eq
#print axioms PNP.Concrete.LockedNAND.SourceParser.canonicalSteps_le_validWorkBound
#print axioms PNP.Concrete.LockedNAND.SourceParser.wellFormed_exact

/-! Generic cleanup and accepting-boundary traces. -/

#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupSeekGuard_workStep
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRight_workStep
#print axioms PNP.Concrete.LockedNAND.SourceParser.pushCleanupScan
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupSeekConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupSeekGuard_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.pushCleanupScan_append
#print axioms PNP.Concrete.LockedNAND.SourceParser.pushCleanupScan_length
#print axioms PNP.Concrete.LockedNAND.SourceParser.pushCleanupBlanks
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRightConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRight_erase_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRight_reject_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRight_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRightFiniteConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRightFinite_erase_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRightFinite_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedCleanupSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedCleanupSteps_eq
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRejectConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedCleanup_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedCleanupFinite_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedCleanupExplicitSteps
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedCleanupExplicitSteps_eq
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupExplicitRejectConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.guardedCleanupExplicit_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRejectConfiguration_output_empty
#print axioms PNP.Concrete.LockedNAND.SourceParser.cleanupRejectConfiguration_isHalted
#print axioms PNP.Concrete.LockedNAND.SourceParser.restoredBoundaryConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.restoredBoundary_workStep
#print axioms PNP.Concrete.LockedNAND.SourceParser.restoredBoundary_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.workStep_to_accept_predecessor

/-! Current all-input boundary regressions. -/

#print axioms PNP.Concrete.LockedNAND.SourceParser.emptyRejectConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.oneBitRejectConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.twoCellRejectConfiguration
#print axioms PNP.Concrete.LockedNAND.SourceParser.emptyInput_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.oneBitFalse_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.oneBitTrue_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.twoBitVersionPrefix_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.threeBitFalseSuffix_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.threeBitTrueSuffix_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.emptyRejectConfiguration_output_empty
#print axioms PNP.Concrete.LockedNAND.SourceParser.oneBitRejectConfiguration_output_empty
#print axioms PNP.Concrete.LockedNAND.SourceParser.twoCellRejectConfiguration_output_empty
#print axioms PNP.Concrete.LockedNAND.SourceParser.illFormed_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.malformed_exact
#print axioms PNP.Concrete.LockedNAND.SourceParser.allInput_exact

/-! Compiled runtime and blank-tape transport. -/

#print axioms PNP.Concrete.LockedNAND.SourceParser.validRawTimePolynomial
#print axioms PNP.Concrete.LockedNAND.SourceParser.validRawTimePolynomial_eval
#print axioms PNP.Concrete.LockedNAND.SourceParser.compiledStart_blankEquivalent
#print axioms PNP.Concrete.LockedNAND.SourceParser.compiledMachineOutput_eq_validatedSourceBytes
#print axioms PNP.Concrete.LockedNAND.SourceParser.compiledBoundedDecide_accept_iff
#print axioms PNP.Concrete.LockedNAND.SourceParser.compiledBoundedDecide_ne_timeout
#print axioms PNP.Concrete.LockedNAND.SourceParser.polynomialTimeMachine
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytesPolynomialTimeFunction
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytesPolynomialTimeFunction_output
#print axioms PNP.Concrete.LockedNAND.SourceParser.validatedSourceBytesRawRefinement
