import PNP

#print axioms PNP.Concrete.TapeSymbol.toBool
#print axioms PNP.Concrete.TapeSymbol.toBool_ofBool
#print axioms PNP.Concrete.Tape.outputBits
#print axioms PNP.Concrete.Tape.map_toBool_ofBool
#print axioms PNP.Concrete.Tape.outputBits_ofInput
#print axioms PNP.Concrete.machineOutput
#print axioms PNP.Concrete.machineOutput_immediateAccept_zero
#print axioms PNP.Concrete.NatPolynomial.substitute
#print axioms PNP.Concrete.NatPolynomial.eval_substitute
#print axioms PNP.Concrete.FunctionProgram
#print axioms PNP.Concrete.FunctionProgram.eval
#print axioms PNP.Concrete.FunctionProgram.chargedSteps
#print axioms PNP.Concrete.FunctionProgram.Halts
#print axioms PNP.Concrete.PolynomialTimeFunction
#print axioms PNP.Concrete.PolynomialTimeFunction.output
#print axioms PNP.Concrete.PolynomialTimeFunction.identity
#print axioms PNP.Concrete.PolynomialTimeFunction.identity_output
#print axioms PNP.Concrete.PolynomialTimeFunction.compose
#print axioms PNP.Concrete.PolynomialTimeFunction.compose_output
#print axioms PNP.Concrete.DecisionProgram
#print axioms PNP.Concrete.DecisionProgram.verdict
#print axioms PNP.Concrete.DecisionProgram.chargedSteps
#print axioms PNP.Concrete.DecisionProgram.Halts
#print axioms PNP.Concrete.Language
#print axioms PNP.Concrete.PolynomialTimeDecider
#print axioms PNP.Concrete.PolynomialTimeDecider.ofMachine
#print axioms PNP.Concrete.PolynomialTimeDecider.relabel
#print axioms PNP.Concrete.PolynomialTimeDecider.precompose
#print axioms PNP.Concrete.VerifierInputMode
#print axioms PNP.Concrete.VerifierInputMode.encode
#print axioms PNP.Concrete.VerifierInputMode.encode_paired
#print axioms PNP.Concrete.VerifierProgram
#print axioms PNP.Concrete.VerifierProgram.verdict
#print axioms PNP.Concrete.VerifierProgram.chargedSteps
#print axioms PNP.Concrete.VerifierProgram.Halts
#print axioms PNP.Concrete.PolynomialTimeVerifier
#print axioms PNP.Concrete.InP
#print axioms PNP.Concrete.InNP
#print axioms PNP.Concrete.PEqualsNP
#print axioms PNP.Concrete.verifierFromDecider
#print axioms PNP.Concrete.p_subset_np
#print axioms PNP.Concrete.PolynomialReduction
#print axioms PNP.Concrete.ReducesTo
#print axioms PNP.Concrete.PolynomialReduction.identity
#print axioms PNP.Concrete.PolynomialReduction.compose
#print axioms PNP.Concrete.reduction_refl
#print axioms PNP.Concrete.reduction_comp
#print axioms PNP.Concrete.reduction_transports_p
#print axioms PNP.Concrete.NPComplete
#print axioms PNP.Concrete.np_complete_in_p_implies_p_eq_np
