import PNP

#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.framerState
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.tallyState
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.framerState_injective
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.tallyState_injective
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.framerState_ne_tallyState
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.renamedFramer
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.renamedTally
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.launchRules
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.rules
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.machine
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.machine_acceptState_ne_rejectState
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.workSteps
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.rawTimeBound
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.finalTape
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.finalConfiguration
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.finalTape_represents
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.finalTape_tally_length
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.machine_isHalted_framer_false
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.machine_isHalted_tally_false_of_local
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.findWorkRule_framer_of_some
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.findWorkRule_tally_of_some
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.framer_workStep?_of_some
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.tally_workStep?_of_some
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.framer_workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.launch_workStep
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.tally_workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.finalConfiguration_isHalted
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.rawTimeBound_eval
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.rawTimeBound_le
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.run_compile_exact
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.run_compile_rawTimeBound
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.run_compile_rawTimeBound_blankEquivalent
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.boundedDecide_compile_accept
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.boundedDecide_compile_ne_timeout
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.malformedTallyConfiguration
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.malformedTallyScanSymbol_isHalted_false
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.malformedTallyScanSymbol_workStep_none
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.malformedTallyScanSymbol_timeout
#print axioms PNP.Concrete.CookLevin.BuilderInputPrefix.work_one_step_short_timeout
