import PNP.Concrete.LockedNANDReduction

#print axioms PNP.Concrete.LockedNAND.RawCircuit.eval
#print axioms PNP.Concrete.LockedNAND.RawCircuit.normalize
#print axioms PNP.Concrete.LockedNAND.RawCircuit.elaborate
#print axioms PNP.Concrete.LockedNAND.RawCandidate.elaborate
#print axioms PNP.Concrete.LockedNAND.RawLockedInstance.elaborate
#print axioms PNP.Concrete.LockedNAND.encodeCircuit
#print axioms PNP.Concrete.LockedNAND.decodeCircuit
#print axioms PNP.Concrete.LockedNAND.encodeLockedInstance
#print axioms PNP.Concrete.LockedNAND.decodeLockedInstance
#print axioms PNP.Concrete.LockedNAND.EncodedNANDSAT
#print axioms PNP.Concrete.LockedNAND.EncodedLockedNANDThreshold
#print axioms PNP.Concrete.LockedNAND.buildLockedNANDInstance

#print axioms PNP.Concrete.LockedNAND.evalRawGatesAux_append
#print axioms PNP.Concrete.LockedNAND.evalRawGatesAux_length
#print axioms PNP.Concrete.LockedNAND.RawCircuit.normalize_gate
#print axioms PNP.Concrete.LockedNAND.RawCircuit.normalize_idempotent
#print axioms PNP.Concrete.LockedNAND.RawCircuit.normalize_eval
#print axioms PNP.Concrete.LockedNAND.RawCircuit.elaborate_normalize
#print axioms PNP.Concrete.LockedNAND.RawCircuit.normalize_satisfiable
#print axioms PNP.Concrete.LockedNAND.fallbackCircuit_not_satisfiable
#print axioms PNP.Concrete.LockedNAND.RawSource.elaborate_ofSource
#print axioms PNP.Concrete.LockedNAND.RawGate.elaborate_ofGate
#print axioms PNP.Concrete.LockedNAND.elaborateGatesAux_append
#print axioms PNP.Concrete.LockedNAND.elaborateGates_rawProgramGates
#print axioms PNP.Concrete.LockedNAND.elaborateSources_rawOutputSources
#print axioms PNP.Concrete.LockedNAND.RawCircuit.elaborate_ofCircuit
#print axioms PNP.Concrete.LockedNAND.RawCandidate.elaborate_ofCandidate
#print axioms PNP.Concrete.LockedNAND.RawLockedInstance.elaborate_ofCandidate
#print axioms PNP.Concrete.LockedNAND.Token.ofBits_bits
#print axioms PNP.Concrete.LockedNAND.decodeTokens_encodeTokens
#print axioms PNP.Concrete.LockedNAND.decodeNatTokens_encodeNatTokens_append
#print axioms PNP.Concrete.LockedNAND.decodeSourceTokens_encodeSourceTokens_append
#print axioms PNP.Concrete.LockedNAND.decodeNGatesTokens_encodeGateListTokens_append
#print axioms PNP.Concrete.LockedNAND.decodeNSourcesTokens_encodeSourceListTokens_append
#print axioms PNP.Concrete.LockedNAND.decodeCircuitTokens_encodeCircuitTokens
#print axioms PNP.Concrete.LockedNAND.decodeCircuit_encodeCircuit
#print axioms PNP.Concrete.LockedNAND.decodeValidCircuit_encodeCircuit
#print axioms PNP.Concrete.LockedNAND.decodeCandidateTokens_encodeCandidateTokens
#print axioms PNP.Concrete.LockedNAND.decodeCandidate_encodeCandidate
#print axioms PNP.Concrete.LockedNAND.decodeLockedInstanceTokens_encodeLockedInstanceTokens
#print axioms PNP.Concrete.LockedNAND.decodeLockedInstance_encodeLockedInstance
#print axioms PNP.Concrete.LockedNAND.encodeTokens_length
#print axioms PNP.Concrete.LockedNAND.decodeElaboratedCircuit_encodeCircuit_ofCircuit
#print axioms PNP.Concrete.LockedNAND.buildLockedNANDInstance_of_decoded
#print axioms PNP.Concrete.LockedNAND.buildLockedNANDInstance_of_malformed
#print axioms PNP.Concrete.LockedNAND.empty_not_encodedLockedNANDThreshold
#print axioms PNP.Concrete.LockedNAND.encoded_fullCandidate_threshold_iff_satisfiable
#print axioms PNP.Concrete.LockedNAND.buildLockedNANDInstance_correct
