import PNP

#print axioms PNP.Concrete.CookLevin.inputModeOfVerifier
#print axioms PNP.Concrete.CookLevin.verifierPair_add_one_same_normalize
#print axioms PNP.Concrete.CookLevin.verifierPair_merge_unit_offsets
#print axioms PNP.Concrete.CookLevin.verifierPair_size_arithmetic
#print axioms PNP.Concrete.CookLevin.verifierPair_size
#print axioms PNP.Concrete.CookLevin.verifierEncodedInput_size_le
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.refinement
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.rawMachine
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.rawTimeBound
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.tableauInputMode
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.certificateLimit
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.rawInput
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.actualFuel
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.encodedInputLimit
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.uniformFuel
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.dimensions
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.layout
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.dimensions_inputLength
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.dimensions_certificateBound
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.dimensions_timeBound
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.layout_mode
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.rawInput_size_le
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.actualFuel_le_uniformFuel
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.source_halts
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.actualFuel_ne_timeout
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.actualFuel_final_isHalted
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.uniformFuel_verdict_eq
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.initial
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.canonicalTableau
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.Valid
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.tableauVerdict
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.Accepting
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.AcceptingWitness
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.canonicalTableau_valid
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.valid_iff_eq_canonical
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.tableauEndpoint_of_valid
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.tableauVerdict_of_valid
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.tableauVerdict_eq_program_of_valid
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.exists_accepting_iff_program_accept
#print axioms PNP.Concrete.CookLevin.VerifierTableauProblem.language_iff_exists_acceptingTableau
