import PNP

#print axioms PNP.Concrete.CookLevin.BuilderInputLength.markedZeroSymbol
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.markedOneSymbol
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.tallySymbol
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.scanState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.seekRightState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.seekTallyEndState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.returnTallyState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.seekMarkedState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.rewindState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.emptyFinishState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.acceptState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.rejectState
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.keepRule
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.writeRule
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.rules
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.machine
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.rules_length
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.rules_pairwise_query_distinct
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.markedZeroSymbol_ne_markedOneSymbol
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.tallySymbol_ne_markedZeroSymbol
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.tallySymbol_ne_markedOneSymbol
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.inputTape
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.finalTape
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.finalConfiguration
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.finalTape_represents
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.finalTape_tally_length
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.workSteps
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.rawTimeBound
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.tallySizeBound
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.tallySizeBound_exact
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.malformedScanSymbol_timeout
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.workRunExact
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.finalConfiguration_isHalted
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.rawTimeBound_exact
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.run_compile
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.workBoundedDecide_accept
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.work_one_step_short_timeout
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.inputTape_eq_totalInputFramerFinalTape
#print axioms PNP.Concrete.CookLevin.BuilderInputLength.workRunExact_after_totalInputFramer
