import PNP

#print axioms PNP.Concrete.BitString
#print axioms PNP.Concrete.BitString.size
#print axioms PNP.Concrete.BitString.frame
#print axioms PNP.Concrete.BitString.decodeLength
#print axioms PNP.Concrete.BitString.splitExact
#print axioms PNP.Concrete.BitString.decodeFrame
#print axioms PNP.Concrete.BitString.pair
#print axioms PNP.Concrete.BitString.decodePair
#print axioms PNP.Concrete.BitString.append_assoc_constructive
#print axioms PNP.Concrete.BitString.append_nil_constructive
#print axioms PNP.Concrete.BitString.length_append_constructive
#print axioms PNP.Concrete.BitString.length_replicate_constructive
#print axioms PNP.Concrete.BitString.decodeLength_frameHeader
#print axioms PNP.Concrete.BitString.decodeLength_noDelimiter
#print axioms PNP.Concrete.BitString.splitExact_append
#print axioms PNP.Concrete.BitString.decodeFrame_frame_append
#print axioms PNP.Concrete.BitString.decodeFrame_frame
#print axioms PNP.Concrete.BitString.frame_injective
#print axioms PNP.Concrete.BitString.frame_prefix_free
#print axioms PNP.Concrete.BitString.decodePair_pair
#print axioms PNP.Concrete.BitString.pair_injective
#print axioms PNP.Concrete.BitString.decodeFrame_empty
#print axioms PNP.Concrete.BitString.decodeFrame_noDelimiter
#print axioms PNP.Concrete.BitString.decodeFrame_shortPayload
#print axioms PNP.Concrete.BitString.decodePair_trailing
#print axioms PNP.Concrete.BitString.size_frame
#print axioms PNP.Concrete.BitString.size_pair
#print axioms PNP.Concrete.NatPolynomial
#print axioms PNP.Concrete.NatPolynomial.eval
#print axioms PNP.Concrete.NatPolynomial.linear
#print axioms PNP.Concrete.NatPolynomial.quadratic
#print axioms PNP.Concrete.NatPolynomial.eval_constant
#print axioms PNP.Concrete.NatPolynomial.eval_variable
#print axioms PNP.Concrete.NatPolynomial.eval_add
#print axioms PNP.Concrete.NatPolynomial.eval_mul
#print axioms PNP.Concrete.NatPolynomial.eval_mono
#print axioms PNP.Concrete.NatPolynomial.eval_le_at_bound
#print axioms PNP.Concrete.NatPolynomial.eval_linear
#print axioms PNP.Concrete.NatPolynomial.eval_quadratic
#print axioms PNP.Concrete.NatPolynomial.eval_linear_example
#print axioms PNP.Concrete.NatPolynomial.eval_quadratic_example
