import PNP.Concrete.CNFToNANDPolynomialReduction

/-! Reused polynomial, language, semantic compiler, and strict
locked-NAND reduction interfaces. -/

#print axioms PNP.Concrete.PolynomialReduction
#print axioms PNP.Concrete.PolynomialReduction.compose
#print axioms PNP.Concrete.ReducesTo
#print axioms PNP.Concrete.PolynomialTimeMachine
#print axioms PNP.Concrete.PolynomialTimeFunction
#print axioms PNP.Concrete.FunctionProgram.RawRefinement
#print axioms PNP.Concrete.FunctionProgram.RawRefinement.ofMachine
#print axioms PNP.Concrete.FunctionProgram.RawRefinement.compose
#print axioms PNP.Concrete.CNFSAT
#print axioms PNP.Concrete.LockedNAND.EncodedNANDSAT
#print axioms PNP.Concrete.LockedNAND.EncodedLockedNANDThreshold
#print axioms PNP.Concrete.CNFToNAND.cnfToNANDOutputSizePolynomial
#print axioms PNP.Concrete.CNFToNAND.compileEncodedCNFToNAND
#print axioms PNP.Concrete.CNFToNAND.compileEncodedCNFToNAND_size_le
#print axioms PNP.Concrete.CNFToNAND.compileEncodedCNFToNAND_correct
#print axioms PNP.Concrete.CNFToNAND.buildLockedNANDFromCNF
#print axioms PNP.Concrete.LockedNAND.strictLockedNANDPolynomialReduction
#print axioms PNP.Concrete.LockedNAND.strictLockedNANDPolynomialReduction_output
#print axioms PNP.Concrete.LockedNAND.strictLockedNANDPolynomialReduction_correct
#print axioms PNP.Concrete.LockedNAND.strictLockedNANDPolynomialReduction_rawRefinement

/-! Complete transcript for every explicit public declaration in the
all-input parser/carrier/controller compiler and both reductions. -/

/-! CNFSourceParserSpec. -/
#print axioms PNP.Concrete.CNFSourceParser.ValidEncodedCNF
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes
#print axioms PNP.Concrete.CNFSourceParser.valid_of_decoded
#print axioms PNP.Concrete.CNFSourceParser.not_valid_of_decode_none
#print axioms PNP.Concrete.CNFSourceParser.decode_none_of_not_valid
#print axioms PNP.Concrete.CNFSourceParser.valid_iff_decodeEncodedCNF_ne_none
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_of_decoded
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_of_decode_none
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_of_valid
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_of_not_valid
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_eq_source_or_empty
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_length_le
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_size_le
#print axioms PNP.Concrete.CNFSourceParser.empty_not_validEncodedCNF
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_empty
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytes_idempotent

/-! CNFSourceParserMachine. -/
#print axioms PNP.Concrete.CNFSourceParser.cellBlank
#print axioms PNP.Concrete.CNFSourceParser.leftGuard
#print axioms PNP.Concrete.CNFSourceParser.formulaPad
#print axioms PNP.Concrete.CNFSourceParser.tokenF
#print axioms PNP.Concrete.CNFSourceParser.tokenSep
#print axioms PNP.Concrete.CNFSourceParser.tokenFinish
#print axioms PNP.Concrete.CNFSourceParser.tokenT
#print axioms PNP.Concrete.CNFSourceParser.workAlphabet
#print axioms PNP.Concrete.CNFSourceParser.State.accept
#print axioms PNP.Concrete.CNFSourceParser.State.reject
#print axioms PNP.Concrete.CNFSourceParser.State.boot
#print axioms PNP.Concrete.CNFSourceParser.State.installGuard
#print axioms PNP.Concrete.CNFSourceParser.State.header
#print axioms PNP.Concrete.CNFSourceParser.State.clauses
#print axioms PNP.Concrete.CNFSourceParser.State.clause
#print axioms PNP.Concrete.CNFSourceParser.State.literal
#print axioms PNP.Concrete.CNFSourceParser.State.expectPad
#print axioms PNP.Concrete.CNFSourceParser.State.finalEOF
#print axioms PNP.Concrete.CNFSourceParser.State.successRestoreLeft
#print axioms PNP.Concrete.CNFSourceParser.State.cleanupSeekGuard
#print axioms PNP.Concrete.CNFSourceParser.State.cleanupRight
#print axioms PNP.Concrete.CNFSourceParser.Action
#print axioms PNP.Concrete.CNFSourceParser.StateProgram
#print axioms PNP.Concrete.CNFSourceParser.keepAction
#print axioms PNP.Concrete.CNFSourceParser.writeAction
#print axioms PNP.Concrete.CNFSourceParser.cleanupAction
#print axioms PNP.Concrete.CNFSourceParser.expectOne
#print axioms PNP.Concrete.CNFSourceParser.stateRules
#print axioms PNP.Concrete.CNFSourceParser.statePrograms
#print axioms PNP.Concrete.CNFSourceParser.rules
#print axioms PNP.Concrete.CNFSourceParser.machine
#print axioms PNP.Concrete.CNFSourceParser.compiledMachine
#print axioms PNP.Concrete.CNFSourceParser.QueryDistinct
#print axioms PNP.Concrete.CNFSourceParser.rules_pairwise_query_distinct
#print axioms PNP.Concrete.CNFSourceParser.statePrograms_length
#print axioms PNP.Concrete.CNFSourceParser.ruleCount
#print axioms PNP.Concrete.CNFSourceParser.rules_length
#print axioms PNP.Concrete.CNFSourceParser.machine_startState_ne_acceptState
#print axioms PNP.Concrete.CNFSourceParser.machine_startState_ne_rejectState
#print axioms PNP.Concrete.CNFSourceParser.machine_acceptState_ne_rejectState
#print axioms PNP.Concrete.CNFSourceParser.no_rule_at_accept
#print axioms PNP.Concrete.CNFSourceParser.no_rule_at_reject
#print axioms PNP.Concrete.CNFSourceParser.accept_configuration_halted
#print axioms PNP.Concrete.CNFSourceParser.reject_configuration_halted
#print axioms PNP.Concrete.CNFSourceParser.focusedConfiguration
#print axioms PNP.Concrete.CNFSourceParser.boot_step
#print axioms PNP.Concrete.CNFSourceParser.installGuard_step
#print axioms PNP.Concrete.CNFSourceParser.header_t_step
#print axioms PNP.Concrete.CNFSourceParser.header_f_step
#print axioms PNP.Concrete.CNFSourceParser.clauses_sep_step
#print axioms PNP.Concrete.CNFSourceParser.clauses_finish_step
#print axioms PNP.Concrete.CNFSourceParser.clause_f_step
#print axioms PNP.Concrete.CNFSourceParser.clause_t_step
#print axioms PNP.Concrete.CNFSourceParser.clause_finish_step
#print axioms PNP.Concrete.CNFSourceParser.literal_t_step
#print axioms PNP.Concrete.CNFSourceParser.literal_f_step
#print axioms PNP.Concrete.CNFSourceParser.expectPad_step
#print axioms PNP.Concrete.CNFSourceParser.finalEOF_blank_step
#print axioms PNP.Concrete.CNFSourceParser.header_sep_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.literal_finish_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.successRestore_guard_step
#print axioms PNP.Concrete.CNFSourceParser.cleanupSeek_guard_step
#print axioms PNP.Concrete.CNFSourceParser.cleanupRight_f_step
#print axioms PNP.Concrete.CNFSourceParser.cleanupRight_blank_step

/-! CNFSourceParserCorrectness. -/
#print axioms PNP.Concrete.CNFSourceParser.packWorkSymbols_encodeTokenPairs_formulaPad
#print axioms PNP.Concrete.CNFSourceParser.rawInputWorkTape_encodeTokenPairs_formulaPad
#print axioms PNP.Concrete.CNFSourceParser.packWorkSymbols_encodeTokenPairs
#print axioms PNP.Concrete.CNFSourceParser.rawInputWorkTape_encodeTokenPairs
#print axioms PNP.Concrete.CNFSourceParser.packWorkSymbols_encodeTokenPairs_wrongPad
#print axioms PNP.Concrete.CNFSourceParser.rawInputWorkTape_encodeTokenPairs_wrongPad
#print axioms PNP.Concrete.CNFSourceParser.rawInputWorkTape_encodeFormula
#print axioms PNP.Concrete.CNFSourceParser.unaryWord
#print axioms PNP.Concrete.CNFSourceParser.literalWord
#print axioms PNP.Concrete.CNFSourceParser.literalListWord
#print axioms PNP.Concrete.CNFSourceParser.clauseListWord
#print axioms PNP.Concrete.CNFSourceParser.formulaWord
#print axioms PNP.Concrete.CNFSourceParser.unaryWord_eq_token_work_symbols
#print axioms PNP.Concrete.CNFSourceParser.literalWord_eq_token_work_symbols
#print axioms PNP.Concrete.CNFSourceParser.literalListWord_eq_token_work_symbols
#print axioms PNP.Concrete.CNFSourceParser.clauseListWord_eq_token_work_symbols
#print axioms PNP.Concrete.CNFSourceParser.formulaWord_eq_token_work_symbols
#print axioms PNP.Concrete.CNFSourceParser.formulaWord_ne_nil
#print axioms PNP.Concrete.CNFSourceParser.headerUnary_exact
#print axioms PNP.Concrete.CNFSourceParser.literalUnary_exact
#print axioms PNP.Concrete.CNFSourceParser.literal_exact
#print axioms PNP.Concrete.CNFSourceParser.literalList_exact
#print axioms PNP.Concrete.CNFSourceParser.oneClauseBody_exact
#print axioms PNP.Concrete.CNFSourceParser.clauseBody_exact
#print axioms PNP.Concrete.CNFSourceParser.clauseList_exact
#print axioms PNP.Concrete.CNFSourceParser.formulaScan_exact
#print axioms PNP.Concrete.CNFSourceParser.RestorableSourceSymbol
#print axioms PNP.Concrete.CNFSourceParser.formulaWord_restorable
#print axioms PNP.Concrete.CNFSourceParser.successRestore_source_step
#print axioms PNP.Concrete.CNFSourceParser.restoreWord
#print axioms PNP.Concrete.CNFSourceParser.restoreWord_restorable
#print axioms PNP.Concrete.CNFSourceParser.restoreWord_length
#print axioms PNP.Concrete.CNFSourceParser.pushWorkLeft_restoreWord
#print axioms PNP.Concrete.CNFSourceParser.acceptedConfiguration
#print axioms PNP.Concrete.CNFSourceParser.acceptedConfiguration_state
#print axioms PNP.Concrete.CNFSourceParser.acceptedConfiguration_halted
#print axioms PNP.Concrete.CNFSourceParser.boot_formula_exact
#print axioms PNP.Concrete.CNFSourceParser.boot_nonempty_word_exact
#print axioms PNP.Concrete.CNFSourceParser.padAndEOF_exact
#print axioms PNP.Concrete.CNFSourceParser.canonical_restore_start
#print axioms PNP.Concrete.CNFSourceParser.restoreAndAccept_exact
#print axioms PNP.Concrete.CNFSourceParser.validWorkSteps
#print axioms PNP.Concrete.CNFSourceParser.encodeFormula_exact
#print axioms PNP.Concrete.CNFSourceParser.acceptedConfiguration_outputBits
#print axioms PNP.Concrete.CNFSourceParser.cleanupSeekGuard_workStep
#print axioms PNP.Concrete.CNFSourceParser.cleanupRight_workStep
#print axioms PNP.Concrete.CNFSourceParser.pushCleanupScan
#print axioms PNP.Concrete.CNFSourceParser.cleanupSeekConfiguration
#print axioms PNP.Concrete.CNFSourceParser.cleanupSeekGuard_exact
#print axioms PNP.Concrete.CNFSourceParser.pushCleanupScan_length
#print axioms PNP.Concrete.CNFSourceParser.pushCleanupBlanks
#print axioms PNP.Concrete.CNFSourceParser.cleanupRightFiniteConfiguration
#print axioms PNP.Concrete.CNFSourceParser.cleanupRightFinite_erase_exact
#print axioms PNP.Concrete.CNFSourceParser.cleanupRightFinite_reject_exact
#print axioms PNP.Concrete.CNFSourceParser.cleanupRightFinite_exact
#print axioms PNP.Concrete.CNFSourceParser.guardedCleanupSteps
#print axioms PNP.Concrete.CNFSourceParser.guardedCleanupSteps_eq
#print axioms PNP.Concrete.CNFSourceParser.cleanupRejectConfiguration
#print axioms PNP.Concrete.CNFSourceParser.guardedCleanupFinite_exact
#print axioms PNP.Concrete.CNFSourceParser.cleanupRejectConfiguration_output_empty
#print axioms PNP.Concrete.CNFSourceParser.cleanupRejectConfiguration_halted
#print axioms PNP.Concrete.CNFSourceParser.grammarState
#print axioms PNP.Concrete.CNFSourceParser.GrammarBoundary
#print axioms PNP.Concrete.CNFSourceParser.pushCleanupScan_eq_pushWorkLeft
#print axioms PNP.Concrete.CNFSourceParser.pushCleanupScan_consumed
#print axioms PNP.Concrete.CNFSourceParser.cleanupSeekConfiguration_of_consumed
#print axioms PNP.Concrete.CNFSourceParser.header_boundary_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.header_finish_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.clauses_boundary_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.clauses_f_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.clauses_t_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.clause_boundary_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.clause_sep_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.literal_boundary_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.literal_sep_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.expectPad_token_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.expectPad_wrongPad_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.expectPad_blank_enters_cleanup
#print axioms PNP.Concrete.CNFSourceParser.GrammarFailureTrace
#print axioms PNP.Concrete.CNFSourceParser.formulaGrammarFailure_exact
#print axioms PNP.Concrete.CNFSourceParser.cleanupRightConfiguration
#print axioms PNP.Concrete.CNFSourceParser.cleanupRight_erase_exact
#print axioms PNP.Concrete.CNFSourceParser.cleanupRight_reject_exact
#print axioms PNP.Concrete.CNFSourceParser.cleanupRight_exact
#print axioms PNP.Concrete.CNFSourceParser.guardedCleanupExplicitSteps
#print axioms PNP.Concrete.CNFSourceParser.cleanupExplicitRejectConfiguration
#print axioms PNP.Concrete.CNFSourceParser.guardedCleanupExplicit_exact
#print axioms PNP.Concrete.CNFSourceParser.cleanupExplicitRejectConfiguration_output_empty
#print axioms PNP.Concrete.CNFSourceParser.cleanupExplicitRejectConfiguration_halted
#print axioms PNP.Concrete.CNFSourceParser.tokenWorkSymbol_ne_blank
#print axioms PNP.Concrete.CNFSourceParser.tokenWorkSymbol_ne_leftGuard
#print axioms PNP.Concrete.CNFSourceParser.cnfTokenWorkSymbols_ne_blank
#print axioms PNP.Concrete.CNFSourceParser.cnfTokenWorkSymbols_ne_leftGuard
#print axioms PNP.Concrete.CNFSourceParser.formulaWord_ne_blank
#print axioms PNP.Concrete.CNFSourceParser.formulaWord_ne_leftGuard
#print axioms PNP.Concrete.CNFSourceParser.pushCleanupScan_eq_reverse_append
#print axioms PNP.Concrete.CNFSourceParser.mem_pushCleanupScan_of_mem
#print axioms PNP.Concrete.CNFSourceParser.formulaGrammarFailure_nonblank_exact
#print axioms PNP.Concrete.CNFSourceParser.formulaGrammarFailure_blank_exact
#print axioms PNP.Concrete.CNFSourceParser.decodedTokenWorkShape
#print axioms PNP.Concrete.CNFSourceParser.decodedTokens_wrongPad_exact
#print axioms PNP.Concrete.CNFSourceParser.decodedTokens_blank_exact
#print axioms PNP.Concrete.CNFSourceParser.parserWorkBound
#print axioms PNP.Concrete.CNFSourceParser.RejectingTrace
#print axioms PNP.Concrete.CNFSourceParser.ofSymbols_append_blank_blankEquivalent
#print axioms PNP.Concrete.CNFSourceParser.evenRawStart_blankEquivalent
#print axioms PNP.Concrete.CNFSourceParser.output_empty_of_workBlankEquivalent
#print axioms PNP.Concrete.CNFSourceParser.malformed_rejectingTrace
#print axioms PNP.Concrete.CNFSourceParser.ExactParserTrace
#print axioms PNP.Concrete.CNFSourceParser.allInput_exact
#print axioms PNP.Concrete.CNFSourceParser.allInput_exact_trace
#print axioms PNP.Concrete.CNFSourceParser.allInput_exact_output
#print axioms PNP.Concrete.CNFSourceParser.allInput_exact_accept_iff
#print axioms PNP.Concrete.CNFSourceParser.workRun_parserWorkBound
#print axioms PNP.Concrete.CNFSourceParser.workBoundedDecide_accept_iff
#print axioms PNP.Concrete.CNFSourceParser.workBoundedDecide_ne_timeout
#print axioms PNP.Concrete.CNFSourceParser.workBoundedDecide_reject_iff

/-! CNFSourceParserCompiled. -/
#print axioms PNP.Concrete.CNFSourceParser.rawTimePolynomial
#print axioms PNP.Concrete.CNFSourceParser.rawTimePolynomial_eval
#print axioms PNP.Concrete.CNFSourceParser.compiledStart_blankEquivalent
#print axioms PNP.Concrete.CNFSourceParser.compiledMachineOutput_eq_validatedCNFBytes
#print axioms PNP.Concrete.CNFSourceParser.compiledBoundedDecide_accept_iff
#print axioms PNP.Concrete.CNFSourceParser.compiledBoundedDecide_ne_timeout
#print axioms PNP.Concrete.CNFSourceParser.polynomialTimeMachine
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytesPolynomialTimeFunction
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytesPolynomialTimeFunction_output
#print axioms PNP.Concrete.CNFSourceParser.validatedCNFBytesRawRefinement

/-! CNFToNANDEmitterPlan. -/
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.Primitive
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.CursorMode
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.Runtime
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.sourceWidth
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.totalGateCount
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.outputIndex
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.capturedLiteralIndex
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.poppedCoordinate
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.gateAt
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.sourceWidth_evaluated
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.totalGateCount_evaluated
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.outputIndex_evaluated
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.capturedLiteralIndex_evaluated
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.poppedCoordinate_evaluated
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.gateAt_evaluated
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.RetainedCoordinate
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.RetainedCoordinate.counter
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.RetainedCoordinate.value
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitRetainedNatProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitCapturedNatProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitScratchNatProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.computeGateAtProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateAtNatProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emittedNatResult
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitRetainedNatProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitCapturedNatProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitScratchNatProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.computeGateAtProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateAtNatProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.EmissionSource
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.EmissionSource.evaluate
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.EmissionSource.finalScratch
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSourceProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSourceResult
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSourceProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.EmissionSource.evaluate_after_emit
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateResult
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateResult_targetTokens
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSelfNANDProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSelfNANDProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSelfNANDResult_targetTokens
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.advanceOutputIndexProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.advanceOutputIndexResult
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.advanceOutputIndexProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateAndAdvanceProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateAndAdvanceResult
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateAndAdvanceProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSelfNANDAndAdvanceProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSelfNANDAndAdvanceProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushFormulaMarkerProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushTotalGateSentinelProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushGateAtProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.popCoordinateProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushFormulaMarkerProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushTotalGateSentinelProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushGateAtProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.popCoordinateProgram_nonempty_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.popCoordinateProgram_empty_rejects
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitHeaderProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitHeaderResult
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitHeaderProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitSuffixProgram
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitSuffixResult
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitSuffixProgram_correct
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.MachineClosed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitRetainedNatProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitCapturedNatProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitScratchNatProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.computeGateAtProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateAtNatProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSourceProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSelfNANDProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.advanceOutputIndexProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitGateAndAdvanceProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.emitSelfNANDAndAdvanceProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushTotalGateSentinelProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushFormulaMarkerProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.pushGateAtProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.popCoordinateProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitHeaderProgram_closed
#print axioms PNP.Concrete.CNFToNANDEmitterPlan.circuitSuffixProgram_closed

/-! CNFToNANDCarrierTokenReader. -/
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.cell01
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.cell00
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.State.start
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.State.second
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.State.accept
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.State.reject
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.State.dead
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Action
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.deadAction
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.firstAction
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.secondAction
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.allWorkSymbols
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.rulesAt
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.rules
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.machine
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.firstSourceMachine
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.secondSourceMachine
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.QueryDistinct
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.start_ne_accept
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.start_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.configAtWord
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.false_exact
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.true_exact
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.false_halted
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.true_halted
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.sourceLeftBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.State.accept
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.State.reject
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.State.scan
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.packed
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.action
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.rules
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.machine
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.QueryDistinct
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierTokenReader.Rewind.boundary_step

/-! CNFToNANDCarrierEncoder. -/
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.firstBit
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.secondBit
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.asConstant
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.tokenGate
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierCircuit
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierCircuit_inputCount
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierCircuit_gates_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierCircuit_output
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.recoverTokenGate
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.recoverTokenGate_tokenGate
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.recover_carrier_gates
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierCircuit_injective
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.constantToken
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.tokenGateTokens
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.encodeGateTokens_tokenGate
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.gateTokenStream
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.gateTokenStream_eq_encodeGateListTokens
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.gateTokenStream_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierTokens
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierTokens_eq_encodeCircuitTokens
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.encodeCarrier_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierTokens_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierCircuit_cells
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.carrierCircuit_cells_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Source.rawInputWorkTape_encodeCarrier
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.cellBlank
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.sourceLeftBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.sourceTargetBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.formulaPad
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.State.accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.State.reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.State.first
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.State.scan
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.State.oldBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.State.installBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.State.rewind
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.Action
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.keep
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.write
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.packed
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.firstAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.scanAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.oldBoundaryAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.installBoundaryAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.rewindAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.StateProgram
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.statePrograms
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.rulesAt
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.rules
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.machine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.compiledMachine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.QueryDistinct
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.start_ne_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.start_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.entryTape
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.finalTape
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.entryConfiguration
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.finalConfiguration
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.workSteps
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.empty_rejects
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Prepare.canonical_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.startState
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.acceptState
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.rejectState
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.ruleFor
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.rules
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.machine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.QueryDistinct
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.accepts_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Match.rejects_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.sourceLeftBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.sourceTargetBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.State.accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.State.reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.State.leaveBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.State.scanLeft
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.targetMove
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.actionRule
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.rules
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.machine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.QueryDistinct
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.workSteps
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Rewind.canonical_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.cellBlank
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.sourceLeftBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.State.accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.State.reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.State.leaveTarget
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.State.seekBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.State.returnTarget
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.Action
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.packed
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.keep
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.leaveTargetAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.seekBoundaryAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.returnTargetAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.StateProgram
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.statePrograms
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.rulesAt
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.rules
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.machine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.QueryDistinct
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.finalTape
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.finalConfiguration
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.workSteps
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.BoundaryCleanup.cleanup_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.cellBlank
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.formulaPad
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.sourceLeftBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.sourceTargetBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.first
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.installLeft
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.scan
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.installTarget
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.leavePad
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.State.rewind
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.Action
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.packed
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.keep
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.firstAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.installLeftAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.scanAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.installTargetAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.leavePadAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.rewindAction
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.StateProgram
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.statePrograms
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.rulesAt
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.rules
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.machine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.QueryDistinct
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.workSteps
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.RawFramer.canonical_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.cnfTokenOrder
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.tokenCode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.tokenCode_injective
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.firstConstantToken
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.secondConstantToken
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.sourceSymbol
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.sourceSymbol_packed
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.controlRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.controlNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.prepare
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.headerVersion
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.headerInputEnd
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.countMatch
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.countBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.countInstall
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.countUnit
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.countRestore
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.countRewind
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateCountEnd
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateMatch
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateBoundary
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateInstall
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateFirst
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateSecond
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateEnd
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateRestore
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.gateRewind
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.suffixProgramEnd
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.suffixOutput
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.suffixOutputsEnd
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.suffixInstanceEnd
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.finalizer
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.cleanup
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.Address.framer
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.prepareRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.framerRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.headerVersionRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.headerInputEndRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countMatchRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countBoundaryRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countInstallRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countUnitRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countRestoreRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countRewindRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateCountEndRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateMatchRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateBoundaryRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateInstallRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateFirstRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateSecondRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateEndRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateRestoreRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateRewindRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixProgramEndRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixOutputRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixOutputsEndRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixInstanceEndRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.finalizerRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.cleanupRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.nextCountMatchRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.nextGateMatchRef
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.prepareNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.framerNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.headerVersionNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.headerInputEndNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countMatchNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countBoundaryNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countInstallNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countUnitNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countRestoreNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countRewindNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateCountEndNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateMatchNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateBoundaryNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateInstallNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateFirstNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateSecondNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateEndNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateRestoreNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateRewindNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixProgramEndNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixOutputNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixOutputsEndNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixInstanceEndNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.finalizerNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.cleanupNode
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.prefixNodes
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.countNodes
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.gateNodes
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.suffixNodes
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.nodes
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.graph
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.machine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.compiledMachine
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.graph_wellFormed
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.machine_start_ne_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.machine_start_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.machine_accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.no_rule_at_dead
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.nodes_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.rules_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.appendedTokenCount
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.initialBlankReserve
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.initialBlankReserve_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.targetCells
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.targetCells_length
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.entryPadding
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.entryPadding_eq_replicate
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.entryTape
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.entryConfiguration
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.finalTape
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.finalConfiguration
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.final_output_eq
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.rawInputWorkTape_tokenPad
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.entryTape_blankEquivalent_rawInput
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.finalTape_blankEquivalent_rawInput
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.appenderWorkSum
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.plannedWorkSteps
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.workPolynomial
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.workPolynomial_evaluated
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.plannedWorkSteps_polynomial_bound
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.empty_rejects
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.dispatchSteps
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.canonicalWorkSteps
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.canonical_exact
#print axioms PNP.Concrete.CNFToNANDCarrierEncoder.canonicalWorkSteps_polynomial_bound

/-! CNFToNANDWorkspace. -/
#print axioms PNP.Concrete.CNFToNANDWorkspace.formulaTokens
#print axioms PNP.Concrete.CNFToNANDWorkspace.formulaTokens_ne_nil
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierCircuit
#print axioms PNP.Concrete.CNFToNANDWorkspace.capacity
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerRegisters
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerWord
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierCircuit_inputCount
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierCircuit_gates_length
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierCircuit_output
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierCircuit_cells_length
#print axioms PNP.Concrete.CNFToNANDWorkspace.capacity_exact
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerRegisters_inputCount
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerRegisters_normalizedGateCount
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerRegisters_carrierWidth
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerRegisters_currentGate
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerRegisters_outputIndex
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerShape
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceWord
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters_inputCount
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters_normalizedGateCount
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters_carrierWidth
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters_baseline
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters_currentGate
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters_outputIndex
#print axioms PNP.Concrete.CNFToNANDWorkspace.formulaStackMarker
#print axioms PNP.Concrete.CNFToNANDWorkspace.formulaStackMarker_exact
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceRegisters_carrierWidth_eq_formulaStackMarker
#print axioms PNP.Concrete.CNFToNANDWorkspace.canonicalEncodedBits_length
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount_le_tokenBound
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount_lt_carrierWidth
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount_lt_formulaStackMarker
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount_lt_workspaceCarrierWidth
#print axioms PNP.Concrete.CNFToNANDWorkspace.formulaStackMarker_le_capacity
#print axioms PNP.Concrete.CNFToNANDWorkspace.variableCount_le_capacity
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount_add_two_le_capacity
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount_lt_capacity
#print axioms PNP.Concrete.CNFToNANDWorkspace.compilerGateCount_succ_lt_capacity
#print axioms PNP.Concrete.CNFToNANDWorkspace.realGateCoordinate_lt_sentinel
#print axioms PNP.Concrete.CNFToNANDWorkspace.realGateCoordinate_lt_formulaStackMarker
#print axioms PNP.Concrete.CNFToNANDWorkspace.realGateCoordinate_succ_lt_capacity
#print axioms PNP.Concrete.CNFToNANDWorkspace.workspaceShape
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerConfiguration
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerConfiguration_left
#print axioms PNP.Concrete.CNFToNANDWorkspace.postLedgerConfiguration_source_and_blank_target
#print axioms PNP.Concrete.CNFToNANDWorkspace.scannerLedgerMachine
#print axioms PNP.Concrete.CNFToNANDWorkspace.machine
#print axioms PNP.Concrete.CNFToNANDWorkspace.compiledMachine
#print axioms PNP.Concrete.CNFToNANDWorkspace.scannerLedger_rules_length
#print axioms PNP.Concrete.CNFToNANDWorkspace.rules_length
#print axioms PNP.Concrete.CNFToNANDWorkspace.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDWorkspace.machine_accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDWorkspace.rule_source_ne_accept
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierEntryConfiguration
#print axioms PNP.Concrete.CNFToNANDWorkspace.entryConfiguration
#print axioms PNP.Concrete.CNFToNANDWorkspace.finalConfiguration
#print axioms PNP.Concrete.CNFToNANDWorkspace.entryConfiguration_state
#print axioms PNP.Concrete.CNFToNANDWorkspace.entryConfiguration_blankEquivalent_rawInput
#print axioms PNP.Concrete.CNFToNANDWorkspace.finalConfiguration_state
#print axioms PNP.Concrete.CNFToNANDWorkspace.finalConfiguration_tape
#print axioms PNP.Concrete.CNFToNANDWorkspace.finalConfiguration_left
#print axioms PNP.Concrete.CNFToNANDWorkspace.finalConfiguration_source_and_blank_target
#print axioms PNP.Concrete.CNFToNANDWorkspace.finalConfiguration_outputBits
#print axioms PNP.Concrete.CNFToNANDWorkspace.scannerLedgerWorkSteps
#print axioms PNP.Concrete.CNFToNANDWorkspace.workSteps
#print axioms PNP.Concrete.CNFToNANDWorkspace.workSteps_eq
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierWorkSteps_polynomial_bound
#print axioms PNP.Concrete.CNFToNANDWorkspace.carrierWorkSteps_encodedPolynomial_bound
#print axioms PNP.Concrete.CNFToNANDWorkspace.exact_execution
#print axioms PNP.Concrete.CNFToNANDWorkspace.exact_execution_output
#print axioms PNP.Concrete.CNFToNANDWorkspace.exact_execution_registers

/-! CNFToNANDControllerBlocks. -/
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.Primitive
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.mode
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countWidthUnitProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countClauseProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countLiteralProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countValidNegativeProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countEmptyFormulaProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.resetLiteralIndexProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.advanceLiteralIndexProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.compareLiteralIndexToWidthProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.compareCoordinateToFalseProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.compareCoordinateToFormulaMarkerProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.initializeFormulaStackProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.initializeClauseStackProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitPositiveLiteralProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitNegativeLiteralProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitInvalidLiteralProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.seedClauseProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.extendClauseProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.finishNonemptyClauseProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.finishEmptyClauseProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.ClauseSource
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.ClauseSource.emission
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.seedFormulaProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.extendFormulaProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitEmptyFormulaProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitCircuitHeaderProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitCircuitSuffixProgram
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countWidthUnitProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countClauseProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countLiteralProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countValidNegativeProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.countEmptyFormulaProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.resetLiteralIndexProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.advanceLiteralIndexProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.compareLiteralIndexToWidthProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.compareCoordinateToFalseProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.compareCoordinateToFormulaMarkerProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.initializeFormulaStackProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.initializeClauseStackProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitPositiveLiteralProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitNegativeLiteralProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitInvalidLiteralProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.seedClauseProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.extendClauseProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.finishNonemptyClauseProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.finishEmptyClauseProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.seedFormulaProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.extendFormulaProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitEmptyFormulaProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitCircuitHeaderProgram_closed
#print axioms PNP.Concrete.CNFToNANDControllerBlocks.emitCircuitSuffixProgram_closed

/-! CNFToNANDController. -/
#print axioms PNP.Concrete.CNFToNANDController.Primitive
#print axioms PNP.Concrete.CNFToNANDController.Blocks.countNegativeSignProgram
#print axioms PNP.Concrete.CNFToNANDController.Blocks.countPositiveSignProgram
#print axioms PNP.Concrete.CNFToNANDController.Blocks.emitNegativeSignProgram
#print axioms PNP.Concrete.CNFToNANDController.Blocks.emitPositiveSignProgram
#print axioms PNP.Concrete.CNFToNANDController.Blocks.popCoordinateProgram
#print axioms PNP.Concrete.CNFToNANDController.Pass
#print axioms PNP.Concrete.CNFToNANDController.FinishKind
#print axioms PNP.Concrete.CNFToNANDController.GrammarState
#print axioms PNP.Concrete.CNFToNANDController.passes
#print axioms PNP.Concrete.CNFToNANDController.activeGrammarStates
#print axioms PNP.Concrete.CNFToNANDController.grammarStates
#print axioms PNP.Concrete.CNFToNANDController.finishKinds
#print axioms PNP.Concrete.CNFToNANDController.cnfTokens
#print axioms PNP.Concrete.CNFToNANDController.bools
#print axioms PNP.Concrete.CNFToNANDController.Pass.code
#print axioms PNP.Concrete.CNFToNANDController.FinishKind.code
#print axioms PNP.Concrete.CNFToNANDController.GrammarState.code
#print axioms PNP.Concrete.CNFToNANDController.tokenCode
#print axioms PNP.Concrete.CNFToNANDController.tokenSecondCell
#print axioms PNP.Concrete.CNFToNANDController.stateFinishKind?
#print axioms PNP.Concrete.CNFToNANDController.validGrammarToken
#print axioms PNP.Concrete.CNFToNANDController.deterministicNextState
#print axioms PNP.Concrete.CNFToNANDController.inRangeState
#print axioms PNP.Concrete.CNFToNANDController.overflowState
#print axioms PNP.Concrete.CNFToNANDController.actionCode
#print axioms PNP.Concrete.CNFToNANDController.controlNodeName
#print axioms PNP.Concrete.CNFToNANDController.controlNodeName_even
#print axioms PNP.Concrete.CNFToNANDController.control_ne_block
#print axioms PNP.Concrete.CNFToNANDController.controlRef
#print axioms PNP.Concrete.CNFToNANDController.controlNode
#print axioms PNP.Concrete.CNFToNANDController.Address.scanner
#print axioms PNP.Concrete.CNFToNANDController.Address.ledger
#print axioms PNP.Concrete.CNFToNANDController.Address.workspaceZero
#print axioms PNP.Concrete.CNFToNANDController.Address.validationHeader
#print axioms PNP.Concrete.CNFToNANDController.Address.validationFirst
#print axioms PNP.Concrete.CNFToNANDController.Address.validationFirstNonInput
#print axioms PNP.Concrete.CNFToNANDController.Address.validationFirstConstant
#print axioms PNP.Concrete.CNFToNANDController.Address.validationFirstReader
#print axioms PNP.Concrete.CNFToNANDController.Address.validationSecond
#print axioms PNP.Concrete.CNFToNANDController.Address.validationSecondNonInput
#print axioms PNP.Concrete.CNFToNANDController.Address.validationSecondConstant
#print axioms PNP.Concrete.CNFToNANDController.Address.validationSecondReader
#print axioms PNP.Concrete.CNFToNANDController.Address.validationAdvance
#print axioms PNP.Concrete.CNFToNANDController.Address.validationProgramEnd
#print axioms PNP.Concrete.CNFToNANDController.Address.validationOutputFirst
#print axioms PNP.Concrete.CNFToNANDController.Address.validationOutputNonInput
#print axioms PNP.Concrete.CNFToNANDController.Address.validationOutput
#print axioms PNP.Concrete.CNFToNANDController.Address.validationRewind
#print axioms PNP.Concrete.CNFToNANDController.Address.countHeader
#print axioms PNP.Concrete.CNFToNANDController.Address.emitHeader
#print axioms PNP.Concrete.CNFToNANDController.Address.stackInitialize
#print axioms PNP.Concrete.CNFToNANDController.Address.firstBit
#print axioms PNP.Concrete.CNFToNANDController.Address.secondBit
#print axioms PNP.Concrete.CNFToNANDController.Address.install
#print axioms PNP.Concrete.CNFToNANDController.Address.literalCompare
#print axioms PNP.Concrete.CNFToNANDController.Address.restore
#print axioms PNP.Concrete.CNFToNANDController.Address.gateAdvance
#print axioms PNP.Concrete.CNFToNANDController.Address.programEnd
#print axioms PNP.Concrete.CNFToNANDController.Address.countRewind
#print axioms PNP.Concrete.CNFToNANDController.Address.countInstallVersion
#print axioms PNP.Concrete.CNFToNANDController.Address.countRestoreVersion
#print axioms PNP.Concrete.CNFToNANDController.Address.countPassRewind
#print axioms PNP.Concrete.CNFToNANDController.Address.emitRewind
#print axioms PNP.Concrete.CNFToNANDController.Address.emitInstallVersion
#print axioms PNP.Concrete.CNFToNANDController.Address.clauseCompareFirst
#print axioms PNP.Concrete.CNFToNANDController.Address.clauseCompareLoop
#print axioms PNP.Concrete.CNFToNANDController.Address.formulaCompareMarkerFirst
#print axioms PNP.Concrete.CNFToNANDController.Address.formulaCompareFalseFirst
#print axioms PNP.Concrete.CNFToNANDController.Address.formulaCompareMarkerLoop
#print axioms PNP.Concrete.CNFToNANDController.Address.formulaCompareFalseLoop
#print axioms PNP.Concrete.CNFToNANDController.Address.finalizer
#print axioms PNP.Concrete.CNFToNANDController.Block.resetWorkspace
#print axioms PNP.Concrete.CNFToNANDController.Block.countWidth
#print axioms PNP.Concrete.CNFToNANDController.Block.countClause
#print axioms PNP.Concrete.CNFToNANDController.Block.countEmptyFormula
#print axioms PNP.Concrete.CNFToNANDController.Block.countNegativeSign
#print axioms PNP.Concrete.CNFToNANDController.Block.countPositiveSign
#print axioms PNP.Concrete.CNFToNANDController.Block.countValidNegative
#print axioms PNP.Concrete.CNFToNANDController.Block.countAdvancePositive
#print axioms PNP.Concrete.CNFToNANDController.Block.countAdvanceNegative
#print axioms PNP.Concrete.CNFToNANDController.Block.emitInitializeClause
#print axioms PNP.Concrete.CNFToNANDController.Block.emitNegativeSign
#print axioms PNP.Concrete.CNFToNANDController.Block.emitPositiveSign
#print axioms PNP.Concrete.CNFToNANDController.Block.emitPositiveLiteral
#print axioms PNP.Concrete.CNFToNANDController.Block.emitNegativeLiteral
#print axioms PNP.Concrete.CNFToNANDController.Block.emitInvalidLiteral
#print axioms PNP.Concrete.CNFToNANDController.Block.emitAdvancePositive
#print axioms PNP.Concrete.CNFToNANDController.Block.emitAdvanceNegative
#print axioms PNP.Concrete.CNFToNANDController.Block.emitHeader
#print axioms PNP.Concrete.CNFToNANDController.Block.initializeFormula
#print axioms PNP.Concrete.CNFToNANDController.Block.clausePopFirst
#print axioms PNP.Concrete.CNFToNANDController.Block.clauseSeed
#print axioms PNP.Concrete.CNFToNANDController.Block.clausePopLoop
#print axioms PNP.Concrete.CNFToNANDController.Block.clauseExtend
#print axioms PNP.Concrete.CNFToNANDController.Block.clauseFinishNonempty
#print axioms PNP.Concrete.CNFToNANDController.Block.clauseFinishEmpty
#print axioms PNP.Concrete.CNFToNANDController.Block.formulaPopFirst
#print axioms PNP.Concrete.CNFToNANDController.Block.formulaSeedFalse
#print axioms PNP.Concrete.CNFToNANDController.Block.formulaSeedGate
#print axioms PNP.Concrete.CNFToNANDController.Block.formulaPopLoop
#print axioms PNP.Concrete.CNFToNANDController.Block.formulaExtendFalse
#print axioms PNP.Concrete.CNFToNANDController.Block.formulaExtendGate
#print axioms PNP.Concrete.CNFToNANDController.Block.formulaEmpty
#print axioms PNP.Concrete.CNFToNANDController.Block.suffix
#print axioms PNP.Concrete.CNFToNANDController.scannerRef
#print axioms PNP.Concrete.CNFToNANDController.ledgerRef
#print axioms PNP.Concrete.CNFToNANDController.stackInitializeRef
#print axioms PNP.Concrete.CNFToNANDController.workspaceZeroRef
#print axioms PNP.Concrete.CNFToNANDController.validationHeaderRef
#print axioms PNP.Concrete.CNFToNANDController.validationFirstRef
#print axioms PNP.Concrete.CNFToNANDController.validationFirstNonInputRef
#print axioms PNP.Concrete.CNFToNANDController.validationFirstConstantRef
#print axioms PNP.Concrete.CNFToNANDController.validationFirstReaderRef
#print axioms PNP.Concrete.CNFToNANDController.validationSecondRef
#print axioms PNP.Concrete.CNFToNANDController.validationSecondNonInputRef
#print axioms PNP.Concrete.CNFToNANDController.validationSecondConstantRef
#print axioms PNP.Concrete.CNFToNANDController.validationSecondReaderRef
#print axioms PNP.Concrete.CNFToNANDController.validationAdvanceRef
#print axioms PNP.Concrete.CNFToNANDController.validationProgramEndRef
#print axioms PNP.Concrete.CNFToNANDController.validationOutputRef
#print axioms PNP.Concrete.CNFToNANDController.validationOutputFirstRef
#print axioms PNP.Concrete.CNFToNANDController.validationOutputNonInputRef
#print axioms PNP.Concrete.CNFToNANDController.validationRewindRef
#print axioms PNP.Concrete.CNFToNANDController.passHeaderRef
#print axioms PNP.Concrete.CNFToNANDController.firstBitRef
#print axioms PNP.Concrete.CNFToNANDController.secondBitRef
#print axioms PNP.Concrete.CNFToNANDController.installRef
#print axioms PNP.Concrete.CNFToNANDController.literalCompareRef
#print axioms PNP.Concrete.CNFToNANDController.restoreRef
#print axioms PNP.Concrete.CNFToNANDController.gateAdvanceRef
#print axioms PNP.Concrete.CNFToNANDController.programEndRef
#print axioms PNP.Concrete.CNFToNANDController.countRewindRef
#print axioms PNP.Concrete.CNFToNANDController.countInstallVersionRef
#print axioms PNP.Concrete.CNFToNANDController.countRestoreVersionRef
#print axioms PNP.Concrete.CNFToNANDController.countPassRewindRef
#print axioms PNP.Concrete.CNFToNANDController.emitRewindRef
#print axioms PNP.Concrete.CNFToNANDController.emitInstallVersionRef
#print axioms PNP.Concrete.CNFToNANDController.clauseCompareFirstRef
#print axioms PNP.Concrete.CNFToNANDController.clauseCompareLoopRef
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareMarkerFirstRef
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareFalseFirstRef
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareMarkerLoopRef
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareFalseLoopRef
#print axioms PNP.Concrete.CNFToNANDController.finalizerRef
#print axioms PNP.Concrete.CNFToNANDController.resetWorkspaceRef
#print axioms PNP.Concrete.CNFToNANDController.countWidthRef
#print axioms PNP.Concrete.CNFToNANDController.countClauseRef
#print axioms PNP.Concrete.CNFToNANDController.countEmptyFormulaRef
#print axioms PNP.Concrete.CNFToNANDController.countNegativeSignRef
#print axioms PNP.Concrete.CNFToNANDController.countPositiveSignRef
#print axioms PNP.Concrete.CNFToNANDController.countValidNegativeRef
#print axioms PNP.Concrete.CNFToNANDController.countAdvancePositiveRef
#print axioms PNP.Concrete.CNFToNANDController.countAdvanceNegativeRef
#print axioms PNP.Concrete.CNFToNANDController.emitInitializeClauseRef
#print axioms PNP.Concrete.CNFToNANDController.emitNegativeSignRef
#print axioms PNP.Concrete.CNFToNANDController.emitPositiveSignRef
#print axioms PNP.Concrete.CNFToNANDController.emitPositiveLiteralRef
#print axioms PNP.Concrete.CNFToNANDController.emitNegativeLiteralRef
#print axioms PNP.Concrete.CNFToNANDController.emitInvalidLiteralRef
#print axioms PNP.Concrete.CNFToNANDController.emitAdvancePositiveRef
#print axioms PNP.Concrete.CNFToNANDController.emitAdvanceNegativeRef
#print axioms PNP.Concrete.CNFToNANDController.emittedHeaderRef
#print axioms PNP.Concrete.CNFToNANDController.initializeFormulaRef
#print axioms PNP.Concrete.CNFToNANDController.clausePopFirstRef
#print axioms PNP.Concrete.CNFToNANDController.clauseSeedRef
#print axioms PNP.Concrete.CNFToNANDController.clausePopLoopRef
#print axioms PNP.Concrete.CNFToNANDController.clauseExtendRef
#print axioms PNP.Concrete.CNFToNANDController.clauseFinishNonemptyRef
#print axioms PNP.Concrete.CNFToNANDController.clauseFinishEmptyRef
#print axioms PNP.Concrete.CNFToNANDController.formulaPopFirstRef
#print axioms PNP.Concrete.CNFToNANDController.formulaSeedFalseRef
#print axioms PNP.Concrete.CNFToNANDController.formulaSeedGateRef
#print axioms PNP.Concrete.CNFToNANDController.formulaPopLoopRef
#print axioms PNP.Concrete.CNFToNANDController.formulaExtendFalseRef
#print axioms PNP.Concrete.CNFToNANDController.formulaExtendGateRef
#print axioms PNP.Concrete.CNFToNANDController.formulaEmptyRef
#print axioms PNP.Concrete.CNFToNANDController.suffixRef
#print axioms PNP.Concrete.CNFToNANDController.grammarActionEndpoint
#print axioms PNP.Concrete.CNFToNANDController.postInstallEndpoint
#print axioms PNP.Concrete.CNFToNANDController.recoveredToken
#print axioms PNP.Concrete.CNFToNANDController.advanceLiteralRef
#print axioms PNP.Concrete.CNFToNANDController.scannerNode
#print axioms PNP.Concrete.CNFToNANDController.ledgerNode
#print axioms PNP.Concrete.CNFToNANDController.stackInitializeNode
#print axioms PNP.Concrete.CNFToNANDController.workspaceZeroNode
#print axioms PNP.Concrete.CNFToNANDController.validationHeaderNode
#print axioms PNP.Concrete.CNFToNANDController.validationFirstNode
#print axioms PNP.Concrete.CNFToNANDController.validationFirstNonInputNode
#print axioms PNP.Concrete.CNFToNANDController.validationFirstConstantNode
#print axioms PNP.Concrete.CNFToNANDController.validationFirstReaderNode
#print axioms PNP.Concrete.CNFToNANDController.validationSecondNode
#print axioms PNP.Concrete.CNFToNANDController.validationSecondNonInputNode
#print axioms PNP.Concrete.CNFToNANDController.validationSecondConstantNode
#print axioms PNP.Concrete.CNFToNANDController.validationSecondReaderNode
#print axioms PNP.Concrete.CNFToNANDController.validationAdvanceNode
#print axioms PNP.Concrete.CNFToNANDController.validationProgramEndNode
#print axioms PNP.Concrete.CNFToNANDController.validationOutputFirstNode
#print axioms PNP.Concrete.CNFToNANDController.validationOutputNonInputNode
#print axioms PNP.Concrete.CNFToNANDController.validationOutputNode
#print axioms PNP.Concrete.CNFToNANDController.validationRewindNode
#print axioms PNP.Concrete.CNFToNANDController.passHeaderNode
#print axioms PNP.Concrete.CNFToNANDController.firstBitNode
#print axioms PNP.Concrete.CNFToNANDController.secondBitNode
#print axioms PNP.Concrete.CNFToNANDController.installNode
#print axioms PNP.Concrete.CNFToNANDController.signCompareNode
#print axioms PNP.Concrete.CNFToNANDController.literalUnitCompareNode
#print axioms PNP.Concrete.CNFToNANDController.literalTerminatorCompareNode
#print axioms PNP.Concrete.CNFToNANDController.restoreNode
#print axioms PNP.Concrete.CNFToNANDController.gateAdvanceNode
#print axioms PNP.Concrete.CNFToNANDController.programEndNode
#print axioms PNP.Concrete.CNFToNANDController.countRewindNode
#print axioms PNP.Concrete.CNFToNANDController.countInstallVersionNode
#print axioms PNP.Concrete.CNFToNANDController.countRestoreVersionNode
#print axioms PNP.Concrete.CNFToNANDController.countPassRewindNode
#print axioms PNP.Concrete.CNFToNANDController.emitRewindNode
#print axioms PNP.Concrete.CNFToNANDController.emitInstallVersionNode
#print axioms PNP.Concrete.CNFToNANDController.clauseCompareFirstNode
#print axioms PNP.Concrete.CNFToNANDController.clauseCompareLoopNode
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareMarkerFirstNode
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareFalseFirstNode
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareMarkerLoopNode
#print axioms PNP.Concrete.CNFToNANDController.formulaCompareFalseLoopNode
#print axioms PNP.Concrete.CNFToNANDController.finalizerNode
#print axioms PNP.Concrete.CNFToNANDController.ControlDescriptor
#print axioms PNP.Concrete.CNFToNANDController.ControlDescriptor.materialize
#print axioms PNP.Concrete.CNFToNANDController.fixedPrefixDescriptors
#print axioms PNP.Concrete.CNFToNANDController.grammarReaderDescriptors
#print axioms PNP.Concrete.CNFToNANDController.installDescriptors
#print axioms PNP.Concrete.CNFToNANDController.literalCompareDescriptors
#print axioms PNP.Concrete.CNFToNANDController.restoreDescriptors
#print axioms PNP.Concrete.CNFToNANDController.gateAdvanceDescriptors
#print axioms PNP.Concrete.CNFToNANDController.programEndDescriptors
#print axioms PNP.Concrete.CNFToNANDController.fixedSuffixDescriptors
#print axioms PNP.Concrete.CNFToNANDController.controlDescriptors
#print axioms PNP.Concrete.CNFToNANDController.controlNodes
#print axioms PNP.Concrete.CNFToNANDController.BlockDescriptor
#print axioms PNP.Concrete.CNFToNANDController.BlockDescriptor.materialize
#print axioms PNP.Concrete.CNFToNANDController.blockDescriptors
#print axioms PNP.Concrete.CNFToNANDController.allBlockNodes
#print axioms PNP.Concrete.CNFToNANDController.nodes
#print axioms PNP.Concrete.CNFToNANDController.controlNode_member_nodes
#print axioms PNP.Concrete.CNFToNANDController.blockNode_member_nodes
#print axioms PNP.Concrete.CNFToNANDController.descriptorBlockNode_member_nodes
#print axioms PNP.Concrete.CNFToNANDController.graph
#print axioms PNP.Concrete.CNFToNANDController.graph_wellFormed
#print axioms PNP.Concrete.CNFToNANDController.machine
#print axioms PNP.Concrete.CNFToNANDController.compiledMachine
#print axioms PNP.Concrete.CNFToNANDController.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDController.machine_start_ne_accept
#print axioms PNP.Concrete.CNFToNANDController.machine_start_ne_reject
#print axioms PNP.Concrete.CNFToNANDController.machine_accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDController.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDController.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDController.no_rule_at_dead
#print axioms PNP.Concrete.CNFToNANDController.accept_halted
#print axioms PNP.Concrete.CNFToNANDController.reject_halted
#print axioms PNP.Concrete.CNFToNANDController.dead_stuck
#print axioms PNP.Concrete.CNFToNANDController.rules_length
#print axioms PNP.Concrete.CNFToNANDController.ruleCount
#print axioms PNP.Concrete.CNFToNANDController.rules_length_literal
#print axioms PNP.Concrete.CNFToNANDController.nodeCount
#print axioms PNP.Concrete.CNFToNANDController.nodes_length_literal
#print axioms PNP.Concrete.CNFToNANDController.scanner_accepts_only_into_ledger
#print axioms PNP.Concrete.CNFToNANDController.ledger_accepts_only_into_stack_initializer
#print axioms PNP.Concrete.CNFToNANDController.stack_initializer_accepts_only_into_workspace_reset
#print axioms PNP.Concrete.CNFToNANDController.workspace_zero_accepts_validation
#print axioms PNP.Concrete.CNFToNANDController.validation_requires_a_gate
#print axioms PNP.Concrete.CNFToNANDController.validation_first_input_rejects
#print axioms PNP.Concrete.CNFToNANDController.validation_first_gate_rejects
#print axioms PNP.Concrete.CNFToNANDController.validation_second_input_rejects
#print axioms PNP.Concrete.CNFToNANDController.validation_second_gate_rejects
#print axioms PNP.Concrete.CNFToNANDController.validation_output_input_rejects
#print axioms PNP.Concrete.CNFToNANDController.validation_output_gate_rejects
#print axioms PNP.Concrete.CNFToNANDController.validation_output_true_rejects
#print axioms PNP.Concrete.CNFToNANDController.validation_output_false_rewinds
#print axioms PNP.Concrete.CNFToNANDController.invalid_grammar_token_rejects
#print axioms PNP.Concrete.CNFToNANDController.finished_gate_rejects_extra_carrier_gate
#print axioms PNP.Concrete.CNFToNANDController.suffix_is_literal_closed_block

/-! CNFToNANDControllerCanonicalTrace. -/
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.Runtime
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.SourceContext
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.CursorLayout
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.ProgramSafe
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.TapeRepresents
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.materializedBlock_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.scanner_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.ledger_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.prefixSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.scanner_ledger_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.ledgerHandoffConfiguration
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.stackInitializeSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.stack_initialize_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.initializedPrefixSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.scanner_ledger_stack_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.canonicalSource
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.canonicalSource_eq_cons
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.canonicalSourceContext
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.postLedgerFits
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.resetSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.reset_path_of_represents
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.workspaceZeroSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.workspace_zero_path_of_represents
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.initializedResetSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.scanner_ledger_stack_reset_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.focusTape
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.constantSecondCell
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.sourceCells_constant
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationSourceSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationGateSourceSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationAdvanceSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.carrierGateCellsFor
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.carrierGateCells
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.carrierGateCells_eq_gateListCells
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.carrierHeaderCells
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.carrierFooterCells
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.canonicalSource_eq_carrier_layout
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationHeaderSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationGateSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationGatesSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationGatesSteps_eq
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationFooterSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationScannedPrefix
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationRewindWorkSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationRewindSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.carrierGateCells_length
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.carrierHeaderCells_length
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationHeaderSteps_eq
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationRewindSteps_eq
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationSteps_eq
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationOutsideLeft
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validationLeftWorkspace_eq
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.canonical_validation_path
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.validation_path_of_represents
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.canonicalPrefixSteps
#print axioms PNP.Concrete.CNFToNANDControllerCanonicalTrace.canonical_prefix_path

/-! CNFToNANDControllerCountTrace. -/
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.Runtime
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.SourceContext
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.CursorLayout
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.ProgramSafe
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.PrimitiveSafe
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.LedgerFits
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.headerTokens
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.emitInitialRuntime
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.emitInitialRuntime_scratch
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.emitInitialRuntime_registers
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.emitInitialRuntime_checks
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.emitInitialRuntime_targetTokens
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.ScanRepresents
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.scanRepresents_nil_iff_tapeRepresents
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countedRegisters
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countedRegisters_inputCount
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countedRegisters_currentGate
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countedRegisters_outputIndex
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countedRegisters_zero
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countedRegisters_final
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.literalGateCharge
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.clauseGateCharge
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.clausesGateCharge
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.literalGateCharge_eq
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.clauseGateCharge_eq
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.clausesGateCharge_eq
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.compilerGateCount_eq_count_charge
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countedRegisters_fits
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.passHeaderNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.firstBitNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.secondBitNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.installNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.signCompareNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.literalUnitCompareNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.literalTerminatorCompareNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.restoreNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.gateAdvanceNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.programEndNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRewindNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countInstallVersionNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRestoreVersionNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countPassRewindNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.finalizerNode_member
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.tokenBeforeCells
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.tokenAfterCells
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.scanBeforeCells
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.scanAfterCells
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.markedSource
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.markedSourceContext
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.markedCursorLayout
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.tokenReaderSteps
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.token_bits_reader_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.tokenReadInstallSteps
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.token_read_install_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.tokenRestoreAdvanceSteps
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.token_restore_advance_next_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.token_restore_advance_end_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.passRewindRef
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.programEndSteps
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.program_end_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.sourceRewindSteps
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.source_rewind_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countHeaderScanSteps
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_header_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.literalCompareSteps
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.literal_compare_equal_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.literal_compare_less_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRuntime
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRuntime_scratch
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRuntime_registers
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRuntime_checks
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRuntime_targetTokens
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countRuntime_initial
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countBlockEnvelope
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_width_block_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_clause_block_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_negative_sign_block_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_positive_sign_block_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_valid_negative_block_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_advance_literal_block_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_empty_formula_block_path
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countPassEnvelope
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.countPassEnvelope_le_allocated
#print axioms PNP.Concrete.CNFToNANDControllerCountTrace.count_pass_path

/-! CNFToNANDControllerCompletionTrace. -/
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.Runtime
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.SourceContext
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.CursorLayout
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.ProgramSafe
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.PrimitiveSafe
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.LedgerFits
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.ScanRepresents
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.headerTokens
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.emitInitialRuntime
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.emitHeaderScanSteps
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.emit_header_path
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.encodeWorkTape_outputBits_eq_of_blankEquivalent
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.emitTraversalCost
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.completionEnvelope
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.completion_path
#print axioms PNP.Concrete.CNFToNANDControllerCompletionTrace.completionEnvelope_le_allocated

/-! CNFToNANDControllerPolynomialBound. -/
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.squareUnit
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.dataMajorant
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.masterMajorant
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.descriptorProgramLimit
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.phaseUnit
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.controllerWorkBound
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.controllerWorkTimePolynomial
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.controllerWorkTimePolynomial_eval
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.compiledRawTimePolynomial
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.compiledRawTimePolynomial_eval
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.one_le_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.formulaTokens_le_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.carrierCells_le_sixteen_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.capacity_le_1024_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.compilerGateCount_le_sixteen_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.formulaStackMarker_le_1024_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.carrierTokenCount_le_sixteen_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.shiftedSize_le_masterMajorant
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.capacity_le_masterMajorant
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.carrierCells_le_masterMajorant
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.primitiveEnvelope_add_one_le_phaseUnit
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.one_le_phaseUnit
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.descriptorProgramEnvelope_le_phaseUnit
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.validationSteps_le_sixtyFour_shiftedSize
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.canonicalPrefixSteps_le_seven_phaseUnits
#print axioms PNP.Concrete.CNFToNANDControllerPolynomialBound.canonicalPrefixSteps_le_controllerWorkBound

/-! CNFToNANDControllerTotalBound. -/
#print axioms PNP.Concrete.CNFToNANDControllerTotalBound.canonicalEnvelope
#print axioms PNP.Concrete.CNFToNANDControllerTotalBound.canonicalEnvelope_le_controllerWorkBound

/-! CNFToNANDControllerTotalTrace. -/
#print axioms PNP.Concrete.CNFToNANDControllerTotalTrace.canonical_path
#print axioms PNP.Concrete.CNFToNANDControllerTotalTrace.canonical_bounded_exact

/-! CNFToNANDCompilerMachine. -/
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.parserRef
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.carrierRef
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.controllerRef
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.parserNode
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.carrierNode
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.controllerNode
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.nodes
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.graph
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.machine
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.compiledMachine
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.parserNode_member
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.carrierNode_member
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.controllerNode_member
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.graph_wellFormed
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.rules_pairwise
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.machine_start_ne_accept
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.machine_start_ne_reject
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.machine_accept_ne_reject
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.no_rule_at_accept
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.no_rule_at_reject
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.no_rule_at_dead
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.accept_halted
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.reject_halted
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.dead_stuck
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.nodeCount
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.nodes_length_literal
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.ruleCount
#print axioms PNP.Concrete.CNFToNANDCompilerMachine.rules_length_literal

/-! CNFToNANDCompilerTrace. -/
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.parser_path
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.decoded_parser_path
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.parserAcceptedTape_blankEquivalent_rawInput
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.parserAcceptedTape_blankEquivalent_carrierEntry
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.carrier_path
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.preControllerSteps
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.preController_path
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.decoded_preController_path
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.malformed_path
#print axioms PNP.Concrete.CNFToNANDCompilerTrace.malformed_exact

/-! CNFToNANDCompilerPolynomialBound. -/
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.parserWorkTimePolynomial
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.parserWorkTimePolynomial_eval
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.allInputWorkTimePolynomial
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.allInputWorkBound
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.allInputWorkTimePolynomial_eval
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.compiledRawTimePolynomial
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.compiledRawTimePolynomial_eval
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.formulaTokens_length_le_encodedBits
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.parserValidWorkSteps_le
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.carrierCanonicalWorkSteps_le
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.malformedWorkBound_le
#print axioms PNP.Concrete.CNFToNANDCompilerPolynomialBound.canonicalComponents_le

/-! CNFToNANDCompilerTotalTrace. -/
#print axioms PNP.Concrete.CNFToNANDCompilerTotalTrace.malformed_bounded_exact
#print axioms PNP.Concrete.CNFToNANDCompilerTotalTrace.decoded_bounded_exact
#print axioms PNP.Concrete.CNFToNANDCompilerTotalTrace.allInput_bounded_exact
#print axioms PNP.Concrete.CNFToNANDCompilerTotalTrace.allInput_exact

/-! CNFToNANDCompilerCompiled. -/
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.machine
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.compiledMachine
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.compiledStart_blankEquivalent
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.compiledMachineOutput_eq_compileEncodedCNFToNAND
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.compiledBoundedDecide_accept_iff
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.compiledBoundedDecide_ne_timeout
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.polynomialTimeMachine
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.cnfToNANDPolynomialTimeFunction
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.cnfToNANDPolynomialTimeFunction_output
#print axioms PNP.Concrete.CNFToNANDCompilerCompiled.cnfToNANDRawRefinement

/-! CNFToNANDPolynomialReduction. -/
#print axioms PNP.Concrete.CNFToNAND.cnfToNANDPolynomialReduction
#print axioms PNP.Concrete.CNFToNAND.cnfToNANDPolynomialReduction_function
#print axioms PNP.Concrete.CNFToNAND.cnfToNANDPolynomialReduction_output
#print axioms PNP.Concrete.CNFToNAND.cnfToNANDPolynomialReduction_correct
#print axioms PNP.Concrete.CNFToNAND.cnfSAT_reducesTo_encodedNANDSAT
#print axioms PNP.Concrete.CNFToNAND.cnfToNANDPolynomialReduction_rawRefinement
#print axioms PNP.Concrete.CNFToNAND.cnfToNANDPolynomialReduction_hasRawRefinement
#print axioms PNP.Concrete.CNFToNAND.cnfToLockedNANDPolynomialReduction
#print axioms PNP.Concrete.CNFToNAND.cnfToLockedNANDPolynomialReduction_output
#print axioms PNP.Concrete.CNFToNAND.cnfToLockedNANDPolynomialReduction_correct
#print axioms PNP.Concrete.CNFToNAND.cnfSAT_reducesTo_encodedLockedNANDThreshold
#print axioms PNP.Concrete.CNFToNAND.cnfToLockedNANDPolynomialReduction_rawRefinement
#print axioms PNP.Concrete.CNFToNAND.cnfToLockedNANDPolynomialReduction_hasRawRefinement
