import PNP.LockedNANDCarrierTrace

#print axioms PNP.DirectWire.LockedNANDTrace.Circuit
#print axioms PNP.DirectWire.LockedNANDTrace.Circuit.Satisfiable
#print axioms PNP.DirectWire.LockedNANDTrace.OccurrenceSide
#print axioms PNP.DirectWire.LockedNANDTrace.OccurrenceSide.offset
#print axioms PNP.DirectWire.LockedNANDTrace.carrierWidth
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierSlot
#print axioms PNP.DirectWire.LockedNANDTrace.occurrenceCoordinate
#print axioms PNP.DirectWire.LockedNANDTrace.occurrenceCoordinate_left_val
#print axioms PNP.DirectWire.LockedNANDTrace.occurrenceCoordinate_right_val
#print axioms PNP.DirectWire.LockedNANDTrace.occurrenceCoordinate_injective
#print axioms PNP.DirectWire.LockedNANDTrace.occurrenceCoordinate_left_ne_right
#print axioms PNP.DirectWire.LockedNANDTrace.primarySlot
#print axioms PNP.DirectWire.LockedNANDTrace.traceSlot
#print axioms PNP.DirectWire.LockedNANDTrace.occurrenceSlot
#print axioms PNP.DirectWire.LockedNANDTrace.sourceLockSlot
#print axioms PNP.DirectWire.LockedNANDTrace.traceLockSlot
#print axioms PNP.DirectWire.LockedNANDTrace.finalLockSlot
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierSlot.encode
#print axioms PNP.DirectWire.LockedNANDTrace.decodeCarrierSlot
#print axioms PNP.DirectWire.LockedNANDTrace.decodeCarrierSlot_primary
#print axioms PNP.DirectWire.LockedNANDTrace.decodeCarrierSlot_trace
#print axioms PNP.DirectWire.LockedNANDTrace.decodeCarrierSlot_occurrence
#print axioms PNP.DirectWire.LockedNANDTrace.decodeCarrierSlot_sourceLock
#print axioms PNP.DirectWire.LockedNANDTrace.decodeCarrierSlot_traceLock
#print axioms PNP.DirectWire.LockedNANDTrace.decodeCarrierSlot_finalLock
#print axioms PNP.DirectWire.LockedNANDTrace.decode_encode
#print axioms PNP.DirectWire.LockedNANDTrace.encode_decode
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierSlot.encode_injective
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierSeparation
#print axioms PNP.DirectWire.LockedNANDTrace.carrierSeparation
#print axioms PNP.DirectWire.LockedNANDTrace.finalLock_fresh
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.occurrenceAt
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.sourceLockAt
#print axioms PNP.DirectWire.LockedNANDTrace.liftOccurrenceCoordinate
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.restrict
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.restrict_primary
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.restrict_trace
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.restrict_occurrenceAt
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.restrict_sourceLockAt
#print axioms PNP.DirectWire.LockedNANDTrace.sourceCheck
#print axioms PNP.DirectWire.LockedNANDTrace.traceCheck
#print axioms PNP.DirectWire.LockedNANDTrace.boolEq_eq_true_iff
#print axioms PNP.DirectWire.LockedNANDTrace.sourceCheck_self
#print axioms PNP.DirectWire.LockedNANDTrace.sourceCheck_true_value
#print axioms PNP.DirectWire.LockedNANDTrace.traceCheck_self
#print axioms PNP.DirectWire.LockedNANDTrace.traceCheck_true_value
#print axioms PNP.DirectWire.LockedNANDTrace.gateChecks
#print axioms PNP.DirectWire.LockedNANDTrace.gateChecks_length
#print axioms PNP.DirectWire.LockedNANDTrace.distinguishedChecks
#print axioms PNP.DirectWire.LockedNANDTrace.distinguishedChecks_length
#print axioms PNP.DirectWire.LockedNANDTrace.tracePredicate
#print axioms PNP.DirectWire.LockedNANDTrace.coherentOccurrences
#print axioms PNP.DirectWire.LockedNANDTrace.coherentOccurrences_snoc_earlier
#print axioms PNP.DirectWire.LockedNANDTrace.coherentOccurrences_snoc_left
#print axioms PNP.DirectWire.LockedNANDTrace.coherentOccurrences_snoc_right
#print axioms PNP.DirectWire.LockedNANDTrace.coherentExtension
#print axioms PNP.DirectWire.LockedNANDTrace.CarrierValuation.ext
#print axioms PNP.DirectWire.LockedNANDTrace.coherentExtension_primary
#print axioms PNP.DirectWire.LockedNANDTrace.coherentExtension_trace
#print axioms PNP.DirectWire.LockedNANDTrace.coherentExtension_sourceLockAt
#print axioms PNP.DirectWire.LockedNANDTrace.coherentExtension_traceLock
#print axioms PNP.DirectWire.LockedNANDTrace.coherentExtension_finalLock
#print axioms PNP.DirectWire.LockedNANDTrace.coherentExtension_snoc_restrict
#print axioms PNP.DirectWire.LockedNANDTrace.gateChecks_coherent
#print axioms PNP.DirectWire.LockedNANDTrace.distinguishedChecks_coherentExtension
#print axioms PNP.DirectWire.LockedNANDTrace.tracePredicate_coherentExtension
#print axioms PNP.DirectWire.LockedNANDTrace.trace_sound_of_predicate_true
#print axioms PNP.DirectWire.LockedNANDTrace.traceEquivalence
#print axioms PNP.DirectWire.LockedNANDTrace.satisfiable_iff_trace_extension
#print axioms PNP.DirectWire.LockedNANDTrace.exists_coherent_trace
