import PNP.LockedNANDGlobalSemanticThreshold

#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidate_final_nonconstant_of_satisfiable
#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidate_final_notPositiveProjection_of_satisfiable
#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidate_final_distinctFromBaseline_of_satisfiable
#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidate_satisfiableFinalConditions
#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidateThresholdPremises
#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidate_referenceMinimum_bounds_of_satisfiable
#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidate_residualSlack_le_four
#print axioms PNP.DirectWire.LockedNANDGlobalCandidates.fullCandidate_satisfiable_iff_referenceMinimum_ge_succ
