import PNP.LockedNANDDirect

#print axioms PNP.DirectWire.Source.hasNoConstant
#print axioms PNP.DirectWire.Gate.hasNoConstant
#print axioms PNP.DirectWire.Program.hasNoConstant
#print axioms PNP.DirectWire.emptyValuation
#print axioms PNP.DirectWire.EqualityMacroOutputs.toValuation
#print axioms PNP.DirectWire.ConstantOneMacroOutputs.toValuation
#print axioms PNP.DirectWire.ConstantZeroMacroOutputs.toValuation
#print axioms PNP.DirectWire.TraceMacroOutputs.toValuation
#print axioms PNP.DirectWire.PrefixAndOutputs.toValuation
#print axioms PNP.DirectWire.exposeAllGates
#print axioms PNP.DirectWire.exposeAllGates_program
#print axioms PNP.DirectWire.exposeAllGates_source
#print axioms PNP.DirectWire.equalityDirectProgram
#print axioms PNP.DirectWire.equalityDirect
#print axioms PNP.DirectWire.equalityDirect_size
#print axioms PNP.DirectWire.equalityDirect_output_source
#print axioms PNP.DirectWire.equalityDirect_semantics
#print axioms PNP.DirectWire.equalityDirect_no_internal_constants
#print axioms PNP.DirectWire.constantOneDirectProgram
#print axioms PNP.DirectWire.constantOneDirect
#print axioms PNP.DirectWire.constantOneDirect_size
#print axioms PNP.DirectWire.constantOneDirect_output_source
#print axioms PNP.DirectWire.constantOneDirect_semantics
#print axioms PNP.DirectWire.constantOneDirect_no_internal_constants
#print axioms PNP.DirectWire.constantZeroDirectProgram
#print axioms PNP.DirectWire.constantZeroDirect
#print axioms PNP.DirectWire.constantZeroDirect_size
#print axioms PNP.DirectWire.constantZeroDirect_output_source
#print axioms PNP.DirectWire.constantZeroDirect_semantics
#print axioms PNP.DirectWire.constantZeroDirect_no_internal_constants
#print axioms PNP.DirectWire.traceDirectProgram
#print axioms PNP.DirectWire.traceDirect
#print axioms PNP.DirectWire.traceDirect_size
#print axioms PNP.DirectWire.traceDirect_output_source
#print axioms PNP.DirectWire.traceDirect_semantics
#print axioms PNP.DirectWire.traceDirect_no_internal_constants
#print axioms PNP.DirectWire.prefixAndDirectProgram
#print axioms PNP.DirectWire.prefixAndDirect
#print axioms PNP.DirectWire.prefixAndDirect_size
#print axioms PNP.DirectWire.prefixAndDirect_output_source
#print axioms PNP.DirectWire.prefixAndDirect_semantics
#print axioms PNP.DirectWire.prefixAndDirect_no_internal_constants
#print axioms PNP.DirectWire.finalConjunctionDirectProgram
#print axioms PNP.DirectWire.finalConjunctionDirect
#print axioms PNP.DirectWire.finalConjunctionDirect_size
#print axioms PNP.DirectWire.finalConjunctionDirect_output_source
#print axioms PNP.DirectWire.finalConjunctionDirect_semantics
#print axioms PNP.DirectWire.finalConjunctionDirect_no_internal_constants
