import PNP

#print axioms PNP.DirectWire.natSub_lt_right_of_lt_add
#print axioms PNP.DirectWire.natAdd_sub_of_le
#print axioms PNP.DirectWire.natAdd_sub_cancel_left
#print axioms PNP.DirectWire.splitFin
#print axioms PNP.DirectWire.splitFin_left
#print axioms PNP.DirectWire.splitFin_right
#print axioms PNP.DirectWire.finSum_decompose
#print axioms PNP.DirectWire.Source.renameInputs
#print axioms PNP.DirectWire.Source.weakenGates
#print axioms PNP.DirectWire.Source.shiftGates
#print axioms PNP.DirectWire.Source.substituteInputs
#print axioms PNP.DirectWire.Gate.renameInputs
#print axioms PNP.DirectWire.Gate.substituteInputs
#print axioms PNP.DirectWire.Program.renameInputs
#print axioms PNP.DirectWire.Program.appendSubstituted
#print axioms PNP.DirectWire.DirectWireWord.renameInputs
#print axioms PNP.DirectWire.Source.eval_renameInputs
#print axioms PNP.DirectWire.Gate.eval_renameInputs
#print axioms PNP.DirectWire.Source.eval_weakenGates
#print axioms PNP.DirectWire.Source.eval_shiftGates
#print axioms PNP.DirectWire.Source.eval_substituteInputs
#print axioms PNP.DirectWire.Program.eval_renameInputs
#print axioms PNP.DirectWire.Program.size_renameInputs
#print axioms PNP.DirectWire.renameInputs_semantics
#print axioms PNP.DirectWire.Program.size_appendSubstituted
#print axioms PNP.DirectWire.Program.eval_appendSubstituted_prefix
#print axioms PNP.DirectWire.Program.eval_appendSubstituted_suffix
#print axioms PNP.DirectWire.sequentialProgram
#print axioms PNP.DirectWire.sequentialWord
#print axioms PNP.DirectWire.sequentialProgram_size
#print axioms PNP.DirectWire.sequential_semantics
#print axioms PNP.DirectWire.Candidate.sequential
#print axioms PNP.DirectWire.Candidate.sequential_program
#print axioms PNP.DirectWire.Candidate.sequential_size
#print axioms PNP.DirectWire.Candidate.ofDirectWireWord_semantics
#print axioms PNP.DirectWire.Candidate.sequential_semantics
#print axioms PNP.DirectWire.Candidate.renameInputs
#print axioms PNP.DirectWire.Candidate.renameInputs_size
#print axioms PNP.DirectWire.Candidate.renameInputs_semantics
#print axioms PNP.DirectWire.withBypassWord
#print axioms PNP.DirectWire.withBypassWord_support_source
#print axioms PNP.DirectWire.withBypassWord_bypass_source
#print axioms PNP.DirectWire.Candidate.withBypass
#print axioms PNP.DirectWire.Candidate.withBypass_size
#print axioms PNP.DirectWire.Candidate.withBypass_semantics
#print axioms PNP.DirectWire.FramedContext
#print axioms PNP.DirectWire.FramedContext.plug
#print axioms PNP.DirectWire.FramedContext.plug_size
#print axioms PNP.DirectWire.FramedContext.plug_semantics
#print axioms PNP.DirectWire.compatibleReplacement_framed
