import PNP

#print axioms PNP.DirectWire.mem_map_of_mem
#print axioms PNP.DirectWire.mem_flatMap_of_mem
#print axioms PNP.DirectWire.allFin
#print axioms PNP.DirectWire.mem_allFin
#print axioms PNP.DirectWire.allSources
#print axioms PNP.DirectWire.mem_allSources
#print axioms PNP.DirectWire.allGates
#print axioms PNP.DirectWire.mem_allGates
#print axioms PNP.DirectWire.allPrograms
#print axioms PNP.DirectWire.mem_allPrograms
#print axioms PNP.DirectWire.OutputWord
#print axioms PNP.DirectWire.OutputWord.get
#print axioms PNP.DirectWire.OutputWord.toDirectWireWord
#print axioms PNP.DirectWire.OutputWord.get_cons_zero
#print axioms PNP.DirectWire.OutputWord.get_cons_succ
#print axioms PNP.DirectWire.OutputWord.toDirectWireWord_pointwise
#print axioms PNP.DirectWire.allOutputWords
#print axioms PNP.DirectWire.mem_allOutputWords
#print axioms PNP.DirectWire.OutputWord.eq_nil
#print axioms PNP.DirectWire.OutputWord.ofFn
#print axioms PNP.DirectWire.OutputWord.get_ofFn
#print axioms PNP.DirectWire.Candidate
#print axioms PNP.DirectWire.Candidate.directWireWord
#print axioms PNP.DirectWire.Candidate.semantics
#print axioms PNP.DirectWire.Candidate.ofDirectWireWord
#print axioms PNP.DirectWire.allCandidates
#print axioms PNP.DirectWire.mem_allCandidates
#print axioms PNP.DirectWire.Candidate.ofDirectWireWord_program
#print axioms PNP.DirectWire.Candidate.ofDirectWireWord_pointwise
#print axioms PNP.DirectWire.exactWidthEnumeration_complete
#print axioms PNP.DirectWire.BoundedCandidate
#print axioms PNP.DirectWire.allBoundedCandidates
#print axioms PNP.DirectWire.mem_allBoundedCandidates
#print axioms PNP.DirectWire.boundedCandidateOfLE
#print axioms PNP.DirectWire.mem_allBoundedCandidates_of_le
#print axioms PNP.DirectWire.boundedDirectInterface_complete
#print axioms PNP.DirectWire.Candidate.program_size_eq_gateCount
#print axioms PNP.DirectWire.Candidate.directWire_size_eq_gateCount
#print axioms PNP.DirectWire.Candidate.semantics_is_typed
#print axioms PNP.DirectWire.NANDEnumeratorCertificate
#print axioms PNP.DirectWire.nandEnumeratorCertificate
