import PNP.PCCMinCheckedPacketPkgCRestorationCoverageBN6BCELRoute

#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCRestorationCoverageBN6BCELSourceData
#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCRestorationCoverageBN6BCELRouteOrZeroSlack
#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCRestorationCoverageBN6BCELSourceData.routeOrZeroSlack
#print axioms PNP.DirectWire.pccmin_checked_packet_pkgc_restoration_coverage_bn6_bcel_route_or_zeroslack_checked_complete
