import PNP.PCCMinCheckedPacketPkgCAmbientBN4ExtractionRoute

#print axioms PNP.DirectWire.TerminalPkgCAmbientBN4ExtractionOutcome
#print axioms PNP.DirectWire.classifyTerminalPkgCAmbientBN4Extraction
#print axioms PNP.DirectWire.classifyTerminalPkgCAmbientBN4Extraction_exhaustive
#print axioms PNP.DirectWire.TerminalPkgCComputedAmbientBN4ExtractionOutcome
#print axioms PNP.DirectWire.classifyTerminalPkgCComputedAmbientBN4Extraction
#print axioms PNP.DirectWire.classifyTerminalPkgCComputedAmbientBN4Extraction_exhaustive
#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCAmbientBN4SourceData
#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCAmbientBN4ExtractionRouteOrZeroSlack
#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCAmbientBN4SourceData.extractionRouteOrZeroSlack
#print axioms PNP.DirectWire.pccmin_checked_packet_pkgc_ambient_bn4_extraction_route_or_zeroslack_checked_complete
