import PNP.PCCMinCheckedPacketPkgCRestorationCoverageChargeDescent

#print axioms PNP.DirectWire.terminalBN4UnsignedChargeSize
#print axioms PNP.DirectWire.terminalBN4UnsignedChargeSize_append
#print axioms PNP.DirectWire.terminalBN4UnsignedChargeSize_perm
#print axioms PNP.DirectWire.terminalPkgCRestorationCoverageCancellationCellsForUnits_unsignedChargeSize
#print axioms PNP.DirectWire.TerminalPkgCSeparatingPair.restorationCoverageCancellation_unsignedChargeSize
#print axioms PNP.DirectWire.TerminalPkgCSeparatingPair.restorationCoverageCancellation_unsignedChargeSize_pos
#print axioms PNP.DirectWire.TerminalPkgCRestorationCoverageAmbientBN4Embedding.unsignedChargeSize_decomposition
#print axioms PNP.DirectWire.TerminalPkgCRestorationCoverageAmbientBN4Embedding.remainder_unsignedChargeSize_lt
#print axioms PNP.DirectWire.TerminalPkgCBN4ChargeRankContext
#print axioms PNP.DirectWire.TerminalPkgCBN4ChargeRankContext.rank
#print axioms PNP.DirectWire.TerminalPkgCRestorationCoverageAmbientBN4Embedding.chargeRank_lt
#print axioms PNP.DirectWire.TerminalPkgCRestorationCoverageAmbientBN4ChargeDescent
#print axioms PNP.DirectWire.TerminalPkgCRestorationCoverageAmbientBN4Embedding.chargeDescent
#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCRestorationCoverageChargeRouteOrZeroSlack
#print axioms PNP.DirectWire.PCCMinCheckedPacketPkgCRestorationCoverageBN6BCELSourceData.chargeRouteOrZeroSlack
#print axioms PNP.DirectWire.pccmin_checked_packet_pkgc_restoration_coverage_charge_route_or_zeroslack_checked_complete
