import PNP.PCCMinCheckedPacketBN6BCELDerivedFamily

#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELGroupedCells
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELGroupedCells.family
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELGroupedCells.family_carrier
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELGroupedCells.family_cutValue
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyHBData
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyHBData.bcelCarrier
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyHBData.bcelDefect
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyHBData.toBCELActivationData
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyHBData.family_carrier_eq_bcelCarrier
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyHBData.family_cutValue_eq_bcelDefect
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyRoute
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyRouteOrZeroSlack
#print axioms PNP.DirectWire.PCCMinCheckedPacketBN6BCELDerivedFamilyHBData.routeOrZeroSlackOfSilence
#print axioms PNP.DirectWire.pccmin_checked_packet_bn6_bcel_derived_family_route_or_zeroslack_checked_complete
