import PNP.ResidualTerminalPacketSelectorHandles

#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.PacketSelectorHandle
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint_mem_universe
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint_injective
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint_sublist_carrier
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint_large
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint_hasPayloadAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint_hasPacketSelectorSeedAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorFootprint_hasPacketPayloadSelectorAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.HasFinitePacketSelectorHandleAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.hasFinitePacketSelectorHandleAt_iff_payloadSelector
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.existsUnique_packetSelectorHandle_iff_payloadSelector
#print axioms PNP.DirectWire.TerminalPacketSelectorHandleConclusion
#print axioms PNP.DirectWire.TerminalPacketPayloadSelectorConclusion.selectorHandles
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.selectorHandles
#print axioms PNP.DirectWire.terminalBN6_packet_selector_handles
