import PNP.ResidualTerminalFiniteBCELPacketCarrierCoherence

#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate
#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.family_carrier_eq
#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.carrier_at_least_two
#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.no_positive_packet
#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.not_constant_activation
#print axioms PNP.terminal_finite_bcel_packet_carrier_coherent_checked_complete
