import PNP.ResidualTerminalPacketSelectorFaithfulnessRouting

#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessRoute
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.Valid
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.check
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.check_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.firstRoute
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.firstRoute_eq_none_of_check
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.check_eq_false_of_firstRoute
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFaithful
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRoute
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFaithful_eq_true_iff
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRoute_eq_none
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.checkPacketSelectorRoutesClear
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.checkPacketSelectorRoutesClear_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkPacketSelectorFaithfulnessBinding
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkPacketSelectorFaithfulnessBinding_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorHandleConclusion.existsHandle
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsPacketSelectorHandle
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsFaithfulHandle_of_routesClear
#print axioms PNP.DirectWire.terminalBN6_packet_selector_faithfulness_hb_contradiction
