import PNP.ResidualTerminalPacketSelectorFirstRouteSemantics

#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.FailureAt
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.firstRoute_eq_some_iff_failureAt
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.failureAt_unique
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.check_eq_false_iff_exists_failureAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFailureAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRoute_eq_some_iff_failureAt
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsFirstRouteFailure_of_computedTableSelectorSilence
#print axioms PNP.DirectWire.terminalBN6_packet_computed_faithfulness_hb_first_route_failure
