import PNP.ResidualTerminalPacketBudgetHBActivityBinding

#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.PacketBudgetHBActivityBound
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkPacketBudgetHBActivityBinding
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkPacketBudgetHBActivityBinding_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.packetBudget_eq_of_checkedHBActivityBinding
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.packetSelectorBudgetFirstRoute_ne_of_checkedHBActivityBinding
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsBudgetHBBoundFirstRouteFailure_of_selectorSilence
#print axioms PNP.DirectWire.terminalBN6_packet_budget_hb_activity_bound_first_route_failure
