import PNP.ResidualTerminalPacketSelectorCodec

#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.encodePacketSelectorHandle
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.decodePacketSelectorHandle
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.decodePacketSelectorHandle_encode
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.encodePacketSelectorHandle_injective
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.encodePacketSelectorHandle_length
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.encodePacketSelectorHandle_length_le_universe
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.decodePacketSelectorHandle_canonical
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.decodePacketSelectorHandle_payloadEvidence
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.IsEncodedPacketSelectorAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.HasEncodedPacketSelectorAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.hasEncodedPacketSelectorAt_iff_payloadSelector
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.existsUnique_encodedPacketSelector_iff_payloadSelector
#print axioms PNP.DirectWire.TerminalPacketEncodedSelectorConclusion
#print axioms PNP.DirectWire.TerminalPacketPayloadSelectorConclusion.selectorCodes
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.selectorCodes
#print axioms PNP.DirectWire.terminalBN6_packet_selector_codes
