import PNP.ResidualTerminalPacketSelectorFaithfulnessTable

#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorFaithfulness
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorFaithfulness_rankOf
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorFaithfulness_hnActive
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorFaithfulness_budgetActive
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorFaithfulness_claim
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorFaithfulness_faithful
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorFaithfulness_binding
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsFaithfulHandle_of_computedTable
#print axioms PNP.DirectWire.terminalBN6_packet_computed_faithfulness_hb_contradiction
