import PNP

#print axioms PNP.DirectWire.referenceMinimumImplementation_gateCount_eq_referenceMinimum
#print axioms PNP.DirectWire.referenceMinimumImplementation_equivalent
#print axioms PNP.DirectWire.referenceMinimumImplementation_isSemanticallyMinimum
#print axioms PNP.DirectWire.referenceMinimumImplementation_residualSlack_eq_zero
#print axioms PNP.DirectWire.referenceMinimumImplementation_strictEquivalentGain_of_residualSlack_pos
#print axioms PNP.DirectWire.residualSlack_pos_iff_exists_strictEquivalentGain
#print axioms PNP.DirectWire.residualSlack_eq_zero_iff_forall_not_strictEquivalentGain
#print axioms PNP.DirectWire.isSemanticallyMinimum_iff_forall_not_strictEquivalentGain
#print axioms PNP.DirectWire.StrictGainChain.end_residualSlack_eq_zero_of_no_strictEquivalentGain
#print axioms PNP.DirectWire.StrictGainChain.end_exactMinimumResult_of_no_strictEquivalentGain
#print axioms PNP.DirectWire.strictGainChainBool_end_residualSlack_eq_zero_of_no_strictEquivalentGain
#print axioms PNP.DirectWire.strictGainChainBool_end_exactMinimumResult_of_no_strictEquivalentGain
