import PNP.ResidualTerminalPacketRankRouteReflection

#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedRankDescent
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedRankDescent_fields
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedRankDescent_valid_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedRankDescent_failureAt_rank_iff_false
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedRankDescent_firstRoute_ne_some_rank
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedRankDescent_failureAt_descent_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedRankDescent_firstRoute_eq_some_descent_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.rankDescent_of_withComputedRankDescent_check
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadWithComputedRankDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFaithfulWithComputedRankDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRouteWithComputedRankDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFailureAtWithComputedRankDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRouteWithComputedRankDescent_eq_some_iff
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.computedRankDescent_firstRoute_ne_some_rank
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.not_rankDescent_of_computedRankDescent_firstRoute_descent
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorRankDescentFaithfulness
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorRankDescentFaithfulness_preserves
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorRankDescentFaithfulness_faithful
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsRankTagReflectedFirstRouteFailure_of_selectorSilence
#print axioms PNP.DirectWire.terminalBN6_packet_rank_tag_reflected_hb_first_route_failure
