import PNP.ResidualTerminalRankWF

#print axioms PNP.DirectWire.TerminalResidualRank
#print axioms PNP.DirectWire.TerminalResidualRank.mk
#print axioms PNP.DirectWire.TerminalResidualRank.witnessType
#print axioms PNP.DirectWire.TerminalResidualRank.spanType
#print axioms PNP.DirectWire.TerminalResidualRank.mode
#print axioms PNP.DirectWire.TerminalResidualRank.frontierDefect
#print axioms PNP.DirectWire.TerminalResidualRank.projectionDefect
#print axioms PNP.DirectWire.TerminalResidualRank.saturationDefect
#print axioms PNP.DirectWire.TerminalResidualRank.anchorCount
#print axioms PNP.DirectWire.TerminalResidualRank.chargeSize
#print axioms PNP.DirectWire.TerminalResidualRank.profileSize
#print axioms PNP.DirectWire.TerminalResidualRank.canonicalCode
#print axioms PNP.DirectWire.TerminalResidualRank.coordinates
#print axioms PNP.DirectWire.TerminalResidualRank.coordinates_mk
#print axioms PNP.DirectWire.TerminalResidualRank.coordinates_length
#print axioms PNP.DirectWire.terminalResidualRankWellFoundedRelation
#print axioms PNP.DirectWire.TerminalResidualRank.LexLT
#print axioms PNP.DirectWire.terminalResidualRankLTBool
#print axioms PNP.DirectWire.terminalResidualRankLTBool_eq_true_iff
#print axioms PNP.DirectWire.terminalResidualRankLTBool_eq_false_iff
#print axioms PNP.DirectWire.terminalResidualRankLexLT_wellFounded
#print axioms PNP.DirectWire.terminalResidualRank_accessible
#print axioms PNP.DirectWire.terminalResidualRank_induction
#print axioms PNP.DirectWire.terminalResidualRank_witnessType_lt
#print axioms PNP.DirectWire.terminalResidualRank_spanType_lt
#print axioms PNP.DirectWire.terminalResidualRank_mode_lt
#print axioms PNP.DirectWire.terminalResidualRank_frontierDefect_lt
#print axioms PNP.DirectWire.terminalResidualRank_projectionDefect_lt
#print axioms PNP.DirectWire.terminalResidualRank_saturationDefect_lt
#print axioms PNP.DirectWire.terminalResidualRank_anchorCount_lt
#print axioms PNP.DirectWire.terminalResidualRank_chargeSize_lt
#print axioms PNP.DirectWire.terminalResidualRank_profileSize_lt
#print axioms PNP.DirectWire.terminalResidualRank_canonicalCode_lt
#print axioms PNP.DirectWire.TerminalResidualRankDescent
#print axioms PNP.DirectWire.TerminalResidualRankDescent.before
#print axioms PNP.DirectWire.TerminalResidualRankDescent.after
#print axioms PNP.DirectWire.TerminalResidualRankDescent.decreasing
#print axioms PNP.DirectWire.TerminalResidualRankDescent.Sound
#print axioms PNP.DirectWire.TerminalResidualRankDescent.sound
