import PNP.ResidualTerminalHBActiveDependencyClosure

#print axioms PNP.DirectWire.TerminalPacketTypedRealizerEnvironment.hbActive
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.ActiveDependencyClosed
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.checkActiveDependencyClosed
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.checkActiveDependencyClosed_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.NoOutcomeActiveClosureValid
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.checkNoOutcomeActiveClosure
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.checkNoOutcomeActiveClosure_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.noActive_of_noOutcomeActiveClosure
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.hnActive_eq_false
#print axioms PNP.DirectWire.TerminalPacketHBDependencyTable.budgetActive_eq_false
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerClaim.HBActiveClosureSound
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerEvidence.hbActiveClosureSound
#print axioms PNP.DirectWire.terminalBN6_packet_typed_realizer_hb_active_dependency_closure_contract
