import PNP.ZeroSlack

#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.terminalDefect
#print axioms PNP.TerminalFiniteBCELPacketActivationCoherent
#print axioms PNP.TerminalFiniteBCELPacketActivationObstruction
#print axioms PNP.checkTerminalFiniteBCELPacketActivationCoherence
#print axioms PNP.checkTerminalFiniteBCELPacketActivationCoherence_eq_true_iff
#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.activation_coherent_mapped_cut_equation
#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.not_activation_coherent
#print axioms PNP.classifyTerminalFiniteBCELPacketActivationObstruction
#print axioms PNP.TerminalFiniteBCELPacketCarrierCoherenceCertificate.activation_coherence_check_eq_false
#print axioms PNP.terminal_finite_bcel_packet_activation_obstruction_checked_complete
#print axioms PNP.ZeroSlackCertificate.bcelPacketActivationObstruction
#print axioms PNP.zeroslack_bcel_packet_activation_obstruction_checked_complete
