import PNP.ResidualTerminalPacketSelectorFirstRouteOutcome

#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.firstRoute_eq_none_iff_check_eq_true
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.exists_firstRoute_iff_check_eq_false
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRoute_eq_none_iff
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.exists_packetSelectorPayloadFirstRoute_iff
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsFaithfulOrFirstRoute
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsFirstRoute_of_computedTableSelectorSilence
#print axioms PNP.DirectWire.terminalBN6_packet_computed_faithfulness_hb_first_route
