import PNP.ResidualTerminalPkgCAmbientBN4ResidualReduction

#print axioms PNP.DirectWire.terminalBN4ResidualCells_add_common
#print axioms PNP.DirectWire.TerminalPkgCAmbientBN4LedgerEmbedding.residualCells_eq_remainder
#print axioms PNP.DirectWire.terminalBN4ResidualLedgerOver
#print axioms PNP.DirectWire.TerminalPkgCAmbientBN4LedgerEmbedding.residualLedgerOver_eq_remainder
#print axioms PNP.DirectWire.TerminalPkgCAmbientBN4LedgerEmbedding.remainderKey_mem_ambientCanonicalKeys
#print axioms PNP.DirectWire.TerminalPkgCAmbientBN4LedgerEmbedding.canonicalResidualLedger_eq_remainder
#print axioms PNP.DirectWire.TerminalPkgCAmbientBN4LedgerEmbedding.canonicalResidualLedger_empty_of_remainder_empty
#print axioms PNP.DirectWire.TerminalPkgCAmbientBN4ResidualReductionOutcome
#print axioms PNP.DirectWire.classifyTerminalPkgCAmbientBN4ResidualReduction
#print axioms PNP.DirectWire.classifyTerminalPkgCAmbientBN4ResidualReduction_exhaustive
#print axioms PNP.DirectWire.TerminalPkgCComputedAmbientBN4ResidualReduction
#print axioms PNP.DirectWire.TerminalPkgCComputedAmbientBN4Cancellation.residualReduction
#print axioms PNP.DirectWire.TerminalPkgCComputedAmbientBN4Cancellation.residualLedger_empty_of_remainder_empty
