import PNP.ResidualTerminalPacketSemanticHNActivityBinding

#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.PacketSemanticFieldsAgree
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.PacketSemanticHNActivityBound
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkPacketSemanticHNActivityBinding
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkPacketSemanticHNActivityBinding_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.packetSemanticFieldsAgree_of_checkedHNActivityBinding
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.packetSelectorSemanticFirstRoutes_ne_of_checkedHNActivityBinding
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsSemanticHNBudgetBoundDescentFailure_of_selectorSilence
#print axioms PNP.DirectWire.terminalBN6_packet_semantic_hn_activity_bound_descent_failure
