import PNP.ResidualTerminalPacketSelectorPayloadRealization

#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorCell
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorCell_mem_groups
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorCell_footprint
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadAtom
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadAtom_mem
#print axioms PNP.DirectWire.TerminalPacketSelectorPayloadRealization
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadRealization
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.realizePacketSelectorPayload
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.realizePacketSelectorPayload_eq_none_iff
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.decodePacketSelectorHandle_eq_some_of_realize
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.exists_realizePacketSelectorPayload_iff
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.exists_realizePacketSelectorPayload_encode
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.realizePacketSelectorPayload_sound
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.IsRealizedPacketSelectorAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.HasRealizedPacketSelectorAt
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.isRealizedPacketSelectorAt_iff_encoded
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.hasRealizedPacketSelectorAt_iff_payloadSelector
#print axioms PNP.DirectWire.TerminalPacketRealizedSelectorConclusion
#print axioms PNP.DirectWire.TerminalPacketEncodedSelectorConclusion.selectorPayloadRealizations
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.selectorPayloadRealizations
#print axioms PNP.DirectWire.terminalBN6_packet_selector_payload_realizations
