import PNP.ResidualTerminalHBExecutableSelectorSilenceInduction

#print axioms PNP.DirectWire.TerminalPacketTypedRealizerClaim.isBotBool
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerClaim.isBotBool_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkSelectorSilent
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkSelectorSilent_eq_true_iff
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.checkFaithful_of_selectorSilent
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.claim_eq_bot_of_selectorSilent
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.noFaithful_of_selectorSilent
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.noFaithfulAtOrBelow_of_selectorSilent
#print axioms PNP.DirectWire.terminalBN6_packet_typed_realizer_hb_selector_silence_induction_contract
