import PNP.ResidualTerminalPacketBudgetNoLowerComposition

#print axioms PNP.DirectWire.TerminalPacketBudgetNoLowerAccepted
#print axioms PNP.DirectWire.checkTerminalPacketBudgetNoLowerComposition
#print axioms PNP.DirectWire.checkTerminalPacketBudgetNoLowerComposition_eq_true_iff
#print axioms PNP.DirectWire.terminal_packet_budget_no_lower_composition_excludes_gain_and_packet
#print axioms PNP.DirectWire.checkTerminalPacketBudgetNoLowerComposition_eq_false_of_feasible_gain
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.checkTerminalPacketBudgetNoLowerComposition_eq_false
