import PNP.ResidualTerminalPacketDescentRouteReflection

#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedDescent
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedDescent_fields
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedDescent_valid_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedDescent_failureAt_descent_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.withComputedDescent_firstRoute_eq_some_descent_iff
#print axioms PNP.DirectWire.TerminalPacketSelectorFaithfulnessPayload.rankDescent_of_withComputedDescent_check
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadWithComputedDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFaithfulWithComputedDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRouteWithComputedDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFailureAtWithComputedDescent
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.packetSelectorPayloadFirstRouteWithComputedDescent_eq_some_iff
#print axioms PNP.DirectWire.TerminalBN6GroupedFamily.not_rankDescent_of_computed_firstRoute_descent
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorDescentFaithfulness
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorDescentFaithfulness_preserves
#print axioms PNP.DirectWire.TerminalPacketTypedRealizerTable.withComputedPacketSelectorDescentFaithfulness_faithful
#print axioms PNP.DirectWire.TerminalBN6PacketConclusion.existsRankReflectedFirstRouteFailure_of_selectorSilence
#print axioms PNP.DirectWire.terminalBN6_packet_rank_reflected_hb_first_route_failure
