import PNP

/- Exact root-import axiom audit for complete structural-action integration. -/

#print axioms PNP.DirectWire.StructuralReindexing.result_gate_level
#print axioms PNP.DirectWire.StructuralReindexing.result_source_level
#print axioms PNP.DirectWire.StructuralReindexing.result_output_level
#print axioms PNP.DirectWire.WireCarrier.reindex_exposed
#print axioms PNP.DirectWire.WireCarrier.reindex_gateCount
#print axioms PNP.DirectWire.WireCarrier.reindex_backward_forward
#print axioms PNP.DirectWire.WireCarrier.reindex_forward_backward
#print axioms PNP.DirectWire.WireCarrier.reindex_output
#print axioms PNP.DirectWire.WireCarrier.reindex_field
#print axioms PNP.DirectWire.WireCarrier.reindex_field_source
#print axioms PNP.DirectWire.WireCarrier.reindex_exposed_level
#print axioms PNP.DirectWire.WireCarrier.reindex_output_level
#print axioms PNP.DirectWire.WireCarrier.reindex_field_level
#print axioms PNP.DirectWire.WireCarrier.reindex_causalBounds
#print axioms PNP.DirectWire.WireObligationHistory.State.reindex_pending
#print axioms PNP.DirectWire.WireObligationHistory.State.reindex_charged
#print axioms PNP.DirectWire.WireObligationHistory.State.reindex_removed
#print axioms PNP.DirectWire.WireObligationHistory.State.reindex_gateCount
#print axioms PNP.DirectWire.WireObligationHistory.State.reindex_causalInvariant
#print axioms PNP.DirectWire.WireStructuralState.execute_isSome
#print axioms PNP.DirectWire.WireStructuralState.execute_failure_iff
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_origin
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_origin_forward
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_origin_injective
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_live_members
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_not_allocated
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_charged
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_removed
#print axioms PNP.DirectWire.WireStructuralState.Receipt.ownership_wellFormed
#print axioms PNP.DirectWire.WireStructuralState.Receipt.physical_ownership
#print axioms PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_origin
#print axioms PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_charged
#print axioms PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_removed
#print axioms PNP.DirectWire.WireOpenProgram.orderEvents_success_iff
#print axioms PNP.DirectWire.WireOpenProgram.orderEvents_failure_iff
#print axioms PNP.DirectWire.WireOpenProgram.execute_failed_tail
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.full_output
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.full_field
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.creation_lifecycle
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.executed_count
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.executed_identities_nodup
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.causalInvariant
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.physical_ownership
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.ownership_origin_injective
#print axioms PNP.DirectWire.WireOpenProgram.CompiledProgram.ownership_charge_origin
#print axioms PNP.DirectWire.WireOpenProgram.compile_exists_iff
#print axioms PNP.DirectWire.WireOpenProgram.compile_none_iff
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.records_source
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.proper_support
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.output
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.field
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.charge_accounting
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictGain
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictResidualDescent
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.physical_ownership
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.closed_ledger
#print axioms PNP.DirectWire.WireOpenCertificate.CheckedCertificate.creation_lifecycle
#print axioms PNP.DirectWire.WireOpenCertificate.verify_exists_iff
#print axioms PNP.DirectWire.WireOpenCertificate.verify_sound
#print axioms PNP.DirectWire.WireOpenCertificate.verify_decode_none
#print axioms PNP.DirectWire.WireOpenCertificate.verify_program_none
#print axioms PNP.DirectWire.WireOpenCertificate.verify_not_proper
#print axioms PNP.DirectWire.WireOpenCertificate.verify_no_gain
