import PNP

#print axioms PNP.DependencyScheduler.ReadyStep.remaining_lt
#print axioms PNP.DependencyScheduler.Schedule.at_injective
#print axioms PNP.DependencyScheduler.Schedule.order_complete
#print axioms PNP.DependencyScheduler.Schedule.order_length
#print axioms PNP.DependencyScheduler.Schedule.order_nodup
#print axioms PNP.DependencyScheduler.Schedule.wellFounded
#print axioms PNP.DependencyScheduler.Stop.complete_of_wellFounded
#print axioms PNP.DependencyScheduler.Stop.unresolved_predecessor
#print axioms PNP.DependencyScheduler.compile_failure_iff
#print axioms PNP.DependencyScheduler.compile_success_iff
#print axioms PNP.DirectWire.WireObligationHistory.State.cancel_full_value
#print axioms PNP.DirectWire.WireObligationHistory.State.cancel_gateCount
#print axioms PNP.DirectWire.WireObligationHistory.State.closed_field
#print axioms PNP.DirectWire.WireObligationHistory.State.create_gateCount
#print axioms PNP.DirectWire.WireObligationHistory.State.create_source_snapshot
#print axioms PNP.DirectWire.WireObligationHistory.State.currentAgreement
#print axioms PNP.DirectWire.WireObligationHistory.State.normalize_gate_balance
#print axioms PNP.DirectWire.WireObligationHistory.State.restore_full_value
#print axioms PNP.DirectWire.WireObligationHistory.State.restore_gate_charge
#print axioms PNP.DirectWire.WireObligationHistory.OrderedEvents.identities_nodup
#print axioms PNP.DirectWire.WireObligationHistory.OrderedEvents.order_complete
#print axioms PNP.DirectWire.WireObligationHistory.OrderedEvents.order_length
#print axioms PNP.DirectWire.WireObligationHistory.OrderedEvents.order_nodup
#print axioms PNP.DirectWire.WireObligationHistory.completeReferences_iff
#print axioms PNP.DirectWire.WireObligationHistory.graph_dependency_iff
#print axioms PNP.DirectWire.WireObligationHistory.orderEvents_failure_iff
#print axioms PNP.DirectWire.WireObligationHistory.orderEvents_success_iff
#print axioms PNP.DirectWire.WireObligationHistory.uniqueIDs_iff
#print axioms PNP.DirectWire.WireObligationHistory.ClosedHistory.creation_lifecycle
#print axioms PNP.DirectWire.WireObligationHistory.ClosedHistory.dependency_before
#print axioms PNP.DirectWire.WireObligationHistory.ClosedHistory.executed_count
#print axioms PNP.DirectWire.WireObligationHistory.ClosedHistory.executed_identities_nodup
#print axioms PNP.DirectWire.WireObligationHistory.ClosedHistory.full_field
#print axioms PNP.DirectWire.WireObligationHistory.ClosedHistory.full_output
#print axioms PNP.DirectWire.WireObligationHistory.ClosedHistory.gate_balance
#print axioms PNP.DirectWire.WireObligationHistory.Execution.creationsClosed_of_finalClosed
#print axioms PNP.DirectWire.WireObligationHistory.Execution.pending_persists_or_discharged
#print axioms PNP.DirectWire.WireObligationHistory.Execution.record_identities
#print axioms PNP.DirectWire.WireObligationHistory.Execution.total_charge
#print axioms PNP.DirectWire.WireObligationHistory.Execution.total_removed
#print axioms PNP.DirectWire.WireObligationHistory.State.isClosed_sound
#print axioms PNP.DirectWire.WireObligationHistory.Transition.charged_eq
#print axioms PNP.DirectWire.WireObligationHistory.Transition.created_pending
#print axioms PNP.DirectWire.WireObligationHistory.Transition.dischargeRecord_binding
#print axioms PNP.DirectWire.WireObligationHistory.Transition.pending_persists_or_discharged
#print axioms PNP.DirectWire.WireObligationHistory.Transition.removed_eq
