/-
Copyright (c) 2026 PNP Labs.

This file is the Lean bridge for the PNP proof-certificate stack.
It intentionally formalizes the theorem boundary, not the entire custom PCC
checker.  The remaining trust base is represented by fields of
`CheckerTrustModel`, so Lean users can see exactly which bridge assumptions
are still external to this formalization pass.
-/

import PNP.PCCMin
import PNP.SAT

namespace PNP

/-- The executable checker verdict. -/
inductive Verdict where
  | accept
  | reject
  deriving DecidableEq, Repr

/-- Canonical identifier for the typed package generated by this Lean bridge. -/
def generatedPCCPackId : String := "PNP-TYPED-PCCMIN-LOOP-0"

/-- A generated proof-carrying package contains the exact proof-bearing PCCMin
loop certificate consumed by the active bridge.  String metadata is not proof
authority. -/
structure PCCPack where
  id : String
  loopCertificate : PCCMinLoopCertificate

/-- Transparent typed packaging for an explicit PCCMin loop certificate.  This
does not construct the certificate. -/
def GeneratePCCPack (loop : PCCMinLoopCertificate) : PCCPack :=
  { id := generatedPCCPackId
    loopCertificate := loop }

/-- The typed structural checker accepts exactly the canonical package
identifier.  The proof-bearing loop certificate is enforced by `PCCPack`'s
type rather than interpreted from a string or caller-supplied success flag. -/
def CheckPCCPackexp (pack : PCCPack) : Verdict :=
  if pack.id = generatedPCCPackId then Verdict.accept else Verdict.reject

/-- Transparent generation always produces the canonical accepted identifier. -/
@[simp] theorem check_generated_pcc_pack_exp_accepts
    (loop : PCCMinLoopCertificate) :
    CheckPCCPackexp (GeneratePCCPack loop) = Verdict.accept := by
  simp [CheckPCCPackexp, GeneratePCCPack]

/-- Typed generation preserves the supplied proof-bearing loop certificate
exactly. -/
@[simp] theorem generated_pcc_pack_loop_certificate_exact
    (loop : PCCMinLoopCertificate) :
    (GeneratePCCPack loop).loopCertificate = loop := rfl

/-- A package with a noncanonical identifier is rejected. -/
theorem check_pcc_pack_exp_rejects_mismatched_id
    (pack : PCCPack)
    (h : pack.id ≠ generatedPCCPackId) :
    CheckPCCPackexp pack = Verdict.reject := by
  simp [CheckPCCPackexp, h]

/-- Complete checked surface for typed package generation and reflection. -/
theorem typed_pccpack_reflection_checked_complete
    (loop : PCCMinLoopCertificate) :
    CheckPCCPackexp (GeneratePCCPack loop) = Verdict.accept ∧
      (GeneratePCCPack loop).loopCertificate = loop ∧
      ∀ pack : PCCPack,
        pack.id ≠ generatedPCCPackId →
          CheckPCCPackexp pack = Verdict.reject := by
  exact ⟨check_generated_pcc_pack_exp_accepts loop,
    generated_pcc_pack_loop_certificate_exact loop,
    check_pcc_pack_exp_rejects_mismatched_id⟩

/-- The accepted generated-package proposition for one explicit proof-bearing
loop certificate. -/
def AcceptedGeneratedPackage (loop : PCCMinLoopCertificate) : Prop :=
  CheckPCCPackexp (GeneratePCCPack loop) = Verdict.accept

/-- Every explicitly supplied loop certificate is accepted after transparent
typed packaging. -/
@[simp] theorem accepted_generated_package
    (loop : PCCMinLoopCertificate) : AcceptedGeneratedPackage loop :=
  check_generated_pcc_pack_exp_accepts loop

/-- The explicit trust model for this Lean bridge.

This pass factors the checker-soundness route through an explicitly supplied,
typed PCCMin loop certificate and rank-ordered ZeroSlack oracle certificate.
Transparent package generation and structural checking preserve that exact
certificate, so no caller reflection field remains.  The local locked NAND
macro truth laws and the local prefix-conjunction semantics are discharged
separately by `lockedNANDMacroCertificate` and
`lockedNANDPrefixCertificate`. The sole remaining field is `satHard`: SAT is
NP-hard for the witness-model reduction relation.

The report-facing SAT, locked-NAND, and residual-band languages now reuse the
concrete bitstring predicates.  Their checked all-input or identity polynomial
reductions are compiled directly, so neither reduction remains caller trust.
-/
structure CheckerTrustModel where
  satHard : SATHard

/-- An accepted typed package gives residual-band exact minimization in P
through the exact explicitly supplied PCCMin loop certificate. -/
theorem accepted_generated_package_implies_residual_band_in_p
    (loop : PCCMinLoopCertificate)
    (_h : AcceptedGeneratedPackage loop) :
    PClass ResidualBandExactMinimization :=
  residual_band_in_p_from_pccmin_loop_certificate
    (GeneratePCCPack loop).loopCertificate

/-- The accepted package gives locked NAND threshold in P through residual-band
exact minimization. -/
theorem accepted_generated_package_implies_locked_nand_in_p
    (loop : PCCMinLoopCertificate)
    (h : AcceptedGeneratedPackage loop) : PClass LockedNANDThreshold :=
  locked_nand_in_p_from_residual_band_in_p
    (accepted_generated_package_implies_residual_band_in_p loop h)

/-- The accepted package gives SAT in P through residual-band minimization and
the locked NAND threshold route. -/
theorem accepted_generated_package_implies_sat_in_p
    (loop : PCCMinLoopCertificate)
    (h : AcceptedGeneratedPackage loop) : PClass SAT :=
  sat_in_p_from_locked_nand_in_p
    (accepted_generated_package_implies_locked_nand_in_p loop h)

/-- Formal version of the report's bridge: existence of an explicit loop
certificate whose transparently generated typed package accepts implies
`P = NP`, relative to the remaining concrete SAT-hardness trust field. -/
theorem accepted_generated_package_implies_p_eq_np
    (T : CheckerTrustModel)
    (loop : PCCMinLoopCertificate)
    (h : AcceptedGeneratedPackage loop) : PEqualsNP :=
  sat_np_complete_and_sat_in_p_implies_p_eq_np
    (sat_np_complete_from_hardness T.satHard)
    (accepted_generated_package_implies_sat_in_p loop h)

/-- Report-facing antecedent.  The proof-bearing loop certificate must exist
explicitly; package generation and checking do not manufacture it. -/
def FinalReportAntecedent : Prop :=
  ∃ loop : PCCMinLoopCertificate, AcceptedGeneratedPackage loop

/-- Report-facing consequent. -/
def FinalReportConsequent : Prop := PEqualsNP

/-- The final report bridge as a theorem in Lean. -/
theorem final_report_bridge
    (T : CheckerTrustModel) :
    FinalReportAntecedent → FinalReportConsequent :=
  fun h => by
    rcases h with ⟨loop, accepted⟩
    exact accepted_generated_package_implies_p_eq_np T loop accepted

/-- A small machine-readable summary object for downstream Lean files. -/
structure LeanBridgeSummary where
  reportCoordinate : String
  antecedentName : String
  consequentName : String
  bridgeTheoremName : String
  dischargedByLean : List String
  externalTrustBase : List String

/-- Summary for the Lean bridge pass. -/
def leanBridgeSummary : LeanBridgeSummary :=
  { reportCoordinate := "PNP-FINAL-PROOF-REPORT-7072F8D"
    antecedentName := "exists loop, CheckPCCPackexp (GeneratePCCPack loop) = Verdict.accept"
    consequentName := "PClass = NPClass"
    bridgeTheoremName := "final_report_bridge"
    dischargedByLean := [
      "Concrete finite-pipeline theorem: P ⊆ NP by embedding a deterministic decider as a bounded-certificate verifier",
      "Concrete finite-pipeline theorem: polynomial reductions transport P membership by composing proved function and decision programs",
      "Lean theorem: concrete NP-complete language in P implies mutual inclusion of concrete P and NP",
      "Lean theorem: compiled concrete CNFSAT verifier plus concrete SAT-hardness gives SAT NP-completeness",
      "Lean theorem: concrete equality, constant-one, constant-zero, NAND-trace, and final-conjunction macro semantics",
      "Lean computation: exposed single-instance macro outputs are pairwise distinct, nonconstant, and nonprojection",
      "Lean theorem: two-gate prefix nodes compute conjunction and expose its negation",
      "Lean theorem: the prefix tree covers exactly the supplied check list and is true iff every check is true",
      "Lean theorem: a nonempty n-check prefix tree uses exactly 2(n-1) NAND gates",
      "Lean computation: prefix-node exposed outputs are distinct, nonconstant, and nonprojection",
      "Lean theorem: structured PCCMin loop certificate constructs a residual-band exact-minimization decider witness",
      "Lean theorem: the concrete locked-NAND and residual-band endpoints share one encoded exact-minimum predicate, so identity transport gives locked NAND threshold ∈ P from residual-band membership",
      "Lean theorem: concrete locked NAND threshold in P plus the compiled all-bitstring CNFSAT-to-locked-NAND reduction gives concrete SAT ∈ P",
      "Lean computation: typed PCCPack generation preserves an explicit proof-bearing PCCMin loop certificate, canonical generated identifiers accept, and mismatched identifiers reject"
    ]
    externalTrustBase := [
      "Existence of a proof-bearing PCCMin loop certificate containing the concrete residual-band decider",
      "Semantic adequacy of PCCMinLoopCertificate and ZeroSlackCertificate fields for the executable PCCMin algorithm",
      "Concrete SAT NP-hardness in the finite-pipeline reduction model"
    ] }

end PNP
