/-
Copyright (c) 2026 PNP Labs.

Constructive finite reconstruction of the pinned manuscript's theorem V54,
`consumer-antichain normal form`.  An arbitrary finite antichain of nonempty
minimal consumers generates its monotone Boolean request function: a cut is
active exactly when it contains one consumer.  The two-sided activation
`kappa(S) = r(S) * r(A \ S)` is nonzero exactly when the antichain contains a
disjoint pair.  If every disjoint consumer pair is singleton-singleton, the
two-sided activation is exactly the cut indicator of the singleton footprint
`E = {a | {a} is a minimal consumer}`.

The carrier and consumer antichain are arbitrary finite lists; no fixed anchor
cardinality or hard-coded cut coordinates occur.  This closes the mathematical
V54 edge from PkgC singletonization to the hyperedge footprint consumed by BN6.
It does not construct the PkgC restoration universe, prove that its routes are
silent, derive a consumer antichain from a terminal candidate, prove V53 or
BN6, establish polynomial runtime, prove ZeroSlack or PCCMin, put SAT in P, or
prove P = NP.
-/

import PNP.ResidualTerminalBN5FullShadowLocalization

namespace PNP
namespace DirectWire

/-! ## Finite consumer systems -/

/-- Extensional inclusion between finite list representatives. -/
def TerminalV54Included {Atom : Type}
    (left right : List Atom) : Prop :=
  ∀ atom, atom ∈ left -> atom ∈ right

/-- Extensional strict inclusion.  This ignores list order, as the manuscript's
    consumers are finite sets. -/
def TerminalV54StrictIncluded {Atom : Type}
    (left right : List Atom) : Prop :=
  TerminalV54Included left right ∧ ¬ TerminalV54Included right left

/-- Two finite consumers share no atom. -/
def TerminalV54Disjoint {Atom : Type}
    (left right : List Atom) : Prop :=
  ∀ atom, atom ∈ left -> atom ∉ right

theorem terminalV54Included_refl
    {Atom : Type} (items : List Atom) :
    TerminalV54Included items items :=
  fun _ member => member

theorem terminalV54Included_trans
    {Atom : Type} {first second third : List Atom}
    (firstSecond : TerminalV54Included first second)
    (secondThird : TerminalV54Included second third) :
    TerminalV54Included first third :=
  fun atom member => secondThird atom (firstSecond atom member)

theorem terminalV54Disjoint_symm
    {Atom : Type} {left right : List Atom}
    (disjoint : TerminalV54Disjoint left right) :
    TerminalV54Disjoint right left := by
  intro atom rightMember leftMember
  exact disjoint atom leftMember rightMember

/-- A finite minimal-consumer antichain for one carrier.  `consumerAntichain`
    is the exact minimality condition: no listed consumer is extensionally
    contained in another distinct listed consumer. -/
structure TerminalV54ConsumerSystem (Atom : Type) where
  carrier : List Atom
  carrierNodup : carrier.Nodup
  consumers : List (List Atom)
  consumersNodup : consumers.Nodup
  consumerNodup : ∀ consumer, consumer ∈ consumers -> consumer.Nodup
  consumerNonempty : ∀ consumer, consumer ∈ consumers -> consumer ≠ []
  consumerContained : ∀ consumer, consumer ∈ consumers ->
    TerminalV54Included consumer carrier
  consumerAntichain : ∀ left, left ∈ consumers ->
    ∀ right, right ∈ consumers ->
      TerminalV54Included left right -> left = right

/-- The monotone request generated by the complete minimal-consumer family. -/
def TerminalV54ConsumerSystem.RequestActive
    {Atom : Type} (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) : Prop :=
  ∃ consumer, consumer ∈ system.consumers ∧
    TerminalV54Included consumer cut

/-- Executable `{0,1}` representative of `RequestActive`. -/
def TerminalV54ConsumerSystem.requestBool
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) : Bool :=
  system.consumers.any fun consumer =>
    consumer.all fun atom => decide (atom ∈ cut)

theorem TerminalV54ConsumerSystem.requestBool_eq_true_iff
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) :
    system.requestBool cut = true ↔ system.RequestActive cut := by
  simp [TerminalV54ConsumerSystem.requestBool,
    TerminalV54ConsumerSystem.RequestActive, TerminalV54Included]

/-- The induced request is monotone, matching the first premise of V54. -/
theorem TerminalV54ConsumerSystem.requestActive_monotone
    {Atom : Type} (system : TerminalV54ConsumerSystem Atom)
    {left right : List Atom}
    (included : TerminalV54Included left right)
    (active : system.RequestActive left) :
    system.RequestActive right := by
  obtain ⟨consumer, consumerMember, consumerLeft⟩ := active
  exact ⟨consumer, consumerMember,
    terminalV54Included_trans consumerLeft included⟩

/-- Nonempty consumers make the empty cut inactive, matching `r(∅)=0`. -/
theorem TerminalV54ConsumerSystem.requestActive_empty_false
    {Atom : Type} (system : TerminalV54ConsumerSystem Atom) :
    ¬ system.RequestActive [] := by
  rintro ⟨consumer, consumerMember, consumerEmpty⟩
  cases consumer with
  | nil =>
      exact system.consumerNonempty [] consumerMember rfl
  | cons head tail =>
      have impossible : head ∈ ([] : List Atom) :=
        consumerEmpty head (by simp)
      simp at impossible

/-- Every listed consumer is active and has no strictly smaller active
    consumer.  Thus the structure really presents minimal consumers rather
    than an arbitrary caller-labelled family. -/
theorem TerminalV54ConsumerSystem.consumer_is_minimal
    {Atom : Type} (system : TerminalV54ConsumerSystem Atom)
    (consumer : List Atom) (consumerMember : consumer ∈ system.consumers) :
    system.RequestActive consumer ∧
      ∀ subset, TerminalV54StrictIncluded subset consumer ->
        ¬ system.RequestActive subset := by
  constructor
  · exact ⟨consumer, consumerMember, terminalV54Included_refl consumer⟩
  · intro subset strict subsetActive
    obtain ⟨smallerConsumer, smallerMember, smallerSubset⟩ := subsetActive
    have smallerInConsumer :
        TerminalV54Included smallerConsumer consumer :=
      terminalV54Included_trans smallerSubset strict.1
    have equal : smallerConsumer = consumer :=
      system.consumerAntichain smallerConsumer smallerMember consumer
        consumerMember smallerInConsumer
    exact strict.2 (equal ▸ smallerSubset)

/-! ## Complements, two-sided activation, and the singleton footprint -/

/-- Canonical complement inside the finite carrier. -/
def terminalV54Complement
    {Atom : Type} [DecidableEq Atom]
    (carrier cut : List Atom) : List Atom :=
  carrier.filter fun atom => decide (atom ∉ cut)

theorem mem_terminalV54Complement_iff
    {Atom : Type} [DecidableEq Atom]
    (carrier cut : List Atom) (atom : Atom) :
    atom ∈ terminalV54Complement carrier cut ↔
      atom ∈ carrier ∧ atom ∉ cut := by
  simp [terminalV54Complement]

/-- `kappa(S)=1`: both the cut and its carrier complement activate the
    request. -/
def TerminalV54ConsumerSystem.CutActive
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) : Prop :=
  system.RequestActive cut ∧
    system.RequestActive (terminalV54Complement system.carrier cut)

/-- Executable `{0,1}` representative of `CutActive`. -/
def TerminalV54ConsumerSystem.cutActivationBool
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) : Bool :=
  system.requestBool cut &&
    system.requestBool (terminalV54Complement system.carrier cut)

theorem TerminalV54ConsumerSystem.cutActivationBool_eq_true_iff
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) :
    system.cutActivationBool cut = true ↔ system.CutActive cut := by
  simp [TerminalV54ConsumerSystem.cutActivationBool,
    TerminalV54ConsumerSystem.CutActive,
    TerminalV54ConsumerSystem.requestBool_eq_true_iff]

/-- `E={a | {a} is a minimal consumer}` in canonical carrier order. -/
def TerminalV54ConsumerSystem.singletonFootprint
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom) : List Atom :=
  system.carrier.filter fun atom => decide ([atom] ∈ system.consumers)

theorem TerminalV54ConsumerSystem.mem_singletonFootprint_iff
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom) (atom : Atom) :
    atom ∈ system.singletonFootprint ↔
      atom ∈ system.carrier ∧ [atom] ∈ system.consumers := by
  simp [TerminalV54ConsumerSystem.singletonFootprint]

/-- The singleton footprint crosses a cut exactly when it has a singleton
    consumer on each side. -/
def TerminalV54ConsumerSystem.FootprintCrossesCut
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) : Prop :=
  ∃ leftAtom, leftAtom ∈ system.singletonFootprint ∧ leftAtom ∈ cut ∧
    ∃ rightAtom, rightAtom ∈ system.singletonFootprint ∧
      rightAtom ∈ terminalV54Complement system.carrier cut

/-- Executable indicator `1_{E cuts S}`. -/
def TerminalV54ConsumerSystem.cutIndicatorBool
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) : Bool :=
  (system.singletonFootprint.any fun atom => decide (atom ∈ cut)) &&
    (system.singletonFootprint.any fun atom =>
      decide (atom ∈ terminalV54Complement system.carrier cut))

theorem TerminalV54ConsumerSystem.cutIndicatorBool_eq_true_iff
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) :
    system.cutIndicatorBool cut = true ↔
      system.FootprintCrossesCut cut := by
  simp [TerminalV54ConsumerSystem.cutIndicatorBool,
    TerminalV54ConsumerSystem.FootprintCrossesCut]
  constructor
  · rintro ⟨⟨leftAtom, leftFootprint, leftCut⟩,
      ⟨rightAtom, rightFootprint, rightComplement⟩⟩
    exact ⟨leftAtom, leftFootprint, leftCut,
      rightAtom, rightFootprint, rightComplement⟩
  · rintro ⟨leftAtom, leftFootprint, leftCut,
      rightAtom, rightFootprint, rightComplement⟩
    exact ⟨⟨leftAtom, leftFootprint, leftCut⟩,
      ⟨rightAtom, rightFootprint, rightComplement⟩⟩

/-! ## V54 consumer-antichain normal form -/

/-- Pointwise two-sided activation exposes a disjoint pair of minimal
    consumers. -/
theorem TerminalV54ConsumerSystem.cutActive_has_disjoint_consumers
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (cut : List Atom) (active : system.CutActive cut) :
    ∃ left, left ∈ system.consumers ∧
      ∃ right, right ∈ system.consumers ∧
        TerminalV54Disjoint left right := by
  obtain ⟨⟨left, leftMember, leftCut⟩,
    ⟨right, rightMember, rightComplement⟩⟩ := active
  refine ⟨left, leftMember, right, rightMember, ?_⟩
  intro atom leftAtom rightAtom
  have atomCut : atom ∈ cut := leftCut atom leftAtom
  have atomComplement :
      atom ∈ terminalV54Complement system.carrier cut :=
    rightComplement atom rightAtom
  exact (mem_terminalV54Complement_iff system.carrier cut atom).1
    atomComplement |>.2 atomCut

/-- V54's first conclusion: `kappa` is nonzero on some cut exactly when the
    minimal-consumer antichain contains two disjoint members. -/
theorem terminalV54_cutActivation_nonzero_iff_disjoint_consumers
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom) :
    (∃ cut, system.CutActive cut) ↔
      ∃ left, left ∈ system.consumers ∧
        ∃ right, right ∈ system.consumers ∧
          TerminalV54Disjoint left right := by
  constructor
  · rintro ⟨cut, active⟩
    exact system.cutActive_has_disjoint_consumers cut active
  · rintro ⟨left, leftMember, right, rightMember, disjoint⟩
    refine ⟨left,
      ⟨⟨left, leftMember, terminalV54Included_refl left⟩, ?_⟩⟩
    refine ⟨right, rightMember, ?_⟩
    intro atom rightAtom
    apply (mem_terminalV54Complement_iff system.carrier left atom).2
    exact ⟨system.consumerContained right rightMember atom rightAtom,
      terminalV54Disjoint_symm disjoint atom rightAtom⟩

/-- The exact PkgC premise consumed by V54: every disjoint pair of minimal
    consumers consists of singleton sets. -/
def TerminalV54ConsumerSystem.DisjointPairsSingletonized
    {Atom : Type} (system : TerminalV54ConsumerSystem Atom) : Prop :=
  ∀ left, left ∈ system.consumers ->
    ∀ right, right ∈ system.consumers ->
      TerminalV54Disjoint left right ->
        ∃ leftAtom rightAtom, left = [leftAtom] ∧ right = [rightAtom]

/-- V54's normal-form conclusion, propositionally: under PkgC
    singletonization, two-sided request activation is exactly crossing of the
    singleton footprint. -/
theorem terminalV54_consumerAntichain_normal_form_iff
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (singletonized : system.DisjointPairsSingletonized)
    (cut : List Atom) :
    system.CutActive cut ↔ system.FootprintCrossesCut cut := by
  constructor
  · intro active
    obtain ⟨⟨left, leftMember, leftCutIncluded⟩,
      ⟨right, rightMember, rightComplementIncluded⟩⟩ := active
    have disjoint : TerminalV54Disjoint left right := by
      intro atom leftAtom rightAtom
      have atomCut : atom ∈ cut := leftCutIncluded atom leftAtom
      have atomComplement :
          atom ∈ terminalV54Complement system.carrier cut :=
        rightComplementIncluded atom rightAtom
      exact (mem_terminalV54Complement_iff system.carrier cut atom).1
        atomComplement |>.2 atomCut
    obtain ⟨leftAtom, rightAtom, leftEqual, rightEqual⟩ :=
      singletonized left leftMember right rightMember disjoint
    have leftCut : leftAtom ∈ cut := by
      apply leftCutIncluded leftAtom
      simp [leftEqual]
    have rightComplement :
        rightAtom ∈ terminalV54Complement system.carrier cut := by
      apply rightComplementIncluded rightAtom
      simp [rightEqual]
    have leftCarrier : leftAtom ∈ system.carrier :=
      system.consumerContained left leftMember leftAtom (by simp [leftEqual])
    have rightCarrier : rightAtom ∈ system.carrier :=
      system.consumerContained right rightMember rightAtom (by
        simp [rightEqual])
    refine ⟨leftAtom,
      (system.mem_singletonFootprint_iff leftAtom).2
        ⟨leftCarrier, leftEqual ▸ leftMember⟩,
      leftCut, rightAtom,
      (system.mem_singletonFootprint_iff rightAtom).2
        ⟨rightCarrier, rightEqual ▸ rightMember⟩,
      rightComplement⟩
  · rintro ⟨leftAtom, leftFootprint, leftCut,
      rightAtom, rightFootprint, rightComplement⟩
    have leftConsumer : [leftAtom] ∈ system.consumers :=
      (system.mem_singletonFootprint_iff leftAtom).1 leftFootprint |>.2
    have rightConsumer : [rightAtom] ∈ system.consumers :=
      (system.mem_singletonFootprint_iff rightAtom).1 rightFootprint |>.2
    constructor
    · refine ⟨[leftAtom], leftConsumer, ?_⟩
      intro atom atomMember
      simp at atomMember
      subst atom
      exact leftCut
    · refine ⟨[rightAtom], rightConsumer, ?_⟩
      intro atom atomMember
      simp at atomMember
      subst atom
      exact rightComplement

/-- Executable equality form of V54: `kappa(S)` is literally the Boolean cut
    indicator of the singleton footprint. -/
theorem terminalV54_consumerAntichain_normal_form
    {Atom : Type} [DecidableEq Atom]
    (system : TerminalV54ConsumerSystem Atom)
    (singletonized : system.DisjointPairsSingletonized)
    (cut : List Atom) :
    system.cutActivationBool cut = system.cutIndicatorBool cut := by
  have equalTrue :
      system.cutActivationBool cut = true ↔
        system.cutIndicatorBool cut = true := by
    rw [system.cutActivationBool_eq_true_iff,
      system.cutIndicatorBool_eq_true_iff]
    exact terminalV54_consumerAntichain_normal_form_iff system
      singletonized cut
  cases activation : system.cutActivationBool cut <;>
    cases indicator : system.cutIndicatorBool cut <;>
      simp_all

end DirectWire
end PNP
