import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import {REQUIRED_MILESTONE_THEOREMS0} from '../formal-publication0.mjs';
import {
  explicitLeanDeclarationHeads0, hasLeanAssumptionDeclaration0,
  hasUnauditedLeanDeclarationForm0, stripLeanCommentsAndStrings0,
} from './lean-source-declarations0.mjs';

// Frozen from reviewed source and regression expectations, not regenerated by tests.
const SPECS = [
  {
    "part": "GateRenamingEncoding",
    "path": "lean/PNP/NANDGateRenamingEncoding.lean",
    "module": "PNP.NANDGateRenamingEncoding",
    "sourceContractSha256": "dc9ad9e24438acf8980fbd3cae2d4c258e23e08cb52bdfb818e6da8ea3d6b0b2",
    "heads": [
      {
        "kind": "def",
        "name": "encode"
      },
      {
        "kind": "theorem",
        "name": "decode_encode"
      },
      {
        "kind": "theorem",
        "name": "encode_length_le"
      },
      {
        "kind": "theorem",
        "name": "validCode_encode"
      }
    ],
    "theorems": [
      "PNP.DirectWire.StructuralReindexing.GateRenaming.decode_encode",
      "PNP.DirectWire.StructuralReindexing.GateRenaming.encode_length_le",
      "PNP.DirectWire.StructuralReindexing.GateRenaming.validCode_encode"
    ]
  },
  {
    "part": "WireCarrierRecoding",
    "path": "lean/PNP/NANDWireCarrierRecoding.lean",
    "module": "PNP.NANDWireCarrierRecoding",
    "sourceContractSha256": "079d01a7281a9b890dbbe96923afa981fd8d143e176e18e7de8de965b9ad7118",
    "heads": [
      {
        "kind": "def",
        "name": "roundTripCheck"
      },
      {
        "kind": "theorem",
        "name": "roundTripCheck_iff"
      },
      {
        "kind": "def",
        "name": "check"
      },
      {
        "kind": "theorem",
        "name": "check_iff"
      },
      {
        "kind": "structure",
        "name": "Checked"
      },
      {
        "kind": "def",
        "name": "compile"
      },
      {
        "kind": "theorem",
        "name": "compile_success_iff"
      },
      {
        "kind": "def",
        "name": "appendMap"
      },
      {
        "kind": "theorem",
        "name": "appendMap_gateCount"
      },
      {
        "kind": "theorem",
        "name": "appendMap_output"
      },
      {
        "kind": "theorem",
        "name": "appendMap_field"
      },
      {
        "kind": "def",
        "name": "encoded"
      },
      {
        "kind": "theorem",
        "name": "encoded_output"
      },
      {
        "kind": "theorem",
        "name": "encoded_field"
      },
      {
        "kind": "def",
        "name": "expanded"
      },
      {
        "kind": "def",
        "name": "result"
      },
      {
        "kind": "def",
        "name": "removed"
      },
      {
        "kind": "theorem",
        "name": "result_output"
      },
      {
        "kind": "theorem",
        "name": "result_field"
      },
      {
        "kind": "theorem",
        "name": "result_gate_balance"
      }
    ],
    "theorems": [
      "PNP.DirectWire.WireCarrierRecoding.roundTripCheck_iff",
      "PNP.DirectWire.WireCarrierRecoding.check_iff",
      "PNP.DirectWire.WireCarrierRecoding.compile_success_iff",
      "PNP.DirectWire.WireCarrierRecoding.appendMap_gateCount",
      "PNP.DirectWire.WireCarrierRecoding.appendMap_output",
      "PNP.DirectWire.WireCarrierRecoding.appendMap_field",
      "PNP.DirectWire.WireCarrierRecoding.encoded_output",
      "PNP.DirectWire.WireCarrierRecoding.encoded_field",
      "PNP.DirectWire.WireCarrierRecoding.result_output",
      "PNP.DirectWire.WireCarrierRecoding.result_field",
      "PNP.DirectWire.WireCarrierRecoding.result_gate_balance"
    ]
  },
  {
    "part": "CausalGuard",
    "path": "lean/PNP/NANDCausalGuard.lean",
    "module": "PNP.NANDCausalGuard",
    "sourceContractSha256": "46f214d3446cba3e30de6472b30be9bab984c8b65932c601ee32693262547627",
    "heads": [
      {
        "kind": "def",
        "name": "singletonLabel"
      },
      {
        "kind": "theorem",
        "name": "levels_bounded_iff"
      },
      {
        "kind": "theorem",
        "name": "source_bounded_iff"
      },
      {
        "kind": "def",
        "name": "sourceDependencyGuard"
      },
      {
        "kind": "theorem",
        "name": "sourceDependencyGuard_iff"
      },
      {
        "kind": "def",
        "name": "candidateDependencyGuard"
      },
      {
        "kind": "theorem",
        "name": "candidateDependencyGuard_iff"
      },
      {
        "kind": "def",
        "name": "dependencyGuard"
      },
      {
        "kind": "theorem",
        "name": "dependencyGuard_iff"
      }
    ],
    "theorems": [
      "PNP.DirectWire.CausalBound.levels_bounded_iff",
      "PNP.DirectWire.CausalBound.source_bounded_iff",
      "PNP.DirectWire.CausalBound.sourceDependencyGuard_iff",
      "PNP.DirectWire.CausalBound.candidateDependencyGuard_iff",
      "PNP.DirectWire.WireCarrier.dependencyGuard_iff"
    ]
  },
  {
    "part": "WireRecodingState",
    "path": "lean/PNP/NANDWireRecodingState.lean",
    "module": "PNP.NANDWireRecodingState",
    "sourceContractSha256": "0b024f2fc7827418ca36749e4071e3796d81dc4a481a8cc7139e7c1496fe861f",
    "heads": [
      {
        "kind": "def",
        "name": "recode"
      },
      {
        "kind": "theorem",
        "name": "recode_pending"
      },
      {
        "kind": "theorem",
        "name": "recode_charged"
      },
      {
        "kind": "theorem",
        "name": "recode_removed"
      },
      {
        "kind": "theorem",
        "name": "recode_causalInvariant"
      },
      {
        "kind": "structure",
        "name": "Receipt"
      },
      {
        "kind": "def",
        "name": "Receipt.next"
      },
      {
        "kind": "def",
        "name": "execute"
      },
      {
        "kind": "theorem",
        "name": "execute_success_iff"
      },
      {
        "kind": "theorem",
        "name": "execute_failure_iff"
      },
      {
        "kind": "theorem",
        "name": "Receipt.pending"
      },
      {
        "kind": "theorem",
        "name": "Receipt.causalInvariant"
      },
      {
        "kind": "theorem",
        "name": "Receipt.gate_balance"
      }
    ],
    "theorems": [
      "PNP.DirectWire.WireObligationHistory.State.recode_pending",
      "PNP.DirectWire.WireObligationHistory.State.recode_charged",
      "PNP.DirectWire.WireObligationHistory.State.recode_removed",
      "PNP.DirectWire.WireObligationHistory.State.recode_causalInvariant",
      "PNP.DirectWire.WireRecodingState.execute_success_iff",
      "PNP.DirectWire.WireRecodingState.execute_failure_iff",
      "PNP.DirectWire.WireRecodingState.Receipt.pending",
      "PNP.DirectWire.WireRecodingState.Receipt.causalInvariant",
      "PNP.DirectWire.WireRecodingState.Receipt.gate_balance"
    ]
  },
  {
    "part": "WireRecodingOwnership",
    "path": "lean/PNP/NANDWireRecodingOwnership.lean",
    "module": "PNP.NANDWireRecodingOwnership",
    "sourceContractSha256": "2500facebad79f803413e355ed0c3e9267df88212be64fe32279cbdc273fa489",
    "heads": [
      {
        "kind": "def",
        "name": "allocations"
      },
      {
        "kind": "def",
        "name": "encoderLedger"
      },
      {
        "kind": "def",
        "name": "encodedLedger"
      },
      {
        "kind": "def",
        "name": "decoderLedger"
      },
      {
        "kind": "def",
        "name": "ledger"
      },
      {
        "kind": "theorem",
        "name": "encoder_positions"
      },
      {
        "kind": "theorem",
        "name": "encoded_origin"
      },
      {
        "kind": "theorem",
        "name": "decoder_positions"
      },
      {
        "kind": "theorem",
        "name": "ledger_origin"
      },
      {
        "kind": "theorem",
        "name": "ledger_charged"
      },
      {
        "kind": "theorem",
        "name": "ledger_removed_length"
      },
      {
        "kind": "theorem",
        "name": "ledger_partition"
      },
      {
        "kind": "theorem",
        "name": "allocation_phases_nodup"
      },
      {
        "kind": "theorem",
        "name": "physical_ownership"
      },
      {
        "kind": "def",
        "name": "labelled"
      },
      {
        "kind": "theorem",
        "name": "labelled_live"
      },
      {
        "kind": "theorem",
        "name": "labelled_physical_ownership"
      },
      {
        "kind": "def",
        "name": "Receipt.ownership"
      },
      {
        "kind": "theorem",
        "name": "Receipt.physical_ownership"
      }
    ],
    "theorems": [
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.encoder_positions",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.encoded_origin",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.decoder_positions",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_origin",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_charged",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_removed_length",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_partition",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.allocation_phases_nodup",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.physical_ownership",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.labelled_live",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.labelled_physical_ownership",
      "PNP.DirectWire.WireRecodingState.Receipt.physical_ownership"
    ]
  },
  {
    "part": "WireRecodingInput",
    "path": "lean/PNP/NANDWireRecodingInput.lean",
    "module": "PNP.NANDWireRecodingInput",
    "sourceContractSha256": "3bca0df23a1471f89a148c7beb92540cb54b887e0f81135f25940cf624de750c",
    "heads": [
      {
        "kind": "def",
        "name": "atWidth"
      },
      {
        "kind": "def",
        "name": "decode"
      },
      {
        "kind": "theorem",
        "name": "decode_encode"
      },
      {
        "kind": "theorem",
        "name": "decode_elaboration_none"
      },
      {
        "kind": "theorem",
        "name": "decode_success_iff"
      },
      {
        "kind": "structure",
        "name": "Receipt"
      },
      {
        "kind": "def",
        "name": "Receipt.next"
      },
      {
        "kind": "def",
        "name": "Receipt.charged"
      },
      {
        "kind": "def",
        "name": "Receipt.removed"
      },
      {
        "kind": "def",
        "name": "execute"
      },
      {
        "kind": "theorem",
        "name": "execute_success_iff"
      },
      {
        "kind": "theorem",
        "name": "execute_encoder_none"
      },
      {
        "kind": "theorem",
        "name": "execute_decoder_none"
      },
      {
        "kind": "theorem",
        "name": "Receipt.pending"
      },
      {
        "kind": "theorem",
        "name": "Receipt.charged_eq"
      },
      {
        "kind": "theorem",
        "name": "Receipt.removed_eq"
      },
      {
        "kind": "theorem",
        "name": "Receipt.causalInvariant"
      }
    ],
    "theorems": [
      "PNP.DirectWire.WireRecodingInput.decode_encode",
      "PNP.DirectWire.WireRecodingInput.decode_elaboration_none",
      "PNP.DirectWire.WireRecodingInput.decode_success_iff",
      "PNP.DirectWire.WireRecodingInput.execute_success_iff",
      "PNP.DirectWire.WireRecodingInput.execute_encoder_none",
      "PNP.DirectWire.WireRecodingInput.execute_decoder_none",
      "PNP.DirectWire.WireRecodingInput.Receipt.pending",
      "PNP.DirectWire.WireRecodingInput.Receipt.charged_eq",
      "PNP.DirectWire.WireRecodingInput.Receipt.removed_eq",
      "PNP.DirectWire.WireRecodingInput.Receipt.causalInvariant"
    ]
  }
];
const REUSED_NAMES = [
  "PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_origin",
  "PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_charged",
  "PNP.DirectWire.WireOpenProgram.ProgramOwnership.advance_structural_removed",
  "PNP.DirectWire.WireOpenProgram.orderEvents_success_iff",
  "PNP.DirectWire.WireOpenProgram.orderEvents_failure_iff",
  "PNP.DirectWire.WireOpenProgram.execute_failed_tail",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.full_output",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.full_field",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.creation_lifecycle",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.executed_count",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.executed_identities_nodup",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.causalInvariant",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.physical_ownership",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.ownership_origin_injective",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.ownership_charge_origin",
  "PNP.DirectWire.WireOpenProgram.compile_exists_iff",
  "PNP.DirectWire.WireOpenProgram.compile_none_iff",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.records_source",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.proper_support",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.output",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.field",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.charge_accounting",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictGain",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictResidualDescent",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.physical_ownership",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.closed_ledger",
  "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.creation_lifecycle",
  "PNP.DirectWire.WireOpenCertificate.verify_exists_iff",
  "PNP.DirectWire.WireOpenCertificate.verify_sound",
  "PNP.DirectWire.WireOpenCertificate.verify_decode_none",
  "PNP.DirectWire.WireOpenCertificate.verify_program_none",
  "PNP.DirectWire.WireOpenCertificate.verify_not_proper",
  "PNP.DirectWire.WireOpenCertificate.verify_no_gain",
  "PNP.DirectWire.WireOpenProgram.Transition.charged_eq",
  "PNP.DirectWire.WireOpenProgram.Transition.removed_eq",
  "PNP.DirectWire.WireOpenProgram.Transition.causalInvariant",
  "PNP.DirectWire.WireOpenProgram.Transition.local_physical_ownership",
  "PNP.DirectWire.WireOpenProgram.CompiledProgram.gate_balance"
];
const REGRESSIONS = [
  {
    "path": "lean-regression/PNPGateRenamingEncoding.lean",
    "imports": [
      "PNP.NANDGateRenamingEncoding"
    ],
    "printedNames": [
      "GateRenaming.decode_encode",
      "GateRenaming.encode_length_le",
      "GateRenaming.validCode_encode"
    ],
    "sourceContractSha256": "83ccaa52d0fbc34f0d20f1da03a5066cf6d99dcd9ffc5def3bde9296f47220e9"
  },
  {
    "path": "lean-regression/PNPWireCarrierRecoding.lean",
    "imports": [
      "PNP.NANDWireCarrierRecoding"
    ],
    "printedNames": [
      "PNP.DirectWire.WireCarrierRecoding.check_iff",
      "PNP.DirectWire.WireCarrierRecoding.compile_success_iff",
      "PNP.DirectWire.WireCarrierRecoding.appendMap_field",
      "PNP.DirectWire.WireCarrierRecoding.result_output",
      "PNP.DirectWire.WireCarrierRecoding.result_field",
      "PNP.DirectWire.WireCarrierRecoding.result_gate_balance"
    ],
    "sourceContractSha256": "0336c09c046cefe5f51a7222e23a10cad78a6eda952e201a7ac7e59ff84d82fa"
  },
  {
    "path": "lean-regression/PNPWireRecodingState.lean",
    "imports": [
      "PNP.NANDWireRecodingState"
    ],
    "printedNames": [
      "PNP.DirectWire.CausalBound.levels_bounded_iff",
      "PNP.DirectWire.CausalBound.source_bounded_iff",
      "PNP.DirectWire.CausalBound.sourceDependencyGuard_iff",
      "PNP.DirectWire.CausalBound.candidateDependencyGuard_iff",
      "PNP.DirectWire.WireCarrier.dependencyGuard_iff",
      "PNP.DirectWire.WireObligationHistory.State.recode_pending",
      "PNP.DirectWire.WireRecodingState.execute_success_iff",
      "PNP.DirectWire.WireRecodingState.execute_failure_iff",
      "PNP.DirectWire.WireRecodingState.Receipt.causalInvariant",
      "PNP.DirectWire.WireRecodingState.Receipt.gate_balance"
    ],
    "sourceContractSha256": "385c0f2e80ea542bca023526c8e1378e69685da5129bbc50b62f1f20df661ec9"
  },
  {
    "path": "lean-regression/PNPWireRecodingOwnership.lean",
    "imports": [
      "PNP.NANDWireRecodingOwnership"
    ],
    "printedNames": [
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.encoder_positions",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.encoded_origin",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.decoder_positions",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_origin",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_charged",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_removed_length",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.ledger_partition",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.allocation_phases_nodup",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.physical_ownership",
      "PNP.DirectWire.WireCarrierRecoding.PhysicalAccounting.labelled_physical_ownership",
      "PNP.DirectWire.WireRecodingState.Receipt.physical_ownership"
    ],
    "sourceContractSha256": "b60f24296187ff4758ce8676c368a94444ccf98d7e38ace136f1fbd0d062332b"
  },
  {
    "path": "lean-regression/PNPWireRecodingInput.lean",
    "imports": [
      "PNP.NANDWireRecodingInput"
    ],
    "printedNames": [
      "PNP.DirectWire.WireRecodingInput.decode_encode",
      "PNP.DirectWire.WireRecodingInput.decode_elaboration_none",
      "PNP.DirectWire.WireRecodingInput.decode_success_iff",
      "PNP.DirectWire.WireRecodingInput.execute_success_iff",
      "PNP.DirectWire.WireRecodingInput.execute_encoder_none",
      "PNP.DirectWire.WireRecodingInput.execute_decoder_none",
      "PNP.DirectWire.WireRecodingInput.Receipt.pending",
      "PNP.DirectWire.WireRecodingInput.Receipt.charged_eq",
      "PNP.DirectWire.WireRecodingInput.Receipt.removed_eq",
      "PNP.DirectWire.WireRecodingInput.Receipt.causalInvariant"
    ],
    "sourceContractSha256": "b103bccf5db4b048dbf0eb405d25208e68b5aa498b7e35282ab3a79287087297"
  },
  {
    "path": "lean-regression/PNPWireRecodingProgram.lean",
    "imports": [
      "PNP.NANDWireOpenCertificate"
    ],
    "printedNames": [
      "PNP.DirectWire.WireOpenProgram.Transition.charged_eq",
      "PNP.DirectWire.WireOpenProgram.Transition.removed_eq",
      "PNP.DirectWire.WireOpenProgram.Transition.causalInvariant",
      "PNP.DirectWire.WireOpenProgram.Transition.local_physical_ownership",
      "PNP.DirectWire.WireOpenProgram.CompiledProgram.full_output",
      "PNP.DirectWire.WireOpenProgram.CompiledProgram.full_field",
      "PNP.DirectWire.WireOpenProgram.CompiledProgram.gate_balance",
      "PNP.DirectWire.WireOpenProgram.CompiledProgram.creation_lifecycle",
      "PNP.DirectWire.WireOpenProgram.CompiledProgram.physical_ownership",
      "PNP.DirectWire.WireOpenCertificate.verify_no_gain"
    ],
    "sourceContractSha256": "9362cccea41200b5757f8e28403f5af651f92e773b885b4231fb62bc852057ce"
  },
  {
    "path": "lean-regression/PNPWireRecodingCertificate.lean",
    "imports": [
      "PNP.NANDWireOpenCertificate"
    ],
    "printedNames": [
      "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictGain",
      "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.strictResidualDescent",
      "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.physical_ownership",
      "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.creation_lifecycle",
      "PNP.DirectWire.WireOpenCertificate.CheckedCertificate.charge_accounting",
      "PNP.DirectWire.WireOpenCertificate.verify_program_none",
      "PNP.DirectWire.WireOpenCertificate.verify_not_proper",
      "PNP.DirectWire.WireOpenCertificate.verify_no_gain"
    ],
    "sourceContractSha256": "7ee0904bbd145af9eba726f07bd051fd2b196e98d0380eaf1a56e31c2821891d"
  }
];
const AXIOM_NAMES = [...SPECS.flatMap(spec => spec.theorems), ...REUSED_NAMES];
// Exact aliases used only by the existing structural regression.
const PRINT_ALIASES = Object.freeze({
  "GateRenaming.decode_encode": "PNP.DirectWire.StructuralReindexing.GateRenaming.decode_encode",
  "GateRenaming.encode_length_le": "PNP.DirectWire.StructuralReindexing.GateRenaming.encode_length_le",
  "GateRenaming.validCode_encode": "PNP.DirectWire.StructuralReindexing.GateRenaming.validCode_encode"
});
const canonicalPrinted0 = name => PRINT_ALIASES[name] ?? name;
const text0 = file => readFile(new URL('../' + file, import.meta.url), 'utf8');
const compact0 = source => stripLeanCommentsAndStrings0(source).replace(/\s+/gu, ' ').trim();
const digest0 = source => createHash('sha256').update(compact0(source)).digest('hex');
const printed0 = source => [...source.matchAll(/^#print axioms\s+(\S+)\s*$/gmu)].map(row => row[1]);
function inspect0(source, spec) {
  const failures = [], clean = compact0(source);
  if (hasLeanAssumptionDeclaration0(source)) failures.push('assumption');
  if (hasUnauditedLeanDeclarationForm0(source)) failures.push('unaudited-form');
  if (/\b(?:sorry|admit|unsafe|native_decide|noncomputable|Classical|implemented_by|csimp)\b|#(?:eval|reduce|guard|synth)\b/u.test(clean))
    failures.push('shortcut');
  if (JSON.stringify(explicitLeanDeclarationHeads0(source).map(({kind, name}) => ({kind, name}))) !==
      JSON.stringify(spec.heads)) failures.push('closed-declarations');
  if (digest0(source) !== spec.sourceContractSha256) failures.push('reviewed-source-contract');
  return failures;
}
let loaded;
function sources0() {
  loaded ??= Promise.all(SPECS.map(async spec => ({spec, source: await text0(spec.path)})));
  return loaded;
}
async function rejectMutations0(part, mutations) {
  const found = (await sources0()).find(row => row.spec.part === part);
  assert.ok(found, part);
  for (const [label, from, to] of mutations) {
    assert.ok(found.source.includes(from), part + ': mutation target exists: ' + label);
    const changed = found.source.replace(from, () => to);
    assert.notEqual(changed, found.source, label);
    assert.ok(inspect0(changed, found.spec).length > 0, part + ': ' + label);
  }
}

test('M272 source: general constructions have exact closed reviewed contracts', async () => {
  assert.deepEqual(SPECS.map(spec => spec.part), [
    'GateRenamingEncoding', 'WireCarrierRecoding', 'CausalGuard',
    'WireRecodingState', 'WireRecodingOwnership', 'WireRecodingInput',
  ]);
  assert.equal(AXIOM_NAMES.length, 88);
  assert.equal(new Set(AXIOM_NAMES).size, AXIOM_NAMES.length);
  for (const {spec, source} of await sources0()) assert.deepEqual(inspect0(source, spec), [], spec.path);
});

test('M272 source: added authority, shortcuts and hidden declarations reject', async () => {
  for (const {spec, source} of await sources0()) {
    for (const extra of [
      'axiom suppliedCorrectness : True', 'private axiom suppliedCorrectness : True',
      'opaque suppliedCorrectness : True', 'variable (suppliedOwner : Nat)',
      'unsafe def hiddenAuthority : Nat := 0', 'import PNP.Main',
      'example : True := by trivial', 'private theorem extraAuthority : True := by trivial',
      'def extraAuthority : Nat := 0',
    ]) assert.ok(inspect0(source + '\n' + extra + '\n', spec).length > 0, spec.path + ': ' + extra);
    assert.deepEqual(inspect0(source + '\n/- prose: axiom suppliedCorrectness : True -/\n', spec), []);
  }
});

test('M272 source: existing structural encoding reconstructs the complete finite bijection', async () => {
  await rejectMutations0('GateRenamingEncoding', [
    ['arbitrary dimension', '(relabeling : GateRenaming nodes)', '(relabeling : GateRenaming 1)'],
    ['complete code', 'encodingRaw (encodingTyped nodes relabeling)', '(encodingRaw (encodingTyped nodes relabeling)).take 1'],
    ['exact decoded maps', 'decode nodes (encode relabeling) = some relabeling', 'True'],
    ['actual code length', '(encode relabeling).length ≤ nodes', '(encode relabeling).length ≤ nodes + 1'],
  ]);
});

test('M272 source: both full inverse equations and literal physical circuits are mandatory', async () => {
  await rejectMutations0('WireCarrierRecoding', [
    ['both inverse directions', 'roundTripCheck encoder decoder && roundTripCheck decoder encoder', 'roundTripCheck encoder decoder'],
    ['every field valuation', 'allBoolTuples fields', 'allBoolTuples 1'],
    ['actual field binding', 'carrier.source mapping.candidate.program', 'suppliedSources mapping.candidate.program'],
    ['actual field normalization', '(appendMap carrier encoder).normalize', 'suppliedNormalized'],
    ['no supplied decoder', '(encoder decoder : Implementation fields fields)', '(encoder decoder : Implementation 1 1)'],
  ]);
});

test('M272 source: causal guards inspect every syntactic dependency and hidden field', async () => {
  await rejectMutations0('CausalGuard', [
    ['every input', '(allFin inputs).all', '(allFin inputs).take 1 |>.all'],
    ['every output', '(allFin outputs).all', '(allFin outputs).take 1 |>.all'],
    ['hidden field observations', 'before.exposed.candidate after.exposed.candidate',
      'before.implementation.candidate after.implementation.candidate'],
    ['all natural label bounds', '∀ labels, after.CausalBounds labels', '∀ labels, True'],
    ['physical dependency direction',
      '0 < source afterWire (singletonLabel input) (levels after (singletonLabel input)) →',
      'True →'],
  ]);
});

test('M272 source: snapshots, accumulated costs and causal acceptance cannot be supplied or erased', async () => {
  await rejectMutations0('WireRecodingState', [
    ['entire pending function', 'pending := state.pending', 'pending := fun _ => none'],
    ['literal accumulated charges', 'charged := state.charged + encoder.gateCount + decoder.gateCount', 'charged := state.charged'],
    ['actual accumulated removals', 'removed := state.removed + WireCarrierRecoding.removed state.current encoder decoder', 'removed := suppliedRemovals'],
    ['computed inverse proof', 'WireCarrierRecoding.compile encoder decoder', 'suppliedInverse'],
    ['independent causal guard', 'if safe : before.current.dependencyGuard', 'if safe : suppliedCausality'],
  ]);
});

test('M272 source: actual normalizer maps and disjoint allocation phases preserve physical ownership', async () => {
  await rejectMutations0('WireRecodingOwnership', [
    ['actual encoder append', '.append 0 encoder.gateCount', '.append 0 0'],
    ['distinct decoder phase', '.append 1 decoder.gateCount', '.append 0 decoder.gateCount'],
    ['actual first deletion map', 'normalizedOrigin (appendMap carrier encoder).exposed gate', 'suppliedOwner gate'],
    ['actual second deletion map', 'normalizedOrigin (expanded carrier encoder decoder).exposed gate', 'suppliedOwner gate'],
    ['both historical charge lists', 'allocations carrier.implementation.gateCount 1 decoder.gateCount', '[]'],
    ['complete distinct ownership', '((ledger carrier encoder decoder).live ++ (ledger carrier encoder decoder).removed).Nodup', 'True'],
  ]);
});

test('M272 source: existing raw codec checks both widths and both complete input circuits', async () => {
  await rejectMutations0('WireRecodingInput', [
    ['existing elaborator', 'match raw.elaborate with', 'match suppliedElaboration with'],
    ['input width', 'packed.inputCount = fields', 'True'],
    ['output width', 'packed.outputCount = fields', 'True'],
    ['actual decoder input', 'match decoderAt : decode fields rawDecoder with', 'match decoderAt : decode fields rawEncoder with'],
    ['computed checked execution', 'WireRecodingState.execute before encoder decoder', 'suppliedReceipt'],
    ['actual decoder charge', 'receipt.encoder.gateCount + receipt.decoder.gateCount', 'receipt.encoder.gateCount'],
    ['literal deletion count', 'WireCarrierRecoding.removed before.current receipt.encoder receipt.decoder', 'suppliedRemovals'],
  ]);
});

test('M272 preflight: root, inventory names, pending publication contract and regression sources agree', async () => {
  const [root, audit, probe, mapText] = await Promise.all([
    text0('lean/PNP.lean'), text0('lean-audit/PNPComputationalRecodingAxiomAudit.lean'),
    text0('lean-audit/PNPTheoremInventory.lean'), text0('publication/FORMAL_PUBLICATION_MAP.json'),
  ]);
  assert.match(audit, /^import PNP$/mu);
  assert.deepEqual(printed0(audit), AXIOM_NAMES);
  for (const spec of SPECS) assert.ok(root.split('\n').includes('import ' + spec.module), spec.path);
  const map = JSON.parse(mapText);
  const rows = map.milestones.filter(row => row.id === 'computational-recoding-program-integration');
  assert.equal(rows.length, 1);
  assert.deepEqual(rows[0].requiredTheorems, AXIOM_NAMES);
  for (const name of AXIOM_NAMES) {
    assert.equal(probe.split(String.fromCharCode(96) + name + ',').length - 1, 1, name);
    assert.equal(REQUIRED_MILESTONE_THEOREMS0.filter(value => value === name).length, 1, name);
    assert.ok(Object.hasOwn(map.earnedMilestoneTheoremKernelTypeSha256, name), name);
  }
  for (const spec of REGRESSIONS) {
    const source = await text0(spec.path);
    assert.equal(digest0(source), spec.sourceContractSha256, spec.path);
    assert.deepEqual(printed0(source), spec.printedNames, spec.path);
    assert.deepEqual([...source.matchAll(/^import (\S+)\s*$/gmu)].map(row => row[1]), spec.imports, spec.path);
    assert.doesNotMatch(stripLeanCommentsAndStrings0(source), /\b(?:sorry|admit|native_decide|unsafe)\b|#eval!/u);
    for (const name of spec.printedNames) assert.ok(AXIOM_NAMES.includes(canonicalPrinted0(name)), name);
  }
});

test('M272 preflight: root audit names are fully qualified and regression aliases are explicit', () => {
  assert.ok(AXIOM_NAMES.every(name => /^PNP\.[A-Za-z0-9_.]+$/u.test(name)));
  assert.deepEqual(Object.keys(PRINT_ALIASES), [
    'GateRenaming.decode_encode', 'GateRenaming.encode_length_le', 'GateRenaming.validCode_encode',
  ]);
  for (const [short, qualified] of Object.entries(PRINT_ALIASES)) {
    assert.equal(qualified, 'PNP.DirectWire.StructuralReindexing.' + short);
    assert.ok(AXIOM_NAMES.includes(qualified));
    assert.ok(!AXIOM_NAMES.includes(short));
  }
});
