import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import {
  DeriveFormalPublication0, MilestoneTheoremKernelTypeSha2560,
  REQUIRED_MILESTONE_THEOREMS0, stableStringify0,
} from '../formal-publication0.mjs';
import {CheckFormalReconstructionStatus0} from '../pcc-formal-reconstruction-status0.mjs';
import {validateProofProgress0} from '../pcc-proof-progress0.mjs';

// Compiled pins and claims frozen after review, never regenerated by the tests.
const REVIEWED = [
  [
    "PNP.DirectWire.WireHistoryArbitrarySupport.closedHistory_dependencyInterfaceBound",
    "7e91a6ba071a60d7acf5537dbbbe7b92588c7600b8794ff29854f641389e8269",
    "PNP.NANDWireDescendantCausalBounds",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantHistory.StageCompilation.output_dependency_bound",
    "6e06d53b0ca176147a923beda5e13fc201257842680b13b7eb0f4e21223d0a5a",
    "PNP.NANDWireDescendantCausalBounds",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantHistory.CompiledRun.output_dependency_bound",
    "3bdab1852a89654374cec56b8b06c23c1d5cc963d33ff2842a254db07836af98",
    "PNP.NANDWireDescendantCausalBounds",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantHistory.CompiledRun.extracted_causalInterfaceBound",
    "9df4cab63a5443ed3c4383553ff5ab1cd7e5a3983b2010d83240b1070703e5d3",
    "PNP.NANDWireDescendantCausalBounds",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantHistory.CompiledRun.extracted_compiles",
    "47a4a1c20244f1b93aa6fa03c58b88b07ccd74498e37eb645adcf966d095f65e",
    "PNP.NANDWireDescendantCausalBounds",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.proper_iff_exterior_positive",
    "d9d08cfb9dadac80b033e39f4954d427cc8003d8cd3d11aae930bb0b6aabb20c",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.open_equivalent",
    "1554f92d8ccf86c4c94a7040f18a301073fd5f2b22e704da9e7c3d2652b2a9fe",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.output",
    "3d4007aa676175bca9da0e38c0fa81c4f55bba457806bbb6d8e76ff919f74b98",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.field",
    "1c982a9e13a376f2b044aa8e95655cea80ea5b09b61717cb7c91612d6bdf67d7",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.gateCount",
    "33ddeedba50fed2e7aeaf3b1d6fdb85128563c912e933424241f611ee8559003",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.charge_accounting",
    "43cf1de7e6f4a89dac1ecaca41999c83bfb01c5c210adc9c82f9ca8a9b93665f",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.gain_iff_local_gain",
    "f2e0f4bf14a3821fd89e9c15ed3ebaa66038e58d2022e7162257f22cb3d9f6ae",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.gain_iff_net_charges",
    "254edea2db6faf6de9ff5991a1101fa5e98da7f95c4f249d54bf545b1c8de7b5",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.strictGain",
    "d52506d1fa99a40e31e1f65e2f346737f9650244c325df8e11db6053f5edc84c",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.strictResidualDescent",
    "9e078fc6943070e2127e757c87e5128553104a268aa22d0d44a8072ff0d9d99c",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.compile_complete",
    "f4fbc6327c464ccd90383ce7238d5fb48985e9d1075e44e99ee14febd197f77d",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.compile_exists_iff",
    "3595a28d541c127f3f9d1c1de45133e52de421ee6dedf8a6ba4b4d2bb70d89c1",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantProperSupport.compile_none_iff",
    "14ee8d6504fbb3d36d05a30c16804bb64c150c8cd1ffb3650c089d072e9e9e59",
    "PNP.NANDWireDescendantProperSupport",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.records_source",
    "438bd94195840fc2351650b23668de3ba131db36ca00a0afb7cb2edd51957d35",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.proper_support",
    "e65ada18451c48e87f3809e321a796e32610f9c00d5bcefee226644ef366aa59",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.output",
    "613f0f18269563e29aba6060065e1b52e3c6becc1e8da84472f6491519266eb7",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.field",
    "60e21b2c8a882cb82bf741e7692504669c9b5e9bd293e11ed11e23edb9ac2d65",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.gateCount",
    "7d350b53d51481dc1fe2d5cb4155b5c7aaf6b613052aa6112b9f1174d066ab07",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.charge_accounting",
    "adb98588ffdceb1296a68ddd61343e8d7939ffca2f812a5d44028ea8f5e9a401",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.strictGain",
    "d285a884b421f2610155e13482363543697a2250a40c1c302c7c46b4016f4732",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.strictResidualDescent",
    "b48c42a7f286f32d4c890f51d3c74b020fb19f9f3a24185e58fe5438a3855b46",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.verify_complete",
    "b9601cb040f7386418b4a280b37d283aecdf0792bee24994e9cc194583976d34",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.verify_exists_iff",
    "9eef87d6e1313ff9dda9650d8ef55854860a6b3f63686952b60d79caaeaf36a4",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.verify_sound",
    "a5ed083668d903a2e924c74f98357e3a846172464fa52e82eca97baee2e9a25b",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.verify_decode_none",
    "67515c26c4d5ea9d26bb89b38dea576d8697c0986dea37797c608fd550c67837",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.verify_run_none",
    "23b902698feb58606e2b576acb188dffc1d3517874bf49a8a892be7c851df74a",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.verify_not_proper",
    "6ae7df30920172cc87b581bb315bbd8fba9db594b35e52f85f30f03dc33b0389",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ],
  [
    "PNP.DirectWire.WireDescendantCertificate.verify_no_gain",
    "5de9ff869d71ff419c095435550f6276df8087016ebd6bf1da647f65743930c4",
    "PNP.NANDWireDescendantCertificate",
    [
      "Quot.sound",
      "propext"
    ]
  ]
];
const META = {
  "coordinate": "PNP-FORMAL-RECONSTRUCTION-STATUS-2026-09-17-268",
  "milestone": {
    "classification": "formalized-foundation-only",
    "id": "proper-descendant-certificates",
    "title": "Source-only proper-support certificates for descendant programs",
    "requiredTheorems": [
      "PNP.DirectWire.WireHistoryArbitrarySupport.closedHistory_dependencyInterfaceBound",
      "PNP.DirectWire.WireDescendantHistory.StageCompilation.output_dependency_bound",
      "PNP.DirectWire.WireDescendantHistory.CompiledRun.output_dependency_bound",
      "PNP.DirectWire.WireDescendantHistory.CompiledRun.extracted_causalInterfaceBound",
      "PNP.DirectWire.WireDescendantHistory.CompiledRun.extracted_compiles",
      "PNP.DirectWire.WireDescendantProperSupport.proper_iff_exterior_positive",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.open_equivalent",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.output",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.field",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.gateCount",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.charge_accounting",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.gain_iff_local_gain",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.gain_iff_net_charges",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.strictGain",
      "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.strictResidualDescent",
      "PNP.DirectWire.WireDescendantProperSupport.compile_complete",
      "PNP.DirectWire.WireDescendantProperSupport.compile_exists_iff",
      "PNP.DirectWire.WireDescendantProperSupport.compile_none_iff",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.records_source",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.proper_support",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.output",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.field",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.gateCount",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.charge_accounting",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.strictGain",
      "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.strictResidualDescent",
      "PNP.DirectWire.WireDescendantCertificate.verify_complete",
      "PNP.DirectWire.WireDescendantCertificate.verify_exists_iff",
      "PNP.DirectWire.WireDescendantCertificate.verify_sound",
      "PNP.DirectWire.WireDescendantCertificate.verify_decode_none",
      "PNP.DirectWire.WireDescendantCertificate.verify_run_none",
      "PNP.DirectWire.WireDescendantCertificate.verify_not_proper",
      "PNP.DirectWire.WireDescendantCertificate.verify_no_gain"
    ],
    "scope": "For arbitrary finite computational wire-carrier dimensions, raw outer support records and raw descendant programs, source-only verification decodes every outer coordinate and executes the complete local program on the extracted source. Arbitrary-label dependency bounds follow actual execution and derive literal outer compilation without a supplied wiring order or successful-splice premise. Acceptance is exactly complete decoding, successful complete local execution, proper physical support and strict final local saving. The constructed one-copy ambient splice preserves all ordinary outputs and literal fields, retains the actual run and compiler receipts, and satisfies exact historical charge/removal accounting. Intermediate expansion is permitted; invalid coordinates, a failed later stage, whole support and final nondecrease reject. Every accepted certificate yields StrictEquivalentGain and strict residual descent without supplied intermediate circuits, correctness, owners, costs, ranks or semantic oracles.",
    "nonClaim": "This verifies offered finite programs in the existing closed computational wire-carrier language. It does not prove that every nonminimal input has an accepted certificate, construct a globally successful strategy, derive terminal families or establish local minimality after rejection. Full manuscript profiles, all R1-R9 and N1-N10 rule families, cross-support transport of open obligations, matched-kappa arbitrary-support Pull/Expand, full manuscript VerifyDW, ChargeSoundness and Package E remain open. No bound on temporary growth, encoded-input polynomial runtime, output size or certificate size is proved. Global route coverage, unconditional SaturatePositive, BCELReady and ZeroSlack, exact general PCCMin, deterministic CNFSAT in P and the eligible root remain open. Runtime fixtures are regression evidence, not theorem authority. No fixed weighted checkpoint or global gate closes, and P = NP is not proved."
  },
  "statusFields": {
    "leanProperDescendantCertificatesFormalized": true,
    "leanProperDescendantCertificatesAxiomAuditPassed": true,
    "leanProperDescendantCertificatesAuditedDeclarationCount": 33,
    "leanProperDescendantCertificatesArbitraryLabelCausalBoundTheorem": "PNP.DirectWire.WireDescendantHistory.CompiledRun.output_dependency_bound",
    "leanProperDescendantCertificatesDerivedOuterCompilationTheorem": "PNP.DirectWire.WireDescendantHistory.CompiledRun.extracted_compiles",
    "leanProperDescendantCertificatesCompleteOuterCompilationTheorem": "PNP.DirectWire.WireDescendantProperSupport.compile_complete",
    "leanProperDescendantCertificatesProperSupportIffTheorem": "PNP.DirectWire.WireDescendantProperSupport.proper_iff_exterior_positive",
    "leanProperDescendantCertificatesAmbientHistoricalAccountingTheorem": "PNP.DirectWire.WireDescendantProperSupport.SplicedRun.charge_accounting",
    "leanProperDescendantCertificatesCompleteAcceptanceIffTheorem": "PNP.DirectWire.WireDescendantCertificate.verify_exists_iff",
    "leanProperDescendantCertificatesSourceRoundTripTheorem": "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.records_source",
    "leanProperDescendantCertificatesOrdinaryOutputPreservationTheorem": "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.output",
    "leanProperDescendantCertificatesLiteralFieldPreservationTheorem": "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.field",
    "leanProperDescendantCertificatesStrictGainTheorem": "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.strictGain",
    "leanProperDescendantCertificatesStrictResidualDescentTheorem": "PNP.DirectWire.WireDescendantCertificate.CheckedCertificate.strictResidualDescent",
    "leanProperDescendantCertificatesFailedCompleteProgramRejectionTheorem": "PNP.DirectWire.WireDescendantCertificate.verify_run_none",
    "leanProperDescendantCertificatesWholeSupportRejectionTheorem": "PNP.DirectWire.WireDescendantCertificate.verify_not_proper",
    "leanProperDescendantCertificatesNondecreaseRejectionTheorem": "PNP.DirectWire.WireDescendantCertificate.verify_no_gain",
    "leanProperDescendantCertificatesArbitraryFiniteDimensionsAndProgramsCovered": true,
    "leanProperDescendantCertificatesRawSourceOnlyCertificate": true,
    "leanProperDescendantCertificatesCompleteProgramRequired": true,
    "leanProperDescendantCertificatesOuterAcyclicityDerivedFromExecution": true,
    "leanProperDescendantCertificatesProperPhysicalSupportRequired": true,
    "leanProperDescendantCertificatesStrictFinalLocalSavingRequired": true,
    "leanProperDescendantCertificatesAllOrdinaryOutputsAndLiteralFieldsPreserved": true,
    "leanProperDescendantCertificatesExteriorOccursExactlyOnce": true,
    "leanProperDescendantCertificatesActualHistoricalChargeRemovalBalancePreserved": true,
    "leanProperDescendantCertificatesIntermediateExpansionAllowed": true,
    "leanProperDescendantCertificatesCallerSuppliedCorrectnessOrIntermediateCircuitRequired": false,
    "leanProperDescendantCertificatesCallerSuppliedOrderOrSuccessfulSpliceRequired": false,
    "leanProperDescendantCertificatesCallerSuppliedCostsOrOwnersRequired": false,
    "leanProperDescendantCertificatesAcceptedPrefixReturnedAfterLaterRejection": false,
    "leanProperDescendantCertificatesRejectedCertificateProvesLocalMinimality": false,
    "leanProperDescendantCertificatesAcceptedCertificateForEveryNonminimalInputProved": false,
    "leanProperDescendantCertificatesGloballySuccessfulStrategyDerived": false,
    "leanProperDescendantCertificatesFullManuscriptVerifyDWProved": false,
    "leanProperDescendantCertificatesFullManuscriptProfilesAndRuleFamiliesProved": false,
    "leanProperDescendantCertificatesOpenObligationsTransportedAcrossSupports": false,
    "leanProperDescendantCertificatesCompleteChargeSoundnessProved": false,
    "leanProperDescendantCertificatesCompletePackageEProved": false,
    "leanProperDescendantCertificatesTerminalFamiliesDerived": false,
    "leanProperDescendantCertificatesGlobalRouteCoverageProved": false,
    "leanProperDescendantCertificatesUnconditionalSaturatePositiveProved": false,
    "leanProperDescendantCertificatesUnconditionalBCELReadyProved": false,
    "leanProperDescendantCertificatesUnconditionalZeroSlackProved": false,
    "leanProperDescendantCertificatesExactGeneralPCCMinProved": false,
    "leanProperDescendantCertificatesPolynomialRuntimeOutputAndCertificateBoundsProved": false,
    "leanProperDescendantCertificatesRuntimeExecutionIsProofAuthority": false,
    "leanProperDescendantCertificatesScope": "arbitrary-finite-computational-wire-carriers-source-only-raw-records-and-complete-descendant-programs-derived-causal-literal-splice-proper-support-strict-final-saving-all-output-and-field-preservation-exact-historical-costs-intermediate-expansion-no-global-certificate-discovery-or-full-manuscript-profiles-or-polynomial-runtime"
  },
  "audit": "lean-audit/PNPProperDescendantCertificateAxiomAudit.lean",
  "testFiles": [
    "audits/lean-proper-descendant-certificates0.test.mjs",
    "audits/lean-proper-descendant-certificates-publication0.test.mjs"
  ],
  "doc": "docs/lean_proper_descendant_certificates.md",
  "plan": "docs/plans/2026-09-17-proper-descendant-certificates.md",
  "command": "node --test audits/lean-proper-descendant-certificates0.test.mjs audits/lean-proper-descendant-certificates-publication0.test.mjs",
  "workflowCommands": "set -euo pipefail\nnode scripts/check-lean-axioms.mjs lean-audit/PNPProperDescendantCertificateAxiomAudit.lean\nfor part in CausalBounds ProperSupport Certificate; do\n  lake env lean -DwarningAsError=true \"lean-regression/PNPWireDescendant${part}.lean\"\ndone\n",
  "publicationDecision": "Publication decision: defer. The source-only proper-support verifier closes the computational offered-program acceptance edge, not full manuscript VerifyDW or certificate discovery for arbitrary nonminimal inputs. No fixed weighted checkpoint or global gate changes, and the published global bottom line remains unchanged. Preserve the coherent M264 website pin and batch pending core evidence at the next major publication."
};
const PARTS = ['CausalBounds','ProperSupport','Certificate'];
const text0 = file=>readFile(new URL('../'+file,import.meta.url),'utf8');
const canonical0 = value=>Buffer.from(stableStringify0(value)+'\n');
const prose0 = value=>value.replaceAll('**','').replace(/\s+/gu,' ').trim();
let loaded;
function sources0() {
  loaded??=Promise.all([
    text0('status/FORMAL_RECONSTRUCTION_STATUS.json'),text0('status/LEAN_THEOREM_INVENTORY.json'),
    text0('status/PROOF_PROGRESS.json'),text0('publication/FORMAL_PUBLICATION_MAP.json'),
  ]).then(([status,inventory,progress,map])=>({
    status:JSON.parse(status),inventory:JSON.parse(inventory),inventoryBytes:Buffer.from(inventory),
    progress:JSON.parse(progress),map:JSON.parse(map),
  }));
  return loaded;
}

test('M268 preflight: exact root, names, scripts and durable workflow share one boundary',async()=>{
  const [root,audit,probe,pkg,surface,verifier,workflow,mapText]=await Promise.all([
    text0('lean/PNP.lean'),text0(META.audit),text0('lean-audit/PNPTheoremInventory.lean'),
    text0('package.json'),text0('pcc-formal-public-surface0.mjs'),text0('scripts/pnp-verify-all.mjs'),
    text0('.github/workflows/lean-bridge.yml'),text0('publication/FORMAL_PUBLICATION_MAP.json'),
  ]);
  assert.equal(REVIEWED.length,33);
  const names=REVIEWED.map(row=>row[0]);
  assert.equal(new Set(names).size,33);
  assert.deepEqual(names,META.milestone.requiredTheorems);
  assert.match(audit,/^import PNP$/mu);
  assert.deepEqual([...audit.matchAll(/^#print axioms\s+(\S+)\s*$/gmu)].map(match=>match[1]),names);
  for(const part of PARTS)assert.ok(root.includes('import PNP.NANDWireDescendant'+part));
  for(const name of names) {
    assert.equal(probe.split(String.fromCharCode(96)+name+',').length-1,1,name);
    assert.equal(REQUIRED_MILESTONE_THEOREMS0.filter(value=>value===name).length,1,name);
  }
  assert.equal(JSON.parse(pkg).scripts['audit:m268'],META.command);
  assert.ok(surface.includes("'audit:m268': '"+META.command+"'"));
  for(const file of META.testFiles)assert.ok(verifier.includes("'"+file+"'"),file);
  assert.ok(workflow.includes('run: npm run audit:m268'));
  const steps=workflow.split(/^      - name:/mu).filter(step=>
    step.includes('node scripts/check-lean-axioms.mjs '+META.audit));
  assert.equal(steps.length,1);
  const block=steps[0].split('        run: |\n')[1];
  assert.ok(block);
  assert.equal(block.trimEnd().split('\n').map(line=>line.slice(10)).join('\n')+'\n',META.workflowCommands);
  assert.ok(workflow.includes('node --test audits/lean-axiom-transcript0.test.mjs'));
  const map=JSON.parse(mapText),row=map.milestones.find(item=>item.id===META.milestone.id);
  const coordinateGuard=(await text0('formal-publication0.mjs'))
    .match(/if \(map\.coordinate !== '([^']+)'\)/u);
  assert.equal(coordinateGuard?.[1],map.coordinate,'map coordinate guard must precede generated-status validation');
  assert.deepEqual(row,META.milestone);
  for(const [name,hash] of REVIEWED) {
    assert.match(hash,/^[0-9a-f]{64}$/u);
    assert.notEqual(hash,'0'.repeat(64),name);
    assert.equal(map.earnedMilestoneTheoremKernelTypeSha256[name],hash,name);
  }
});

test('M268 release: compiled theorem types and exact axiom closures support only reviewed claims',async()=>{
  const {status,inventory,inventoryBytes,map}=await sources0();
  assert.ok(canonical0(inventory).equals(inventoryBytes));
  const publication=DeriveFormalPublication0(inventory,map,inventoryBytes,status.leanSourceClosureSha256);
  const row=publication.milestones.find(item=>item.id===META.milestone.id);
  assert.equal(row?.earned,true);
  for(const field of ['classification','requiredTheorems','scope','nonClaim'])
    assert.deepEqual(row[field],META.milestone[field],field);
  for(const [name,hash,module,axioms] of REVIEWED) {
    for(const collection of [inventory.declarations,inventory.milestoneCandidates]) {
      const found=collection.filter(item=>item.name===name);
      assert.equal(found.length,1,name);
      assert.equal(found[0].kind,'theorem',name);
      assert.equal(found[0].module,module,name);
      assert.deepEqual(found[0].axioms,axioms,name);
    }
    assert.ok(axioms.every(value=>['propext','Quot.sound'].includes(value)),name);
    const candidate=inventory.milestoneCandidates.find(item=>item.name===name);
    assert.equal(MilestoneTheoremKernelTypeSha2560(name,candidate.kernelType),hash,name);
    assert.equal(map.earnedMilestoneTheoremKernelTypeSha256[name],hash,name);
  }
  for(const [field,value] of Object.entries(META.statusFields))
    assert.deepEqual(status[field],value,field);
});

test('M268 release: weakened types and supplied authority cannot retain earned credit',async()=>{
  const {status,inventory,map}=await sources0();
  const alternatives=new Map();
  for(const [name,hash] of REVIEWED) {
    const current=inventory.milestoneCandidates.find(row=>row.name===name).kernelType;
    const changed=[
      'Lean.Expr.const '+String.fromCharCode(96)+'True []',
      'Lean.Expr.forallE '+String.fromCharCode(96)+'supplied ('+current+') ('+current+') (Lean.BinderInfo.default)',
    ];
    for(const type of changed)assert.notEqual(MilestoneTheoremKernelTypeSha2560(name,type),hash,name);
    alternatives.set(name,changed);
  }
  // Exercise every pin above; serialize the large inventory only for one
  // representative of each affected module and each distinct mutation kind.
  for(const name of new Map(REVIEWED.map(row=>[row[2],row[0]])).values())
    for(const type of alternatives.get(name)) {
      const mutation={...inventory,milestoneCandidates:inventory.milestoneCandidates.map(row=>
        row.name===name?{...row,kernelType:type}:row)};
      const result=DeriveFormalPublication0(mutation,map,canonical0(mutation),status.leanSourceClosureSha256);
      assert.equal(result.milestones.find(row=>row.id===META.milestone.id).earned,false,name);
      assert.equal(result.gate.passed,false);
    }
});

test('M268 release: missing evidence, project axioms and widened scope reject',async()=>{
  const {status,inventory,inventoryBytes,map}=await sources0();
  const name='PNP.DirectWire.WireDescendantCertificate.verify_exists_iff';
  const addAuthority=row=>row.name===name?{...row,axioms:['PNP.UnauthorizedAuthority','Quot.sound','propext']}:row;
  const mutation={...inventory,declarations:inventory.declarations.map(addAuthority),
    milestoneCandidates:inventory.milestoneCandidates.map(addAuthority)};
  const result=DeriveFormalPublication0(mutation,map,canonical0(mutation),status.leanSourceClosureSha256);
  assert.equal(result.milestones.find(row=>row.id===META.milestone.id).earned,false);
  assert.equal(result.gate.passed,false);
  const missing={...inventory,milestoneCandidates:inventory.milestoneCandidates.filter(row=>row.name!==name)};
  assert.throws(()=>DeriveFormalPublication0(missing,map,canonical0(missing),status.leanSourceClosureSha256),
    /reviewed milestone theorem candidate inventory mismatch/u);
  for(const field of ['scope','nonClaim']) {
    const widened={...map,milestones:map.milestones.map(row=>row.id===META.milestone.id
      ?{...row,[field]:'Every nonminimal input has a polynomially discoverable full manuscript certificate.'}:row)};
    assert.throws(()=>DeriveFormalPublication0(inventory,widened,inventoryBytes,status.leanSourceClosureSha256),
      /map drifted from the reviewed specification/u);
  }
  const changedPin={...map,earnedMilestoneTheoremKernelTypeSha256:{
    ...map.earnedMilestoneTheoremKernelTypeSha256,[name]:'0'.repeat(64)}};
  assert.throws(()=>DeriveFormalPublication0(inventory,changedPin,inventoryBytes,status.leanSourceClosureSha256),
    /map drifted from the reviewed specification/u);
});

test('M268 release: status rejects widened acceptance, full-scope and complexity claims',async()=>{
  const {status}=await sources0();
  for(const suffix of [
    'CompleteAcceptanceIffTheorem','AuditedDeclarationCount','ProperPhysicalSupportRequired',
    'CallerSuppliedOrderOrSuccessfulSpliceRequired','AcceptedCertificateForEveryNonminimalInputProved',
    'FullManuscriptVerifyDWProved','PolynomialRuntimeOutputAndCertificateBoundsProved','Scope',
  ]) {
    const field='leanProperDescendantCertificates'+suffix,value=META.statusFields[field];
    assert.notEqual(value,undefined,field);
    const mutation={...status,[field]:typeof value==='boolean'?!value:
      typeof value==='number'?value+1:value+':unreviewed'};
    const result=await CheckFormalReconstructionStatus0({writeOutput:false,statusOverride:mutation,siteOverride:mutation});
    assert.equal(result.tag,'reject',field);
    assert.equal(result.coord,'FormalReconstructionStatus.Field',field);
    assert.deepEqual(result.path,['status/FORMAL_RECONSTRUCTION_STATUS.json',field],field);
  }
});

test('M268 release: offered-program verification does not earn an unconditional checkpoint',async()=>{
  const {status,inventory,progress}=await sources0();
  assert.equal(validateProofProgress0(progress,status,inventory).tag,'accept');
  const reviews=progress.history.filter(row=>row.asOfCoordinate===META.coordinate);
  assert.equal(reviews.length,1);
  const review=reviews[0];
  assert.equal(review.scoreChanged,false);
  assert.deepEqual(review.changedCheckpointIds,[]);
  assert.deepEqual(review.changeRecords,[]);
  assert.equal(review.riskWeightedProofCompletionPercent,40);
  assert.equal(review.uncertaintyLowPercent,20);
  assert.equal(review.uncertaintyHighPercent,40);
  assert.equal(review.globalGatesClosed,0);
  assert.equal(review.globalGatesAvailable,5);
  assert.ok(prose0(review.rationale).includes('No fixed load-bearing checkpoint changes state'));
  if(progress.asOfCoordinate!==META.coordinate)return;
  assert.deepEqual(review.formalArtefactCoverage,{
    earnedRows:status.formalPublicationMilestones.filter(row=>row.earned).length,
    totalRows:status.formalPublicationMilestones.length,
  });
  assert.deepEqual(progress.tracks.map(track=>track.pointsEarned),[13,20,2,1,4]);
  assert.equal(progress.proofCompletion.percent,40);
  assert.equal(progress.globalGates.length,5);
  assert.ok(progress.globalGates.every(gate=>gate.status==='open'));
  assert.deepEqual(inventory.projectAxioms,[]);
  assert.deepEqual(progress.projectSpecificAxiomsRemaining,[]);
  assert.equal(inventory.declarations.some(row=>row.name==='PNP.Main.p_eq_np'),false);
  assert.equal(status.leanConcreteCNFSATInPFormalized,false);
  assert.equal(status.concretePublicationGate.passed,false);
  assert.equal(progress.publicationGate.passed,false);
  assert.deepEqual(progress.rootTheorem,{name:'PNP.Main.p_eq_np',present:false,built:false,axiomAuditPassed:false});
  const inflated=structuredClone(progress);
  inflated.proofCompletion.pointsEarned+=1;
  inflated.proofCompletion.percent+=1;
  assert.throws(()=>validateProofProgress0(inflated,status,inventory),error=>error.code==='ProofCompletion.StoredEarned');
});

test('M268 release: current documentation separates coverage, estimate and publication decision',async()=>{
  const {progress}=await sources0();
  const doc=prose0(await text0(META.doc)),plan=prose0(await text0(META.plan));
  assert.ok(doc.includes(META.coordinate));
  assert.ok(doc.includes(prose0(META.milestone.scope)));
  assert.ok(doc.includes(prose0(META.milestone.nonClaim)));
  assert.ok(doc.includes(prose0(META.publicationDecision)));
  assert.ok(plan.includes('Publication decision: defer'));
  if(progress.asOfCoordinate!==META.coordinate)return;
  const p=progress.proofCompletion,a=progress.formalArtefactCoverage;
  const metrics=[
    'Formal artefact coverage: '+a.earnedRows+' of '+a.totalRows+' current scoped publication rows earned.',
    'Risk-weighted proof completion estimate: '+p.percent+'%.',
    'Uncertainty range: '+p.uncertaintyLowPercent+'% to '+p.uncertaintyHighPercent+'%.',
    'Global gates closed: '+progress.globalGates.filter(gate=>gate.status==='closed').length+' of 5.',
  ];
  for(const file of ['README.md','docs/FORMAL_RECONSTRUCTION.md','docs/lean_bridge.md',
    'docs/proof_pipeline.md','docs/audit_questions.md','docs/proof_progress.md',META.doc]) {
    const current=prose0(await text0(file));
    for(const metric of metrics)assert.ok(current.includes(metric),file+': '+metric);
  }
});
