import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {test} from 'node:test';
import {
  explicitLeanDeclarationHeads0, hasLeanAssumptionDeclaration0,
  hasUnauditedLeanDeclarationForm0, stripLeanCommentsAndStrings0,
} from './lean-source-declarations0.mjs';

// Frozen from the kernel-checked research source; never regenerated by tests.
const SPECS = [
  {
    "file": "lean/PNP/NANDCompatibleSupportSlackMinimum.lean",
    "sourceContractSha256": "18e5ac3fa44135bb851b23f70c5560f12b170c1b61741133d8489efac48276e3",
    "heads": [
      {
        "kind": "def",
        "name": "originalProgram"
      },
      {
        "kind": "def",
        "name": "original"
      },
      {
        "kind": "def",
        "name": "records"
      },
      {
        "kind": "def",
        "name": "support"
      },
      {
        "kind": "def",
        "name": "smallerProgram"
      },
      {
        "kind": "def",
        "name": "smaller"
      },
      {
        "kind": "def",
        "name": "valuation"
      },
      {
        "kind": "def",
        "name": "openValuation"
      },
      {
        "kind": "def",
        "name": "freeValue"
      },
      {
        "kind": "def",
        "name": "formula"
      },
      {
        "kind": "theorem",
        "name": "formula_exact"
      },
      {
        "kind": "theorem",
        "name": "baseline"
      },
      {
        "kind": "theorem",
        "name": "no_output_is_first_nand"
      },
      {
        "kind": "theorem",
        "name": "gate_lower_bound"
      },
      {
        "kind": "theorem",
        "name": "original_is_minimum"
      },
      {
        "kind": "theorem",
        "name": "original_reference_minimum"
      },
      {
        "kind": "theorem",
        "name": "global_slack_zero"
      }
    ]
  },
  {
    "file": "lean/PNP/NANDCompatibleSupportSlackComparison.lean",
    "sourceContractSha256": "cb765cad0feafcf46ff168188fcd7ded7477f87d2ebeceb7d7960ca845cf9570",
    "heads": [
      {
        "kind": "theorem",
        "name": "boundary_exact"
      },
      {
        "kind": "theorem",
        "name": "interface_exact"
      },
      {
        "kind": "theorem",
        "name": "selected_gate_count"
      },
      {
        "kind": "def",
        "name": "offered"
      },
      {
        "kind": "def",
        "name": "openFormula"
      },
      {
        "kind": "theorem",
        "name": "smaller_formula_exact"
      },
      {
        "kind": "def",
        "name": "comparison"
      },
      {
        "kind": "theorem",
        "name": "same_open_function"
      },
      {
        "kind": "theorem",
        "name": "comparison_reference_minimum"
      },
      {
        "kind": "theorem",
        "name": "literal_splice_is_cyclic"
      }
    ]
  },
  {
    "file": "lean/PNP/NANDCompatibleSupportSlackObstruction.lean",
    "sourceContractSha256": "38791da313777278daf61c2760852967f7e492022bcc049c9b9f1cc95428414a",
    "heads": [
      {
        "kind": "theorem",
        "name": "open_baseline"
      },
      {
        "kind": "theorem",
        "name": "local_reference_minimum"
      },
      {
        "kind": "theorem",
        "name": "local_slack_one"
      },
      {
        "kind": "theorem",
        "name": "global_slack_law_violation"
      }
    ]
  }
];

const text0 = file => readFile(new URL('../' + file, import.meta.url), 'utf8');
const digest0 = source => createHash('sha256')
  .update(stripLeanCommentsAndStrings0(source).replace(/\s+/gu, ' ').trim()).digest('hex');
function inspect0(spec, source) {
  const issues = [];
  if (hasLeanAssumptionDeclaration0(source)) issues.push('assumption declaration');
  if (hasUnauditedLeanDeclarationForm0(source)) issues.push('unaudited declaration');
  if (/\b(?:sorry|admit|unsafe|native_decide)\b|decide\s+\+native/u.test(stripLeanCommentsAndStrings0(source)))
    issues.push('unchecked authority');
  const heads = explicitLeanDeclarationHeads0(source).map(({kind, name}) => ({kind, name}));
  if (JSON.stringify(heads) !== JSON.stringify(spec.heads)) issues.push('changed public interface');
  if (digest0(source) !== spec.sourceContractSha256) issues.push('changed reviewed contract');
  return issues;
}
async function reject0(module, mutations) {
  const spec = SPECS.find(row => row.file === 'lean/PNP/' + module + '.lean');
  assert.ok(spec, module);
  const source = await text0(spec.file);
  assert.deepEqual(inspect0(spec, source), []);
  for (const [label, before, after] of mutations) {
    assert.ok(source.includes(before), 'mutation anchor absent: ' + label);
    const changed = source.replace(before, () => after);
    assert.notEqual(changed, source, label);
    assert.ok(inspect0(spec, changed).length > 0, 'accepted mutation: ' + label);
  }
}
test('slack obstruction sources retain the reviewed statements and allow comment-only prose', async () => {
  for (const spec of SPECS) {
    const source = await text0(spec.file);
    assert.deepEqual(inspect0(spec, source), [], spec.file);
    assert.deepEqual(inspect0(spec, source + '\n/- explanatory prose -/\n'), [], spec.file);
  }
});
test('slack obstruction sources reject supplied authority and native proof shortcuts', async () => {
  for (const spec of SPECS) {
    const source = await text0(spec.file);
    for (const extra of [
      'axiom suppliedMinimum : True', 'private axiom suppliedSlack : True',
      'opaque suppliedMinimum : True', 'theorem invented : True := by sorry',
      'example : True := by trivial', 'variable (suppliedMinimum : Prop)',
      'theorem nativeAuthority : True := by native_decide',
    ]) assert.ok(inspect0(spec, source + '\n' + extra + '\n').length > 0, spec.file);
  }
});
test('slack obstruction whole minimum stays universal and uses the literal source', async () => {
  await reject0('NANDCompatibleSupportSlackMinimum', [
    ['arbitrary competitor size', '(offered : Candidate 4 gates 10)', '(offered : Candidate 4 11 10)'],
    ['strict whole lower bound', ': 11 ≤ gates := by', ': 10 ≤ gates := by'],
    ['complete actual support', '.gate 0, .gate 1, .gate 4', '.gate 0, .gate 4'],
    ['whole reference minimum', 'referenceMinimum original.toImplementation = 11', 'referenceMinimum original.toImplementation = 10'],
  ]);
});
test('slack obstruction compares the actual extracted open function and rejected splice', async () => {
  await reject0('NANDCompatibleSupportSlackComparison', [
    ['incoming exterior wire', 'support.boundary = [.input 0, .input 1, .gate 3]', 'support.boundary = [.input 0, .input 1]'],
    ['complete outgoing interface', 'support.interface = [1, 4, 5, 6, 7, 8, 9, 10]', 'support.interface = [4, 5, 6, 7, 8, 9, 10]'],
    ['actual extractor', 'def comparison := extractedAtPorts original records', 'def comparison := offered'],
    ['independent open equivalence', 'Equivalent offered.program offered.directWireWord', 'Equivalent comparison.program comparison.directWireWord'],
    ['acyclicity rejection', ').isNone = true', ').isNone = false'],
  ]);
});
test('slack obstruction exact minima and strict inequality cannot be weakened', async () => {
  await reject0('NANDCompatibleSupportSlackObstruction', [
    ['actual open minimum', 'referenceMinimum support.extractedCandidate.toImplementation = 8', 'referenceMinimum support.extractedCandidate.toImplementation = 9'],
    ['positive local slack', 'residualSlack support.extractedCandidate.toImplementation = 1', 'residualSlack support.extractedCandidate.toImplementation = 0'],
    ['refuted inequality', '¬ residualSlack support.extractedCandidate.toImplementation ≤', '¬ residualSlack support.extractedCandidate.toImplementation <'],
  ]);
});
test('slack obstruction integration audits every public theorem through the explicit root', async () => {
  const root = await text0('lean/PNP.lean');
  const audit = await text0('lean-audit/PNPCompatibleSupportSlackObstructionAxiomAudit.lean');
  const regression = await text0('lean-regression/PNPCompatibleSupportSlackObstructionProbe.lean');
  for (const spec of SPECS) {
    const module = spec.file.replace('lean/', '').replaceAll('/', '.').replace('.lean', '');
    assert.equal(root.split('\n').filter(line => line === 'import ' + module).length, 1);
  }
  const names = SPECS.flatMap(spec => spec.heads.filter(head => head.kind === 'theorem')
    .map(head => 'PNP.DirectWire.CompatibleSupportSlackObstruction.' + head.name)).sort();
  assert.equal(names.length, 18);
  assert.match(audit, /^import PNP\n/u);
  assert.deepEqual([...audit.matchAll(/^#print axioms (\S+)$/gmu)].map(row => row[1]).sort(), names);
  assert.match(regression, /^import PNP\n/u);
  assert.doesNotMatch(regression, /\b(?:sorry|admit|native_decide|referenceMinimum)\b/u);
  for (const guard of [
    'original.toImplementation.gateCount != 11', 'support.gateCount != 9',
    'smaller.toImplementation.gateCount != 8',
    'equivalentBool offered comparison != true',
    '(ArbitrarySupportSplice.compile original records offered).isNone != true',
    '(ArbitrarySupportSplice.compile original records comparison).isSome != true',
    'equivalentBool wrong comparison != false',
    'original.semantics (valuation value) output != expected (valuation value) output',
    'compatible-support-slack-obstruction-regressions-passed',
  ]) assert.ok(regression.includes(guard), guard);
});
test('slack obstruction integration is in the durable workflow and verifier coverage', async () => {
  const workflow = await text0('.github/workflows/lean-bridge.yml');
  const verifier = await import('../scripts/pnp-verify-all.mjs');
  for (const file of [
    'audits/lean-compatible-support-slack-obstruction0.test.mjs',
    'audits/lean-compatible-support-slack-obstruction-publication0.test.mjs',
  ]) {
    assert.ok(verifier.CURRENT_VERIFICATION_TESTS0.includes(file), file);
    assert.ok(workflow.includes(file), file);
  }
  for (const command of [
    'node scripts/check-lean-axioms.mjs lean-audit/PNPCompatibleSupportSlackObstructionAxiomAudit.lean',
    'lake env lean -DwarningAsError=true lean-regression/PNPCompatibleSupportSlackObstructionProbe.lean',
  ]) assert.ok(workflow.includes(command), command);
});
test('slack obstruction documentation states the restricted scope and awards no completion credit', async () => {
  const doc = (await text0('docs/lean_compatible_support_slack_obstruction.md')).replace(/\s+/gu, ' ');
  for (const text of [
    'unrestricted raw-port-completeness',
    'not a refutation of the checked acyclic framed law',
    'No positive publication row or fixed checkpoint is awarded',
    'full-profile admissibility and first-loss routing remain open',
  ]) assert.ok(doc.includes(text), text);
});
